/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_custom_load_start(void) {
}

static void screen_load_start (lv_event_t *e) {
    screen_custom_load_start();
}


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_grad_dir(scr->obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(scr->obj, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(scr->obj, lv_color_hex(0x98faff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->logo
    scr->logo = lv_img_create(scr->obj);
    lv_img_set_src(scr->logo, LVGL_IMAGE_PATH(logo_300x85.png));
    lv_img_set_pivot(scr->logo, 50, 50);
    lv_img_set_offset_x(scr->logo, 0);
    lv_img_set_offset_y(scr->logo, 0);
    lv_img_set_angle(scr->logo, 0);
    lv_obj_set_pos(scr->logo, 50, 20);

    // Init scr->temp_arc
    scr->temp_arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->temp_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->temp_arc, 160, 350);
    lv_arc_set_value(scr->temp_arc, 180);
    lv_arc_set_bg_angles(scr->temp_arc, 0, 360);
    lv_arc_set_angles(scr->temp_arc, 0, 37);
    lv_arc_set_rotation(scr->temp_arc, 90);
    lv_arc_set_change_rate(scr->temp_arc, 720);
    lv_obj_set_pos(scr->temp_arc, 50, 150);
    lv_obj_set_size(scr->temp_arc, 300, 300);

    // Set style of scr->temp_arc
    lv_obj_set_style_shadow_opa(scr->temp_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->temp_arc, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_label
    scr->temp_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp_label, "25.3");
    lv_label_set_long_mode(scr->temp_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp_label, 120, 245);
    lv_obj_set_size(scr->temp_label, 160, 86);

    // Set style of scr->temp_label
    lv_obj_set_style_text_align(scr->temp_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->temp_label, fs_droidsansfallback_70, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cold_hot
    scr->cold_hot = lv_img_create(scr->obj);
    lv_img_set_src(scr->cold_hot, LVGL_IMAGE_PATH(cold_40x40.png));
    lv_img_set_pivot(scr->cold_hot, 50, 50);
    lv_img_set_offset_x(scr->cold_hot, 0);
    lv_img_set_offset_y(scr->cold_hot, 0);
    lv_img_set_angle(scr->cold_hot, 0);
    lv_obj_set_pos(scr->cold_hot, 140, 340);

    // Set style of scr->cold_hot
    lv_obj_set_style_img_recolor(scr->cold_hot, lv_color_hex(0x55aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(scr->cold_hot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_uint
    scr->temp_uint = lv_img_create(scr->obj);
    lv_img_set_src(scr->temp_uint, LVGL_IMAGE_PATH(temp.png));
    lv_img_set_pivot(scr->temp_uint, 50, 50);
    lv_img_set_offset_x(scr->temp_uint, 0);
    lv_img_set_offset_y(scr->temp_uint, 0);
    lv_img_set_angle(scr->temp_uint, 0);
    lv_obj_set_pos(scr->temp_uint, 254, 233);

    // Init scr->temp_status
    scr->temp_status = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp_status, "Colding");
    lv_label_set_long_mode(scr->temp_status, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp_status, 170, 350);
    lv_obj_set_size(scr->temp_status, 100, 22);

    // Set style of scr->temp_status
    lv_obj_set_style_text_align(scr->temp_status, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->temp_status, fs_droidsansfallback_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_chart
    scr->temp_chart = lv_chart_create(scr->obj);
    lv_chart_set_type(scr->temp_chart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(scr->temp_chart, LV_CHART_AXIS_PRIMARY_Y, 160, 350);
    lv_chart_set_point_count(scr->temp_chart, 5);

    lv_obj_set_pos(scr->temp_chart, 30, 520);
    lv_obj_set_size(scr->temp_chart, 340, 120);

    // Set style of scr->temp_chart
    lv_obj_set_style_shadow_opa(scr->temp_chart, 56, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->temp_chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->temp_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->temp_chart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(scr->temp_chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(scr->temp_chart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(scr->temp_chart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(scr->temp_chart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->temp_chart, lv_color_hex(0xa1e0ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->temp_chart, 37, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->temp_chart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_container
    scr->arc_container = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->arc_container, 30, 720);
    lv_obj_set_size(scr->arc_container, 340, 150);
    lv_obj_set_scrollbar_mode(scr->arc_container, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->arc_container
    lv_obj_set_style_pad_right(scr->arc_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->arc_container, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->arc_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(scr->arc_container, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(scr->arc_container, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->arc_container, lv_color_hex(0xa1e3ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(scr->arc_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_container, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->arc_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->arc_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->arc_container, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->arc_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->fan_arc
    scr->fan_arc = lv_arc_create(scr->arc_container);
    lv_arc_set_mode(scr->fan_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->fan_arc, 0, 100);
    lv_arc_set_value(scr->fan_arc, 20);
    lv_arc_set_bg_angles(scr->fan_arc, 135, 45);
    lv_arc_set_angles(scr->fan_arc, 135, 189);
    lv_arc_set_rotation(scr->fan_arc, 0);
    lv_arc_set_change_rate(scr->fan_arc, 720);
    lv_obj_set_pos(scr->fan_arc, 20, 15);
    lv_obj_set_size(scr->fan_arc, 120, 120);

    // Init scr->humidity_arc
    scr->humidity_arc = lv_arc_create(scr->arc_container);
    lv_arc_set_mode(scr->humidity_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->humidity_arc, 0, 100);
    lv_arc_set_value(scr->humidity_arc, 20);
    lv_arc_set_bg_angles(scr->humidity_arc, 135, 45);
    lv_arc_set_angles(scr->humidity_arc, 135, 189);
    lv_arc_set_rotation(scr->humidity_arc, 0);
    lv_arc_set_change_rate(scr->humidity_arc, 720);
    lv_obj_set_pos(scr->humidity_arc, 200, 15);
    lv_obj_set_size(scr->humidity_arc, 120, 120);

    // Init scr->Humidity
    scr->Humidity = lv_label_create(scr->arc_container);
    lv_label_set_text(scr->Humidity, "Humidity");
    lv_label_set_long_mode(scr->Humidity, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->Humidity, 210, 60);
    lv_obj_set_size(scr->Humidity, 103, 20);

    // Set style of scr->Humidity
    lv_obj_set_style_text_align(scr->Humidity, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->Humidity, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->FanSpeed
    scr->FanSpeed = lv_label_create(scr->arc_container);
    lv_label_set_text(scr->FanSpeed, "Fan Speed\n");
    lv_label_set_long_mode(scr->FanSpeed, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->FanSpeed, 36, 60);
    lv_obj_set_size(scr->FanSpeed, 100, 32);

    // Set style of scr->FanSpeed
    lv_obj_set_style_text_font(scr->FanSpeed, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->arc_container);
    lv_label_set_text(scr->label_7, "50%");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 50, 85);
    lv_obj_set_size(scr->label_7, 60, 18);

    // Set style of scr->label_7
    lv_obj_set_style_text_align(scr->label_7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->arc_container);
    lv_label_set_text(scr->label_8, "30%\n");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 230, 85);
    lv_obj_set_size(scr->label_8, 60, 18);

    // Set style of scr->label_8
    lv_obj_set_style_text_align(scr->label_8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->hot_image
    scr->hot_image = lv_img_create(scr->obj);
    lv_img_set_src(scr->hot_image, LVGL_IMAGE_PATH(hot_40x40.png));
    lv_img_set_pivot(scr->hot_image, 50, 50);
    lv_img_set_offset_x(scr->hot_image, 0);
    lv_img_set_offset_y(scr->hot_image, 0);
    lv_img_set_angle(scr->hot_image, 0);
    lv_obj_set_pos(scr->hot_image, 140, 340);

    // Set style of scr->hot_image
    lv_obj_set_style_img_opa(scr->hot_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(scr->hot_image, lv_color_hex(0xff5d00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(scr->hot_image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->Chart_title
    scr->Chart_title = lv_label_create(scr->obj);
    lv_label_set_text(scr->Chart_title, "Temperature Record");
    lv_label_set_long_mode(scr->Chart_title, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->Chart_title, 50, 480);
    lv_obj_set_size(scr->Chart_title, 300, 30);

    // Set style of scr->Chart_title
    lv_obj_set_style_text_align(scr->Chart_title, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->Chart_title, fs_droidsansfallback_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chart_title
    scr->chart_title = lv_label_create(scr->obj);
    lv_label_set_text(scr->chart_title, "Other Parameters");
    lv_label_set_long_mode(scr->chart_title, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->chart_title, 50, 680);
    lv_obj_set_size(scr->chart_title, 300, 32);

    // Set style of scr->chart_title
    lv_obj_set_style_text_align(scr->chart_title, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->chart_title, fs_droidsansfallback_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_cont
    scr->temp_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->temp_cont, 90, 190);
    lv_obj_set_size(scr->temp_cont, 220, 220);
    lv_obj_set_scrollbar_mode(scr->temp_cont, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->temp_cont
    lv_obj_set_style_pad_right(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->temp_cont, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(scr->temp_cont, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->temp_cont, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->temp_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->temp_cont, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 50, 150);
    lv_obj_set_size(scr->container_2, 300, 300);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_2
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(scr->container_2, 115, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(scr->container_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(scr->container_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0xaa0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(scr->container_2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->container_2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}


