/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_droidsansfallback_22;
lv_font_t *fs_droidsansfallback_70;
lv_font_t *fs_droidsansfallback_20;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_droidsansfallback_22 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 22);
    fs_droidsansfallback_70 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 70);
    fs_droidsansfallback_20 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 20);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_droidsansfallback_22) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_22");
    	return;
    }
    if (!fs_droidsansfallback_70) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_70");
    	return;
    }
    if (!fs_droidsansfallback_20) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_20");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    screen_create(&ui_manager);
    lv_scr_load(screen_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
