/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *logo;
    lv_obj_t *temp_arc;
    lv_obj_t *temp_label;
    lv_obj_t *cold_hot;
    lv_obj_t *temp_uint;
    lv_obj_t *temp_status;
    lv_obj_t *temp_chart;
    lv_obj_t *arc_container;
    lv_obj_t *fan_arc;
    lv_obj_t *humidity_arc;
    lv_obj_t *Humidity;
    lv_obj_t *FanSpeed;
    lv_obj_t *label_7;
    lv_obj_t *label_8;
    lv_obj_t *hot_image;
    lv_obj_t *Chart_title;
    lv_obj_t *chart_title;
    lv_obj_t *temp_cont;
    lv_obj_t *container_2;
} screen_t;


typedef struct {
    bool auto_del;
    screen_t screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}


void screen_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_droidsansfallback_70;
extern lv_font_t *fs_droidsansfallback_20;
extern lv_font_t *fs_droidsansfallback_22;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
