/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) blind_screen_custom_load_start(void) {
}
void __attribute__((weak)) blind_screen_custom_unloaded(void) {
}

static void blind_screen_unloaded (lv_event_t *e) {
    blind_screen_custom_unloaded();
}

static void blind_screen_load_start (lv_event_t *e) {
    blind_screen_custom_load_start();
}

void __attribute__((weak)) blind_screen_slider_power_custom_value_changed(void) {
}

static void blind_screen_slider_power_value_changed (lv_event_t *e) {
    blind_screen_slider_power_custom_value_changed();
}

void __attribute__((weak)) blind_screen_button_open_custom_clicked(void) {
}

static void blind_screen_button_open_clicked (lv_event_t *e) {
    blind_screen_button_open_custom_clicked();
}

void __attribute__((weak)) blind_screen_button_close_custom_clicked(void) {
}

static void blind_screen_button_close_clicked (lv_event_t *e) {
    blind_screen_button_close_custom_clicked();
}


void blind_screen_create(ui_manager_t *ui)
{
    blind_screen_t *scr = blind_screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, blind_screen_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb(scr->obj, blind_screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->image_blind
    scr->image_blind = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_blind, LVGL_IMAGE_PATH(UI/blind/blind.png));
    lv_img_set_pivot(scr->image_blind, 50, 50);
    lv_img_set_offset_x(scr->image_blind, 0);
    lv_img_set_offset_y(scr->image_blind, 0);
    lv_img_set_angle(scr->image_blind, 0);
    lv_obj_set_pos(scr->image_blind, 16, 28);

    // Init scr->slider_power
    scr->slider_power = lv_slider_create(scr->obj);
    lv_slider_set_mode(scr->slider_power, LV_SLIDER_MODE_NORMAL);
    lv_slider_set_range(scr->slider_power, 0, 74);
    lv_slider_set_value(scr->slider_power, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_power, 52, 353);
    lv_obj_set_size(scr->slider_power, 376, 60);

    // Set style of scr->slider_power
    lv_obj_set_style_bg_color(scr->slider_power, lv_color_hex(0x9c99f2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_power, lv_color_hex(0x9c99f2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_power, lv_color_hex(0x9c99f2), LV_PART_KNOB | LV_STATE_DEFAULT);

    // Set event handler of scr->slider_power
    lv_obj_add_event_cb(scr->slider_power, blind_screen_slider_power_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->button_open
    scr->button_open = lv_btn_create(scr->obj);
    lv_obj_t *button_open_label = lv_label_create(scr->button_open);
    lv_label_set_text(button_open_label, "open");
    lv_obj_align(button_open_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_open, 344, 28);
    lv_obj_set_size(scr->button_open, 101, 102);

    // Set style of scr->button_open
    lv_obj_set_style_bg_img_src(scr->button_open, LVGL_IMAGE_PATH(UI/blind/bg1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_open, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_open, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_open, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_open
    lv_obj_add_event_cb(scr->button_open, blind_screen_button_open_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->button_close
    scr->button_close = lv_btn_create(scr->obj);
    lv_obj_t *button_close_label = lv_label_create(scr->button_close);
    lv_label_set_text(button_close_label, "close");
    lv_obj_align(button_close_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_close, 344, 197);
    lv_obj_set_size(scr->button_close, 101, 102);

    // Set style of scr->button_close
    lv_obj_set_style_bg_img_src(scr->button_close, LVGL_IMAGE_PATH(UI/blind/bg2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->button_close, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_close, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_close, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_close
    lv_obj_add_event_cb(scr->button_close, blind_screen_button_close_clicked, LV_EVENT_CLICKED, NULL);


}


