/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) light_screen_custom_load_start(void) {
}

static void light_screen_load_start (lv_event_t *e) {
    light_screen_custom_load_start();
}

void __attribute__((weak)) light_screen_image_blue_custom_clicked(void) {
}

static void light_screen_image_blue_clicked (lv_event_t *e) {
    light_screen_image_blue_custom_clicked();
}

void __attribute__((weak)) light_screen_image_green_custom_clicked(void) {
}

static void light_screen_image_greeen_clicked (lv_event_t *e) {
    light_screen_image_green_custom_clicked();
}

void __attribute__((weak)) light_screen_image_pure_custom_clicked(void) {
}

static void light_screen_image_pure_clicked (lv_event_t *e) {
    light_screen_image_pure_custom_clicked();
}

void __attribute__((weak)) light_screen_image_red_custom_clicked(void) {
}

static void light_screen_image_red_clicked (lv_event_t *e) {
    light_screen_image_red_custom_clicked();
}

void __attribute__((weak)) light_screen_image_yellow_custom_clicked(void) {
}

static void light_screen_image_yellow_clicked (lv_event_t *e) {
    light_screen_image_yellow_custom_clicked();
}

void __attribute__((weak)) light_screen_slider_brightness_custom_value_changed(void) {
}

static void light_screen_slider_brightness_value_changed (lv_event_t *e) {
    light_screen_slider_brightness_custom_value_changed();
}


void light_screen_create(ui_manager_t *ui)
{
    light_screen_t *scr = light_screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, light_screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->container_clor
    scr->container_clor = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_clor, 0, 285);
    lv_obj_set_size(scr->container_clor, 480, 195);
    lv_obj_set_scrollbar_mode(scr->container_clor, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_clor
    lv_obj_set_style_bg_color(scr->container_clor, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_clor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_clor
    scr->image_clor = lv_img_create(scr->container_clor);
    lv_img_set_src(scr->image_clor, LVGL_IMAGE_PATH(UI/light/bg_pink.png));
    lv_img_set_pivot(scr->image_clor, 50, 50);
    lv_img_set_offset_x(scr->image_clor, 0);
    lv_img_set_offset_y(scr->image_clor, 0);
    lv_img_set_angle(scr->image_clor, 0);
    lv_obj_set_pos(scr->image_clor, 0, 0);

    // Init scr->image_blue
    scr->image_blue = lv_img_create(scr->container_clor);
    lv_img_set_src(scr->image_blue, LVGL_IMAGE_PATH(light_change/blue.png));
    lv_img_set_pivot(scr->image_blue, 50, 50);
    lv_img_set_offset_x(scr->image_blue, 0);
    lv_img_set_offset_y(scr->image_blue, 0);
    lv_img_set_angle(scr->image_blue, 0);
    lv_obj_set_pos(scr->image_blue, 29, 104);
    lv_obj_add_flag(scr->image_blue, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_blue
    lv_obj_add_event_cb(scr->image_blue, light_screen_image_blue_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_greeen
    scr->image_greeen = lv_img_create(scr->container_clor);
    lv_img_set_src(scr->image_greeen, LVGL_IMAGE_PATH(light_change/green.png));
    lv_img_set_pivot(scr->image_greeen, 50, 50);
    lv_img_set_offset_x(scr->image_greeen, 0);
    lv_img_set_offset_y(scr->image_greeen, 0);
    lv_img_set_angle(scr->image_greeen, 0);
    lv_obj_set_pos(scr->image_greeen, 123, 103);
    lv_obj_add_flag(scr->image_greeen, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_greeen
    lv_obj_add_event_cb(scr->image_greeen, light_screen_image_greeen_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_pure
    scr->image_pure = lv_img_create(scr->container_clor);
    lv_img_set_src(scr->image_pure, LVGL_IMAGE_PATH(light_change/pure.png));
    lv_img_set_pivot(scr->image_pure, 50, 50);
    lv_img_set_offset_x(scr->image_pure, 0);
    lv_img_set_offset_y(scr->image_pure, 0);
    lv_img_set_angle(scr->image_pure, 0);
    lv_obj_set_pos(scr->image_pure, 206, 103);
    lv_obj_add_flag(scr->image_pure, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_pure
    lv_obj_add_event_cb(scr->image_pure, light_screen_image_pure_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_red
    scr->image_red = lv_img_create(scr->container_clor);
    lv_img_set_src(scr->image_red, LVGL_IMAGE_PATH(light_change/red.png));
    lv_img_set_pivot(scr->image_red, 50, 50);
    lv_img_set_offset_x(scr->image_red, 0);
    lv_img_set_offset_y(scr->image_red, 0);
    lv_img_set_angle(scr->image_red, 0);
    lv_obj_set_pos(scr->image_red, 292, 103);
    lv_obj_add_flag(scr->image_red, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_red
    lv_obj_add_event_cb(scr->image_red, light_screen_image_red_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_yellow
    scr->image_yellow = lv_img_create(scr->container_clor);
    lv_img_set_src(scr->image_yellow, LVGL_IMAGE_PATH(light_change/yellow.png));
    lv_img_set_pivot(scr->image_yellow, 50, 50);
    lv_img_set_offset_x(scr->image_yellow, 0);
    lv_img_set_offset_y(scr->image_yellow, 0);
    lv_img_set_angle(scr->image_yellow, 0);
    lv_obj_set_pos(scr->image_yellow, 385, 103);
    lv_obj_add_flag(scr->image_yellow, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_yellow
    lv_obj_add_event_cb(scr->image_yellow, light_screen_image_yellow_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_brightness
    scr->container_brightness = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_brightness, 401, 9);
    lv_obj_set_size(scr->container_brightness, 50, 236);
    lv_obj_set_scrollbar_mode(scr->container_brightness, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_brightness
    lv_obj_set_style_bg_color(scr->container_brightness, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_brightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->slider_brightness
    scr->slider_brightness = lv_slider_create(scr->container_brightness);
    lv_slider_set_mode(scr->slider_brightness, LV_SLIDER_MODE_NORMAL);
    lv_slider_set_range(scr->slider_brightness, 0, 100);
    lv_slider_set_value(scr->slider_brightness, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_brightness, 16, 29);
    lv_obj_set_size(scr->slider_brightness, 20, 170);

    // Set style of scr->slider_brightness
    lv_obj_set_style_bg_color(scr->slider_brightness, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_brightness, lv_color_hex(0xf38ea4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->slider_brightness, lv_color_hex(0xf38ea4), LV_PART_KNOB | LV_STATE_DEFAULT);

    // Set event handler of scr->slider_brightness
    lv_obj_add_event_cb(scr->slider_brightness, light_screen_slider_brightness_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->image_light
    scr->image_light = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_light, LVGL_IMAGE_PATH(UI/light/light.png));
    lv_img_set_pivot(scr->image_light, 50, 50);
    lv_img_set_offset_x(scr->image_light, 0);
    lv_img_set_offset_y(scr->image_light, 0);
    lv_img_set_angle(scr->image_light, 0);
    lv_obj_set_pos(scr->image_light, 94, 6);


}


