/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) main_screen_custom_load_start(void) {
}

static void main_screen_load_start (lv_event_t *e) {
    main_screen_custom_load_start();
}

static void main_screen_image_light_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create light_screen
        light_screen_create(&ui_manager);
        // load light_screen
        lv_scr_load_anim(light_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, ui_manager.auto_del);
    }
}

static void main_screen_image_air_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create air_screen
        air_screen_create(&ui_manager);
        // load air_screen
        lv_scr_load_anim(air_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 350, 0, ui_manager.auto_del);
    }
}

static void main_screen_image_blind_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create blind_screen
        blind_screen_create(&ui_manager);
        // load blind_screen
        lv_scr_load_anim(blind_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void main_screen_image_scene_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create Scene_screen
        Scene_screen_create(&ui_manager);
        // load Scene_screen
        lv_scr_load_anim(Scene_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void main_screen_create(ui_manager_t *ui)
{
    main_screen_t *scr = main_screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, main_screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->container_light
    scr->container_light = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_light, 24, 256);
    lv_obj_set_size(scr->container_light, 201, 200);
    lv_obj_set_scrollbar_mode(scr->container_light, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_light
    lv_obj_set_style_bg_color(scr->container_light, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_light
    scr->image_light = lv_img_create(scr->container_light);
    lv_img_set_src(scr->image_light, LVGL_IMAGE_PATH(main_change/main_light.png));
    lv_img_set_pivot(scr->image_light, 50, 50);
    lv_img_set_offset_x(scr->image_light, 0);
    lv_img_set_offset_y(scr->image_light, 0);
    lv_img_set_angle(scr->image_light, 0);
    lv_obj_set_pos(scr->image_light, 0, 0);
    lv_obj_add_flag(scr->image_light, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_light
    lv_obj_add_event_cb(scr->image_light, main_screen_image_light_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_air
    scr->container_air = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_air, 256, 260);
    lv_obj_set_size(scr->container_air, 200, 200);
    lv_obj_set_scrollbar_mode(scr->container_air, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_air
    lv_obj_set_style_bg_color(scr->container_air, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_air, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_air
    scr->image_air = lv_img_create(scr->container_air);
    lv_img_set_src(scr->image_air, LVGL_IMAGE_PATH(main_change/main_air.png));
    lv_img_set_pivot(scr->image_air, 50, 50);
    lv_img_set_offset_x(scr->image_air, 0);
    lv_img_set_offset_y(scr->image_air, 0);
    lv_img_set_angle(scr->image_air, 0);
    lv_obj_set_pos(scr->image_air, 0, 0);
    lv_obj_add_flag(scr->image_air, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_air
    lv_obj_add_event_cb(scr->image_air, main_screen_image_air_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_blind
    scr->container_blind = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_blind, 302, 58);
    lv_obj_set_size(scr->container_blind, 154, 155);
    lv_obj_set_scrollbar_mode(scr->container_blind, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_blind
    lv_obj_set_style_bg_color(scr->container_blind, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_blind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_blind
    scr->image_blind = lv_img_create(scr->container_blind);
    lv_img_set_src(scr->image_blind, LVGL_IMAGE_PATH(main_change/main_blind.png));
    lv_img_set_pivot(scr->image_blind, 50, 50);
    lv_img_set_offset_x(scr->image_blind, 0);
    lv_img_set_offset_y(scr->image_blind, 0);
    lv_img_set_angle(scr->image_blind, 0);
    lv_obj_set_pos(scr->image_blind, 0, 0);
    lv_obj_add_flag(scr->image_blind, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_blind
    lv_obj_add_event_cb(scr->image_blind, main_screen_image_blind_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_scene
    scr->container_scene = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_scene, 12, 47);
    lv_obj_set_size(scr->container_scene, 265, 175);
    lv_obj_set_scrollbar_mode(scr->container_scene, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_scene
    lv_obj_set_style_bg_color(scr->container_scene, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_scene, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_scene
    scr->image_scene = lv_img_create(scr->container_scene);
    lv_img_set_src(scr->image_scene, LVGL_IMAGE_PATH(main_change/main_scene.png));
    lv_img_set_pivot(scr->image_scene, 50, 50);
    lv_img_set_offset_x(scr->image_scene, 0);
    lv_img_set_offset_y(scr->image_scene, 0);
    lv_img_set_angle(scr->image_scene, 0);
    lv_obj_set_pos(scr->image_scene, 0, 0);
    lv_obj_add_flag(scr->image_scene, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_scene
    lv_obj_add_event_cb(scr->image_scene, main_screen_image_scene_clicked, LV_EVENT_CLICKED, NULL);


}


