/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) Scene_screen_custom_load_start(void) {
}
void __attribute__((weak)) Scene_screen_custom_unloaded(void) {
}

static void Scene_screen_unloaded (lv_event_t *e) {
    Scene_screen_custom_unloaded();
}

static void Scene_screen_load_start (lv_event_t *e) {
    Scene_screen_custom_load_start();
}

void __attribute__((weak)) Scene_screen_image_screen1_custom_clicked(void) {
}

static void Scene_screen_image_screen1_clicked (lv_event_t *e) {
    Scene_screen_image_screen1_custom_clicked();
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen_gif
        screen_gif_create(&ui_manager);
        // load screen_gif
        lv_scr_load_anim(screen_gif_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) Scene_screen_image_screen2_custom_clicked(void) {
}

static void Scene_screen_image_screen2_clicked (lv_event_t *e) {
    Scene_screen_image_screen2_custom_clicked();
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen_gif
        screen_gif_create(&ui_manager);
        // load screen_gif
        lv_scr_load_anim(screen_gif_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void Scene_screen_image_screen3_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create wallpaper_screen
        wallpaper_screen_create(&ui_manager);
        // load wallpaper_screen
        lv_scr_load_anim(wallpaper_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) Scene_screen_image_screen4_custom_clicked(void) {
}

static void Scene_screen_image_screen4_clicked (lv_event_t *e) {
    Scene_screen_image_screen4_custom_clicked();
}

void __attribute__((weak)) Scene_screen_image_screen5_custom_clicked(void) {
}

static void Scene_screen_image_screen5_clicked (lv_event_t *e) {
    Scene_screen_image_screen5_custom_clicked();
}


void Scene_screen_create(ui_manager_t *ui)
{
    Scene_screen_t *scr = Scene_screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, Scene_screen_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb(scr->obj, Scene_screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->container_board
    scr->container_board = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_board, 26, 11);
    lv_obj_set_size(scr->container_board, 428, 160);
    lv_obj_set_scrollbar_mode(scr->container_board, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_board
    lv_obj_set_style_bg_color(scr->container_board, lv_color_hex(0xffe88b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_board, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_board, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_board, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_board, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_board, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_board, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_temp2
    scr->label_temp2 = lv_label_create(scr->container_board);
    lv_label_set_text(scr->label_temp2, "22°");
    lv_label_set_long_mode(scr->label_temp2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_temp2, 43, 13);
    lv_obj_set_size(scr->label_temp2, 68, 36);

    // Set style of scr->label_temp2
    lv_obj_set_style_text_font(scr->label_temp2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_IT
    scr->label_IT = lv_label_create(scr->container_board);
    lv_label_set_text(scr->label_IT, "Indoor temperature");
    lv_label_set_long_mode(scr->label_IT, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_IT, 87, 13);
    lv_obj_set_size(scr->label_IT, 218, 16);

    // Set style of scr->label_IT
    lv_obj_set_style_text_font(scr->label_IT, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_temp1
    scr->label_temp1 = lv_label_create(scr->container_board);
    lv_label_set_text(scr->label_temp1, "22°");
    lv_label_set_long_mode(scr->label_temp1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_temp1, 29, 106);
    lv_obj_set_size(scr->label_temp1, 28, 18);

    // Set style of scr->label_temp1
    lv_obj_set_style_text_font(scr->label_temp1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_room
    scr->label_room = lv_label_create(scr->container_board);
    lv_label_set_text(scr->label_room, "Room temperature");
    lv_label_set_long_mode(scr->label_room, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_room, 27, 124);
    lv_obj_set_size(scr->label_room, 132, 17);

    // Set style of scr->label_room
    lv_obj_set_style_text_font(scr->label_room, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_percent
    scr->label_percent = lv_label_create(scr->container_board);
    lv_label_set_text(scr->label_percent, "65%");
    lv_label_set_long_mode(scr->label_percent, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_percent, 292, 106);
    lv_obj_set_size(scr->label_percent, 100, 18);

    // Set style of scr->label_percent
    lv_obj_set_style_text_font(scr->label_percent, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_indoor
    scr->label_indoor = lv_label_create(scr->container_board);
    lv_label_set_text(scr->label_indoor, "Indoor humidity");
    lv_label_set_long_mode(scr->label_indoor, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_indoor, 289, 124);
    lv_obj_set_size(scr->label_indoor, 115, 17);

    // Set style of scr->label_indoor
    lv_obj_set_style_text_font(scr->label_indoor, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_screen1
    scr->image_screen1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_screen1, LVGL_IMAGE_PATH(scene_icon/1_1.png));
    lv_img_set_pivot(scr->image_screen1, 50, 50);
    lv_img_set_offset_x(scr->image_screen1, 0);
    lv_img_set_offset_y(scr->image_screen1, 0);
    lv_img_set_angle(scr->image_screen1, 0);
    lv_obj_set_pos(scr->image_screen1, 41, 199);
    lv_obj_add_flag(scr->image_screen1, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_screen1
    lv_obj_add_event_cb(scr->image_screen1, Scene_screen_image_screen1_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_screen2
    scr->image_screen2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_screen2, LVGL_IMAGE_PATH(scene_icon/2_1.png));
    lv_img_set_pivot(scr->image_screen2, 50, 50);
    lv_img_set_offset_x(scr->image_screen2, 0);
    lv_img_set_offset_y(scr->image_screen2, 0);
    lv_img_set_angle(scr->image_screen2, 0);
    lv_obj_set_pos(scr->image_screen2, 192, 233);
    lv_obj_add_flag(scr->image_screen2, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_screen2
    lv_obj_add_event_cb(scr->image_screen2, Scene_screen_image_screen2_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_screen3
    scr->image_screen3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_screen3, LVGL_IMAGE_PATH(scene_icon/3_1.png));
    lv_img_set_pivot(scr->image_screen3, 50, 50);
    lv_img_set_offset_x(scr->image_screen3, 0);
    lv_img_set_offset_y(scr->image_screen3, 0);
    lv_img_set_angle(scr->image_screen3, 0);
    lv_obj_set_pos(scr->image_screen3, 336, 202);
    lv_obj_add_flag(scr->image_screen3, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_screen3
    lv_obj_add_event_cb(scr->image_screen3, Scene_screen_image_screen3_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_screen4
    scr->image_screen4 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_screen4, LVGL_IMAGE_PATH(scene_icon/4_1.png));
    lv_img_set_pivot(scr->image_screen4, 50, 50);
    lv_img_set_offset_x(scr->image_screen4, 0);
    lv_img_set_offset_y(scr->image_screen4, 0);
    lv_img_set_angle(scr->image_screen4, 0);
    lv_obj_set_pos(scr->image_screen4, 111, 348);
    lv_obj_add_flag(scr->image_screen4, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_screen4
    lv_obj_add_event_cb(scr->image_screen4, Scene_screen_image_screen4_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_screen5
    scr->image_screen5 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_screen5, LVGL_IMAGE_PATH(scene_icon/5_1.png));
    lv_img_set_pivot(scr->image_screen5, 50, 50);
    lv_img_set_offset_x(scr->image_screen5, 0);
    lv_img_set_offset_y(scr->image_screen5, 0);
    lv_img_set_angle(scr->image_screen5, 0);
    lv_obj_set_pos(scr->image_screen5, 328, 355);
    lv_obj_add_flag(scr->image_screen5, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_screen5
    lv_obj_add_event_cb(scr->image_screen5, Scene_screen_image_screen5_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_screen1
    scr->label_screen1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_screen1, "场景1");
    lv_label_set_long_mode(scr->label_screen1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_screen1, 89, 270);
    lv_obj_set_size(scr->label_screen1, 59, 32);

    // Set style of scr->label_screen1
    lv_obj_set_style_text_font(scr->label_screen1, fs_a_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_screen2
    scr->label_screen2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_screen2, "场景2");
    lv_label_set_long_mode(scr->label_screen2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_screen2, 224, 269);
    lv_obj_set_size(scr->label_screen2, 50, 32);

    // Set style of scr->label_screen2
    lv_obj_set_style_text_font(scr->label_screen2, fs_a_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_screen3
    scr->label_screen3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_screen3, "场景3");
    lv_label_set_long_mode(scr->label_screen3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_screen3, 365, 277);
    lv_obj_set_size(scr->label_screen3, 53, 19);

    // Set style of scr->label_screen3
    lv_obj_set_style_text_font(scr->label_screen3, fs_a_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_screen4
    scr->label_screen4 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_screen4, "场景4");
    lv_label_set_long_mode(scr->label_screen4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_screen4, 185, 377);
    lv_obj_set_size(scr->label_screen4, 44, 20);

    // Set style of scr->label_screen4
    lv_obj_set_style_text_font(scr->label_screen4, fs_a_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_screen5
    scr->label_screen5 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_screen5, "场景5");
    lv_label_set_long_mode(scr->label_screen5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_screen5, 341, 379);
    lv_obj_set_size(scr->label_screen5, 44, 20);

    // Set style of scr->label_screen5
    lv_obj_set_style_text_font(scr->label_screen5, fs_a_16, LV_PART_MAIN | LV_STATE_DEFAULT);


}


