/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) screen_gif_custom_load_start(void) {
}
void __attribute__((weak)) screen_gif_custom_unloaded(void) {
}

static void screen_gif_unloaded (lv_event_t *e) {
    screen_gif_custom_unloaded();
}

static void screen_gif_load_start (lv_event_t *e) {
    screen_gif_custom_load_start();
}


void screen_gif_create(ui_manager_t *ui)
{
    screen_gif_t *scr = screen_gif_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_gif_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb(scr->obj, screen_gif_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);


}


