/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) startup_screen_custom_load_start(void) {
}
void __attribute__((weak)) startup_screen_custom_unloaded(void) {
}

static void startup_screen_unloaded (lv_event_t *e) {
    startup_screen_custom_unloaded();
}

static void startup_screen_load_start (lv_event_t *e) {
    startup_screen_custom_load_start();
}

static void startup_screen_image_switch_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create main_screen
        main_screen_create(&ui_manager);
        // load main_screen
        lv_scr_load_anim(main_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void startup_screen_create(ui_manager_t *ui)
{
    startup_screen_t *scr = startup_screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, startup_screen_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb(scr->obj, startup_screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(UI/start/bg.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 0, 0);

    // Init scr->image_switch
    scr->image_switch = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_switch, LVGL_IMAGE_PATH(UI/start/go.png));
    lv_img_set_pivot(scr->image_switch, 50, 50);
    lv_img_set_offset_x(scr->image_switch, 0);
    lv_img_set_offset_y(scr->image_switch, 0);
    lv_img_set_angle(scr->image_switch, 0);
    lv_obj_set_pos(scr->image_switch, 66, 367);
    lv_obj_add_flag(scr->image_switch, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_switch
    lv_obj_add_event_cb(scr->image_switch, startup_screen_image_switch_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_time
    scr->label_time = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_time, "10:15");
    lv_label_set_long_mode(scr->label_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_time, 35, 42);
    lv_obj_set_size(scr->label_time, 186, 80);

    // Set style of scr->label_time
    lv_obj_set_style_text_font(scr->label_time, fs_montserratmedium_70, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_date
    scr->label_date = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_date, "9月10日");
    lv_label_set_long_mode(scr->label_date, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_date, 76, 143);
    lv_obj_set_size(scr->label_date, 100, 32);

    // Set style of scr->label_date
    lv_obj_set_style_text_font(scr->label_date, fs_a_23, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_week
    scr->label_week = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_week, "星期三");
    lv_label_set_long_mode(scr->label_week, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_week, 76, 192);
    lv_obj_set_size(scr->label_week, 100, 32);

    // Set style of scr->label_week
    lv_obj_set_style_text_font(scr->label_week, fs_a_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->player_pinwheel
    scr->player_pinwheel = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->player_pinwheel, LVGL_VIDEO_PATH(fengche2.png));
    lv_aic_player_set_auto_restart(scr->player_pinwheel, true);
    lv_aic_player_set_cmd(scr->player_pinwheel, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->player_pinwheel, 326, 108);
    lv_obj_set_size(scr->player_pinwheel, 128, 128);

    // Init scr->player_2
    scr->player_2 = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->player_2, LVGL_VIDEO_PATH(gif_com_1.png));
    lv_aic_player_set_auto_restart(scr->player_2, true);
    lv_aic_player_set_cmd(scr->player_2, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->player_2, 357, -15);
    lv_obj_set_size(scr->player_2, 120, 120);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->obj);
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, -633, 165);


}


