/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_montserratmedium_70;
lv_font_t *fs_a_23;
lv_font_t *fs_a_16;
lv_font_t *fs_a_34;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_montserratmedium_70 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 70);
    fs_a_23 = ui_font_init(LVGL_FONT_PATH(a.ttf), 23);
    fs_a_16 = ui_font_init(LVGL_FONT_PATH(a.ttf), 16);
    fs_a_34 = ui_font_init(LVGL_FONT_PATH(a.ttf), 34);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_montserratmedium_70) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_70");
    	return;
    }
    if (!fs_a_23) {
    	LV_LOG_ERROR("Failed to init fs_a_23");
    	return;
    }
    if (!fs_a_16) {
    	LV_LOG_ERROR("Failed to init fs_a_16");
    	return;
    }
    if (!fs_a_34) {
    	LV_LOG_ERROR("Failed to init fs_a_34");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    startup_screen_create(&ui_manager);
    lv_scr_load(startup_screen_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
