/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_1;
    lv_obj_t *image_switch;
    lv_obj_t *label_time;
    lv_obj_t *label_date;
    lv_obj_t *label_week;
    lv_obj_t *player_pinwheel;
    lv_obj_t *player_2;
    lv_obj_t *image_2;
} startup_screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_light;
    lv_obj_t *image_light;
    lv_obj_t *container_air;
    lv_obj_t *image_air;
    lv_obj_t *container_blind;
    lv_obj_t *image_blind;
    lv_obj_t *container_scene;
    lv_obj_t *image_scene;
} main_screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_ac;
    lv_obj_t *image_remote;
    lv_obj_t *image_cold;
    lv_obj_t *button_power;
    lv_obj_t *button_wind;
    lv_obj_t *button_cold;
    lv_obj_t *button_up;
    lv_obj_t *button_down;
    lv_obj_t *roller_temp;
    lv_obj_t *image_wind;
} air_screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_clor;
    lv_obj_t *image_clor;
    lv_obj_t *image_blue;
    lv_obj_t *image_greeen;
    lv_obj_t *image_pure;
    lv_obj_t *image_red;
    lv_obj_t *image_yellow;
    lv_obj_t *container_brightness;
    lv_obj_t *slider_brightness;
    lv_obj_t *image_light;
} light_screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_blind;
    lv_obj_t *slider_power;
    lv_obj_t *button_open;
    lv_obj_t *button_close;
} blind_screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_board;
    lv_obj_t *label_temp2;
    lv_obj_t *label_IT;
    lv_obj_t *label_temp1;
    lv_obj_t *label_room;
    lv_obj_t *label_percent;
    lv_obj_t *label_indoor;
    lv_obj_t *image_screen1;
    lv_obj_t *image_screen2;
    lv_obj_t *image_screen3;
    lv_obj_t *image_screen4;
    lv_obj_t *image_screen5;
    lv_obj_t *label_screen1;
    lv_obj_t *label_screen2;
    lv_obj_t *label_screen3;
    lv_obj_t *label_screen4;
    lv_obj_t *label_screen5;
} Scene_screen_t;

typedef struct {
    lv_obj_t *obj;
} screen_gif_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1;
    lv_obj_t *image_2;
    lv_obj_t *image_1;
    lv_obj_t *image_3;
    lv_obj_t *image_4;
    lv_obj_t *button_1;
} wallpaper_screen_t;


typedef struct {
    bool auto_del;
    startup_screen_t startup_screen;
    main_screen_t main_screen;
    air_screen_t air_screen;
    light_screen_t light_screen;
    blind_screen_t blind_screen;
    Scene_screen_t Scene_screen;
    screen_gif_t screen_gif;
    wallpaper_screen_t wallpaper_screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline startup_screen_t *startup_screen_get(ui_manager_t *ui)
{
    return &ui->startup_screen;
}

static inline main_screen_t *main_screen_get(ui_manager_t *ui)
{
    return &ui->main_screen;
}

static inline air_screen_t *air_screen_get(ui_manager_t *ui)
{
    return &ui->air_screen;
}

static inline light_screen_t *light_screen_get(ui_manager_t *ui)
{
    return &ui->light_screen;
}

static inline blind_screen_t *blind_screen_get(ui_manager_t *ui)
{
    return &ui->blind_screen;
}

static inline Scene_screen_t *Scene_screen_get(ui_manager_t *ui)
{
    return &ui->Scene_screen;
}

static inline screen_gif_t *screen_gif_get(ui_manager_t *ui)
{
    return &ui->screen_gif;
}

static inline wallpaper_screen_t *wallpaper_screen_get(ui_manager_t *ui)
{
    return &ui->wallpaper_screen;
}


void startup_screen_create(ui_manager_t *ui);
void main_screen_create(ui_manager_t *ui);
void air_screen_create(ui_manager_t *ui);
void light_screen_create(ui_manager_t *ui);
void blind_screen_create(ui_manager_t *ui);
void Scene_screen_create(ui_manager_t *ui);
void screen_gif_create(ui_manager_t *ui);
void wallpaper_screen_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_montserratmedium_70;
extern lv_font_t *fs_a_23;
extern lv_font_t *fs_a_16;
extern lv_font_t *fs_a_34;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
