/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) wallpaper_screen_custom_load_start(void) {
}
void __attribute__((weak)) wallpaper_screen_custom_unloaded(void) {
}

static void wallpaper_screen_unloaded (lv_event_t *e) {
    wallpaper_screen_custom_unloaded();
}

static void wallpaper_screen_load_start (lv_event_t *e) {
    wallpaper_screen_custom_load_start();
}

static void wallpaper_screen_button_1_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create Scene_screen
        Scene_screen_create(&ui_manager);
        // load Scene_screen
        lv_scr_load_anim(Scene_screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void wallpaper_screen_create(ui_manager_t *ui)
{
    wallpaper_screen_t *scr = wallpaper_screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, wallpaper_screen_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);
    lv_obj_add_event_cb(scr->obj, wallpaper_screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_1, 0, 145);
    lv_obj_set_size(scr->container_1, 480, 200);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_1
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(UI/start/bg_200x200.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 200, 0);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(UI/start/bg_2_200x200.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 0, 0);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(UI/start/bg_200x200.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 400, 0);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(UI/start/bg_2_200x200.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_offset_x(scr->image_4, 0);
    lv_img_set_offset_y(scr->image_4, 0);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_pos(scr->image_4, 600, 0);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "<");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 393, 429);
    lv_obj_set_size(scr->button_1, 87, 43);

    // Set style of scr->button_1
    lv_obj_set_style_bg_opa(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, wallpaper_screen_button_1_clicked, LV_EVENT_CLICKED, NULL);


}


