/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void scrCharge_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrMain
        scrMain_create(&ui_manager);
        // load scrMain
        lv_scr_load_anim(scrMain_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void scrCharge_create(ui_manager_t *ui)
{
    scrCharge_t *scr = scrCharge_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x26190f), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->back
    scr->back = lv_img_create(scr->obj);
    lv_img_set_src(scr->back, LVGL_IMAGE_PATH(back1_100x100.png));
    lv_img_set_pivot(scr->back, 50, 50);
    lv_img_set_offset_x(scr->back, 0);
    lv_img_set_offset_y(scr->back, 0);
    lv_img_set_angle(scr->back, 0);
    lv_obj_set_pos(scr->back, 50, 50);
    lv_obj_add_flag(scr->back, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->back
    lv_obj_set_style_img_recolor(scr->back, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->back
    lv_obj_add_event_cb(scr->back, scrCharge_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_14
    scr->container_14 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_14, 50, 550);
    lv_obj_set_size(scr->container_14, 500, 600);
    lv_obj_set_scrollbar_mode(scr->container_14, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_14
    lv_obj_set_style_radius(scr->container_14, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_14, lv_color_hex(0x572519), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_11
    scr->label_11 = lv_label_create(scr->container_14);
    lv_label_set_text(scr->label_11, "Gas Savings");
    lv_label_set_long_mode(scr->label_11, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_11, 30, 30);
    lv_obj_set_size(scr->label_11, 400, 60);

    // Set style of scr->label_11
    lv_obj_set_style_text_color(scr->label_11, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_11, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->container_14);
    lv_label_set_text(scr->label_12, "Estimated values");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 30, 100);
    lv_obj_set_size(scr->label_12, 400, 40);

    // Set style of scr->label_12
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0x886b64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_12, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_money
    scr->label_money = lv_label_create(scr->container_14);
    lv_label_set_text(scr->label_money, "$250");
    lv_label_set_long_mode(scr->label_money, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_money, 30, 170);
    lv_obj_set_size(scr->label_money, 400, 100);

    // Set style of scr->label_money
    lv_obj_set_style_text_color(scr->label_money, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_money, fs_montserratmedium_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_16
    scr->label_16 = lv_label_create(scr->container_14);
    lv_label_set_text(scr->label_16, "Saved");
    lv_label_set_long_mode(scr->label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_16, 30, 280);
    lv_obj_set_size(scr->label_16, 200, 40);

    // Set style of scr->label_16
    lv_obj_set_style_text_color(scr->label_16, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_16, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_15
    scr->container_15 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_15, 600, 550);
    lv_obj_set_size(scr->container_15, 500, 600);
    lv_obj_set_scrollbar_mode(scr->container_15, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_15
    lv_obj_set_style_radius(scr->container_15, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_15, lv_color_hex(0x6a443a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->container_15);
    lv_label_set_text(scr->label_13, "Last 14 days");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 30, 30);
    lv_obj_set_size(scr->label_13, 400, 60);

    // Set style of scr->label_13
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_13, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chart_1
    scr->chart_1 = lv_chart_create(scr->container_15);
    lv_chart_set_type(scr->chart_1, LV_CHART_TYPE_BAR);
    lv_chart_set_range(scr->chart_1, LV_CHART_AXIS_PRIMARY_Y, 0, 100);
    lv_chart_set_point_count(scr->chart_1, 10);

    lv_chart_series_t *chart_1_series_0 = lv_chart_add_series(scr->chart_1, lv_color_hex(0xffffff), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 46);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 28);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 75);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 91);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 45);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 57);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 76);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 42);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 31);
    lv_chart_set_next_value(scr->chart_1, chart_1_series_0, 95);

    lv_obj_set_pos(scr->chart_1, 30, 150);
    lv_obj_set_size(scr->chart_1, 370, 220);

    // Set style of scr->chart_1
    lv_obj_set_style_line_width(scr->chart_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->chart_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->chart_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_10, "EV Charging");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 50, 200);
    lv_obj_set_size(scr->label_10, 580, 100);

    // Set style of scr->label_10
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_10, fs_montserratmedium_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_charge
    scr->cont_charge = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_charge, 1150, 250);
    lv_obj_set_size(scr->cont_charge, 720, 900);
    lv_obj_set_scrollbar_mode(scr->cont_charge, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_charge
    lv_obj_set_style_radius(scr->cont_charge, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_charge, lv_color_hex(0x9364f0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_charge
    scr->arc_charge = lv_arc_create(scr->cont_charge);
    lv_arc_set_mode(scr->arc_charge, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_charge, 0, 100);
    lv_arc_set_value(scr->arc_charge, 20);
    lv_arc_set_bg_angles(scr->arc_charge, 0, 360);
    lv_arc_set_angles(scr->arc_charge, 0, 72);
    lv_arc_set_rotation(scr->arc_charge, 270);
    lv_arc_set_change_rate(scr->arc_charge, 720);
    lv_obj_set_pos(scr->arc_charge, 160, 150);
    lv_obj_set_size(scr->arc_charge, 400, 400);

    // Set style of scr->arc_charge
    lv_obj_set_style_arc_opa(scr->arc_charge, 111, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_charge, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_percent
    scr->label_percent = lv_label_create(scr->cont_charge);
    lv_label_set_text(scr->label_percent, "0%");
    lv_label_set_long_mode(scr->label_percent, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_percent, 210, 250);
    lv_obj_set_size(scr->label_percent, 300, 110);

    // Set style of scr->label_percent
    lv_obj_set_style_text_align(scr->label_percent, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_percent, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_percent, fs_montserratmedium_100, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->btn_charge
    scr->btn_charge = lv_btn_create(scr->cont_charge);
    lv_obj_t *btn_charge_label = lv_label_create(scr->btn_charge);
    lv_label_set_text(btn_charge_label, "Start Charging");
    lv_obj_align(btn_charge_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_charge, 220, 375);
    lv_obj_set_size(scr->btn_charge, 280, 80);

    // Set style of scr->btn_charge
    lv_obj_set_style_radius(scr->btn_charge, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->btn_charge, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->btn_charge, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_charge, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_18
    scr->label_18 = lv_label_create(scr->cont_charge);
    lv_label_set_text(scr->label_18, "Charging");
    lv_label_set_long_mode(scr->label_18, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_18, 30, 30);
    lv_obj_set_size(scr->label_18, 400, 60);

    // Set style of scr->label_18
    lv_obj_set_style_text_color(scr->label_18, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_18, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_17
    scr->container_17 = lv_obj_create(scr->cont_charge);
    lv_obj_set_pos(scr->container_17, 30, 580);
    lv_obj_set_size(scr->container_17, 200, 280);
    lv_obj_set_scrollbar_mode(scr->container_17, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_17
    lv_obj_set_style_radius(scr->container_17, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_17, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_17, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_8
    scr->image_8 = lv_img_create(scr->container_17);
    lv_img_set_src(scr->image_8, LVGL_IMAGE_PATH(time_80x80.png));
    lv_img_set_pivot(scr->image_8, 50, 50);
    lv_img_set_offset_x(scr->image_8, 0);
    lv_img_set_offset_y(scr->image_8, 0);
    lv_img_set_angle(scr->image_8, 0);
    lv_obj_set_pos(scr->image_8, 20, 20);

    // Init scr->label_19
    scr->label_19 = lv_label_create(scr->container_17);
    lv_label_set_text(scr->label_19, "Time to full charge");
    lv_label_set_long_mode(scr->label_19, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_19, 20, 110);
    lv_obj_set_size(scr->label_19, 170, 80);

    // Set style of scr->label_19
    lv_obj_set_style_text_color(scr->label_19, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_19, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_time
    scr->label_time = lv_label_create(scr->container_17);
    lv_label_set_text(scr->label_time, "7.2");
    lv_label_set_long_mode(scr->label_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_time, 20, 200);
    lv_obj_set_size(scr->label_time, 100, 70);

    // Set style of scr->label_time
    lv_obj_set_style_text_color(scr->label_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_time, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_21
    scr->label_21 = lv_label_create(scr->container_17);
    lv_label_set_text(scr->label_21, "h");
    lv_label_set_long_mode(scr->label_21, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_21, 120, 230);
    lv_obj_set_size(scr->label_21, 20, 40);

    // Set style of scr->label_21
    lv_obj_set_style_text_color(scr->label_21, lv_color_hex(0xd2b2e9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_21, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_18
    scr->container_18 = lv_obj_create(scr->cont_charge);
    lv_obj_set_pos(scr->container_18, 260, 580);
    lv_obj_set_size(scr->container_18, 200, 280);
    lv_obj_set_scrollbar_mode(scr->container_18, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_18
    lv_obj_set_style_radius(scr->container_18, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_18, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_18, 66, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_23
    scr->label_23 = lv_label_create(scr->container_18);
    lv_label_set_text(scr->label_23, "Energy consumed");
    lv_label_set_long_mode(scr->label_23, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_23, 20, 110);
    lv_obj_set_size(scr->label_23, 170, 80);

    // Set style of scr->label_23
    lv_obj_set_style_text_color(scr->label_23, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_23, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_consume
    scr->label_consume = lv_label_create(scr->container_18);
    lv_label_set_text(scr->label_consume, "0.0");
    lv_label_set_long_mode(scr->label_consume, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_consume, 20, 200);
    lv_obj_set_size(scr->label_consume, 100, 70);

    // Set style of scr->label_consume
    lv_obj_set_style_text_color(scr->label_consume, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_consume, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_26
    scr->label_26 = lv_label_create(scr->container_18);
    lv_label_set_text(scr->label_26, "kW");
    lv_label_set_long_mode(scr->label_26, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_26, 120, 230);
    lv_obj_set_size(scr->label_26, 68, 40);

    // Set style of scr->label_26
    lv_obj_set_style_text_color(scr->label_26, lv_color_hex(0xd2b2e9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_26, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->container_18);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(consumption_80x80.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 20, 20);

    // Init scr->container_19
    scr->container_19 = lv_obj_create(scr->cont_charge);
    lv_obj_set_pos(scr->container_19, 490, 580);
    lv_obj_set_size(scr->container_19, 200, 280);
    lv_obj_set_scrollbar_mode(scr->container_19, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_19
    lv_obj_set_style_radius(scr->container_19, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_19, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_19, 64, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_9
    scr->image_9 = lv_img_create(scr->container_19);
    lv_img_set_src(scr->image_9, LVGL_IMAGE_PATH(driving_range_80x80.png));
    lv_img_set_pivot(scr->image_9, 50, 50);
    lv_img_set_offset_x(scr->image_9, 0);
    lv_img_set_offset_y(scr->image_9, 0);
    lv_img_set_angle(scr->image_9, 0);
    lv_obj_set_pos(scr->image_9, 20, 20);

    // Init scr->label_22
    scr->label_22 = lv_label_create(scr->container_19);
    lv_label_set_text(scr->label_22, "Driving Range");
    lv_label_set_long_mode(scr->label_22, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_22, 20, 110);
    lv_obj_set_size(scr->label_22, 170, 80);

    // Set style of scr->label_22
    lv_obj_set_style_text_color(scr->label_22, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_22, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_km
    scr->label_km = lv_label_create(scr->container_19);
    lv_label_set_text(scr->label_km, "0");
    lv_label_set_long_mode(scr->label_km, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_km, 20, 200);
    lv_obj_set_size(scr->label_km, 100, 70);

    // Set style of scr->label_km
    lv_obj_set_style_text_color(scr->label_km, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_km, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_27
    scr->label_27 = lv_label_create(scr->container_19);
    lv_label_set_text(scr->label_27, "km");
    lv_label_set_long_mode(scr->label_27, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_27, 130, 230);
    lv_obj_set_size(scr->label_27, 60, 40);

    // Set style of scr->label_27
    lv_obj_set_style_text_color(scr->label_27, lv_color_hex(0xd2b2e9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_27, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);


}


