/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) scrMain_custom_load_start(void) {
}

static void scrMain_load_start (lv_event_t *e) {
    scrMain_custom_load_start();
}

static void scrMain_contItem1_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrCharge
        scrCharge_create(&ui_manager);
        // load scrCharge
        lv_scr_load_anim(scrCharge_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scrMain_contItem2_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrSmartHome
        scrSmartHome_create(&ui_manager);
        // load scrSmartHome
        lv_scr_load_anim(scrSmartHome_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scrMain_contItem3_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrSmartMeter
        scrSmartMeter_create(&ui_manager);
        // load scrSmartMeter
        lv_scr_load_anim(scrSmartMeter_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scrMain_contItem5_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrAbout
        scrAbout_create(&ui_manager);
        // load scrAbout
        lv_scr_load_anim(scrAbout_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void scrMain_create(ui_manager_t *ui)
{
    scrMain_t *scr = scrMain_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_img_recolor(scr->obj, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(scr->obj, 142, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(scr->obj, lv_color_hex(0x20130b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x26190f), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrMain_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->cont_datetime
    scr->cont_datetime = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_datetime, 0, 200);
    lv_obj_set_size(scr->cont_datetime, 700, 300);
    lv_obj_set_scrollbar_mode(scr->cont_datetime, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_datetime
    lv_obj_set_style_radius(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_datetime, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_datetime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_time
    scr->label_time = lv_label_create(scr->cont_datetime);
    lv_label_set_text(scr->label_time, "09:58");
    lv_label_set_long_mode(scr->label_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_time, 50, 120);
    lv_obj_set_size(scr->label_time, 400, 180);

    // Set style of scr->label_time
    lv_obj_set_style_text_color(scr->label_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_time, fs_droidsansfallback_140, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_date
    scr->label_date = lv_label_create(scr->cont_datetime);
    lv_label_set_text(scr->label_date, "Wednesday,1 August");
    lv_label_set_long_mode(scr->label_date, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_date, 50, 8);
    lv_obj_set_size(scr->label_date, 600, 100);

    // Set style of scr->label_date
    lv_obj_set_style_text_color(scr->label_date, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_date, fs_droidsansfallback_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_item
    scr->cont_item = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_item, 0, 704);
    lv_obj_set_size(scr->cont_item, 1920, 400);
    lv_obj_set_scrollbar_mode(scr->cont_item, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_item
    lv_obj_set_style_radius(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_item, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contItem1
    scr->contItem1 = lv_obj_create(scr->cont_item);
    lv_obj_set_pos(scr->contItem1, 36, 75);
    lv_obj_set_size(scr->contItem1, 350, 250);
    lv_obj_set_scrollbar_mode(scr->contItem1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contItem1
    lv_obj_set_style_radius(scr->contItem1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contItem1, lv_color_hex(0x54211b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->contItem1
    lv_obj_add_event_cb(scr->contItem1, scrMain_contItem1_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->contImg1
    scr->contImg1 = lv_obj_create(scr->contItem1);
    lv_obj_set_pos(scr->contImg1, 30, 30);
    lv_obj_set_size(scr->contImg1, 100, 100);
    lv_obj_set_scrollbar_mode(scr->contImg1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contImg1
    lv_obj_set_style_radius(scr->contImg1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contImg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contImg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contImg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contImg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contImg1, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contImg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->contImg1);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(charging_80x80.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 10, 10);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->contItem1);
    lv_label_set_text(scr->label_1, "EV Charging");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 25, 180);
    lv_obj_set_size(scr->label_1, 300, 50);

    // Set style of scr->label_1
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contItem2
    scr->contItem2 = lv_obj_create(scr->cont_item);
    lv_obj_set_pos(scr->contItem2, 412, 75);
    lv_obj_set_size(scr->contItem2, 350, 250);
    lv_obj_set_scrollbar_mode(scr->contItem2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contItem2
    lv_obj_set_style_radius(scr->contItem2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contItem2, lv_color_hex(0x54211b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->contItem2
    lv_obj_add_event_cb(scr->contItem2, scrMain_contItem2_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->contImg2
    scr->contImg2 = lv_obj_create(scr->contItem2);
    lv_obj_set_pos(scr->contImg2, 30, 30);
    lv_obj_set_size(scr->contImg2, 100, 100);
    lv_obj_set_scrollbar_mode(scr->contImg2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contImg2
    lv_obj_set_style_radius(scr->contImg2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contImg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contImg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contImg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contImg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contImg2, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contImg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->contImg2);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(wifi_60x60.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 20, 20);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->contItem2);
    lv_label_set_text(scr->label_2, "Smart Home");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 25, 180);
    lv_obj_set_size(scr->label_2, 300, 50);

    // Set style of scr->label_2
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contItem3
    scr->contItem3 = lv_obj_create(scr->cont_item);
    lv_obj_set_pos(scr->contItem3, 802, 75);
    lv_obj_set_size(scr->contItem3, 350, 250);
    lv_obj_set_scrollbar_mode(scr->contItem3, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contItem3
    lv_obj_set_style_radius(scr->contItem3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contItem3, lv_color_hex(0x54211b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->contItem3
    lv_obj_add_event_cb(scr->contItem3, scrMain_contItem3_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->contImg3
    scr->contImg3 = lv_obj_create(scr->contItem3);
    lv_obj_set_pos(scr->contImg3, 30, 30);
    lv_obj_set_size(scr->contImg3, 100, 100);
    lv_obj_set_scrollbar_mode(scr->contImg3, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contImg3
    lv_obj_set_style_radius(scr->contImg3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contImg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contImg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contImg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contImg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contImg3, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contImg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->contImg3);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(brightness_60x60.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 20, 20);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->contItem3);
    lv_label_set_text(scr->label_3, "Smart Meter");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 25, 180);
    lv_obj_set_size(scr->label_3, 300, 50);

    // Set style of scr->label_3
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contItem4
    scr->contItem4 = lv_obj_create(scr->cont_item);
    lv_obj_set_pos(scr->contItem4, 1178, 75);
    lv_obj_set_size(scr->contItem4, 350, 250);
    lv_obj_set_scrollbar_mode(scr->contItem4, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contItem4
    lv_obj_set_style_radius(scr->contItem4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contItem4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contItem4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contItem4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contItem4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contItem4, lv_color_hex(0x54211b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contItem4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contImg4
    scr->contImg4 = lv_obj_create(scr->contItem4);
    lv_obj_set_pos(scr->contImg4, 30, 30);
    lv_obj_set_size(scr->contImg4, 100, 100);
    lv_obj_set_scrollbar_mode(scr->contImg4, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contImg4
    lv_obj_set_style_radius(scr->contImg4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contImg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contImg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contImg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contImg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contImg4, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contImg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->contImg4);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(charging_80x80.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_offset_x(scr->image_4, 0);
    lv_img_set_offset_y(scr->image_4, 0);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_pos(scr->image_4, 10, 10);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->contItem4);
    lv_label_set_text(scr->label_4, "Thermostat");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 25, 180);
    lv_obj_set_size(scr->label_4, 300, 50);

    // Set style of scr->label_4
    lv_obj_set_style_text_color(scr->label_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->contItem5
    scr->contItem5 = lv_obj_create(scr->cont_item);
    lv_obj_set_pos(scr->contItem5, 1558, 75);
    lv_obj_set_size(scr->contItem5, 350, 250);
    lv_obj_set_scrollbar_mode(scr->contItem5, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contItem5
    lv_obj_set_style_radius(scr->contItem5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contItem5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contItem5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contItem5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contItem5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contItem5, lv_color_hex(0x54211b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contItem5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->contItem5
    lv_obj_add_event_cb(scr->contItem5, scrMain_contItem5_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->contImg5
    scr->contImg5 = lv_obj_create(scr->contItem5);
    lv_obj_set_pos(scr->contImg5, 30, 30);
    lv_obj_set_size(scr->contImg5, 100, 100);
    lv_obj_set_scrollbar_mode(scr->contImg5, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->contImg5
    lv_obj_set_style_radius(scr->contImg5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->contImg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->contImg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->contImg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->contImg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->contImg5, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->contImg5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_5
    scr->image_5 = lv_img_create(scr->contImg5);
    lv_img_set_src(scr->image_5, LVGL_IMAGE_PATH(about_60x60.png));
    lv_img_set_pivot(scr->image_5, 50, 50);
    lv_img_set_offset_x(scr->image_5, 0);
    lv_img_set_offset_y(scr->image_5, 0);
    lv_img_set_angle(scr->image_5, 0);
    lv_obj_set_pos(scr->image_5, 20, 20);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->contItem5);
    lv_label_set_text(scr->label_5, "About");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 25, 180);
    lv_obj_set_size(scr->label_5, 300, 50);

    // Set style of scr->label_5
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5, fs_montserratmedium_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_13
    scr->container_13 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_13, 1000, 200);
    lv_obj_set_size(scr->container_13, 800, 300);
    lv_obj_set_scrollbar_mode(scr->container_13, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_13
    lv_obj_set_style_radius(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_13, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_7
    scr->image_7 = lv_img_create(scr->container_13);
    lv_img_set_src(scr->image_7, LVGL_IMAGE_PATH(Cloudy_200x200.png));
    lv_img_set_pivot(scr->image_7, 50, 50);
    lv_img_set_offset_x(scr->image_7, 0);
    lv_img_set_offset_y(scr->image_7, 0);
    lv_img_set_angle(scr->image_7, 0);
    lv_obj_set_pos(scr->image_7, 30, 0);

    // Set style of scr->image_7
    lv_obj_set_style_img_recolor(scr->image_7, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->container_13);
    lv_label_set_text(scr->label_6, "Cloudy");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 30, 190);
    lv_obj_set_size(scr->label_6, 200, 50);

    // Set style of scr->label_6
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xe12717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->container_13);
    lv_label_set_text(scr->label_7, "H:19°   L:10°");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 30, 240);
    lv_obj_set_size(scr->label_7, 250, 40);

    // Set style of scr->label_7
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->container_13);
    lv_label_set_text(scr->label_8, "16°");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 450, 0);
    lv_obj_set_size(scr->label_8, 300, 200);

    // Set style of scr->label_8
    lv_obj_set_style_text_align(scr->label_8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8, fs_montserratmedium_180, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->container_13);
    lv_label_set_text(scr->label_9, "Outdoor");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 500, 230);
    lv_obj_set_size(scr->label_9, 250, 60);

    // Set style of scr->label_9
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_9, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);


}


