/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_droidsansfallback_140;
lv_font_t *fs_droidsansfallback_60;
lv_font_t *fs_montserratmedium_36;
lv_font_t *fs_montserratmedium_40;
lv_font_t *fs_montserratmedium_180;
lv_font_t *fs_montserratmedium_50;
lv_font_t *fs_montserratmedium_30;
lv_font_t *fs_montserratmedium_80;
lv_font_t *fs_montserratmedium_100;
lv_font_t *fs_montserratmedium_60;
lv_font_t *fs_montserratmedium_70;

void ui_init(void)
{
    fs_droidsansfallback_140 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 140);
    fs_droidsansfallback_60 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 60);
    fs_montserratmedium_36 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 36);
    fs_montserratmedium_40 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 40);
    fs_montserratmedium_180 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 180);
    fs_montserratmedium_50 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 50);
    fs_montserratmedium_30 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 30);
    fs_montserratmedium_80 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 80);
    fs_montserratmedium_100 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 100);
    fs_montserratmedium_60 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 60);
    fs_montserratmedium_70 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 70);
    if (!fs_droidsansfallback_140) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_140");
    	return;
    }
    if (!fs_droidsansfallback_60) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_60");
    	return;
    }
    if (!fs_montserratmedium_36) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_36");
    	return;
    }
    if (!fs_montserratmedium_40) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_40");
    	return;
    }
    if (!fs_montserratmedium_180) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_180");
    	return;
    }
    if (!fs_montserratmedium_50) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_50");
    	return;
    }
    if (!fs_montserratmedium_30) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_30");
    	return;
    }
    if (!fs_montserratmedium_80) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_80");
    	return;
    }
    if (!fs_montserratmedium_100) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_100");
    	return;
    }
    if (!fs_montserratmedium_60) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_60");
    	return;
    }
    if (!fs_montserratmedium_70) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_70");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    scrMain_create(&ui_manager);
    lv_scr_load(scrMain_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
