/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *cont_datetime;
    lv_obj_t *label_time;
    lv_obj_t *label_date;
    lv_obj_t *cont_item;
    lv_obj_t *contItem1;
    lv_obj_t *contImg1;
    lv_obj_t *image_1;
    lv_obj_t *label_1;
    lv_obj_t *contItem2;
    lv_obj_t *contImg2;
    lv_obj_t *image_2;
    lv_obj_t *label_2;
    lv_obj_t *contItem3;
    lv_obj_t *contImg3;
    lv_obj_t *image_3;
    lv_obj_t *label_3;
    lv_obj_t *contItem4;
    lv_obj_t *contImg4;
    lv_obj_t *image_4;
    lv_obj_t *label_4;
    lv_obj_t *contItem5;
    lv_obj_t *contImg5;
    lv_obj_t *image_5;
    lv_obj_t *label_5;
    lv_obj_t *container_13;
    lv_obj_t *image_7;
    lv_obj_t *label_6;
    lv_obj_t *label_7;
    lv_obj_t *label_8;
    lv_obj_t *label_9;
} scrMain_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *back;
    lv_obj_t *container_14;
    lv_obj_t *label_11;
    lv_obj_t *label_12;
    lv_obj_t *label_money;
    lv_obj_t *label_16;
    lv_obj_t *container_15;
    lv_obj_t *label_13;
    lv_obj_t *chart_1;
    lv_obj_t *label_1;
    lv_obj_t *label_2;
    lv_obj_t *label_6;
    lv_obj_t *label_7;
    lv_obj_t *label_8;
    lv_obj_t *label_9;
    lv_obj_t *label_14;
    lv_obj_t *label_15;
    lv_obj_t *label_17;
    lv_obj_t *label_10;
    lv_obj_t *cont_charge;
    lv_obj_t *arc_charge;
    lv_obj_t *label_percent;
    lv_obj_t *btn_charge;
    lv_obj_t *label_18;
    lv_obj_t *container_17;
    lv_obj_t *image_8;
    lv_obj_t *label_19;
    lv_obj_t *label_time;
    lv_obj_t *label_21;
    lv_obj_t *container_18;
    lv_obj_t *label_23;
    lv_obj_t *label_consume;
    lv_obj_t *label_26;
    lv_obj_t *image_1;
    lv_obj_t *container_19;
    lv_obj_t *image_9;
    lv_obj_t *label_22;
    lv_obj_t *label_km;
    lv_obj_t *label_27;
} scrCharge_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *back;
    lv_obj_t *title;
    lv_obj_t *cont_main;
    lv_obj_t *cont_1;
    lv_obj_t *label_2;
    lv_obj_t *container_7;
    lv_obj_t *label_3;
    lv_obj_t *label_10;
    lv_obj_t *label_11;
    lv_obj_t *cont_2;
    lv_obj_t *label_6;
    lv_obj_t *arc_charge;
    lv_obj_t *label_charge;
    lv_obj_t *cont_3;
    lv_obj_t *switch_lock;
    lv_obj_t *label_12;
    lv_obj_t *label_13;
    lv_obj_t *image_2;
    lv_obj_t *cont_4;
    lv_obj_t *label_14;
    lv_obj_t *slider_light1;
    lv_obj_t *label_16;
    lv_obj_t *label_17;
    lv_obj_t *slider_light2;
    lv_obj_t *cont_5;
    lv_obj_t *label_15;
} scrSmartHome_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_1;
    lv_obj_t *back;
    lv_obj_t *label_20;
} scrPhotoViewer_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *back;
    lv_obj_t *label_18;
    lv_obj_t *label_19;
    lv_obj_t *qrcode_1;
} scrAbout_t;


typedef struct {
    bool auto_del;
    scrMain_t scrMain;
    scrCharge_t scrCharge;
    scrSmartHome_t scrSmartHome;
    scrPhotoViewer_t scrPhotoViewer;
    scrAbout_t scrAbout;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline scrMain_t *scrMain_get(ui_manager_t *ui)
{
    return &ui->scrMain;
}

static inline scrCharge_t *scrCharge_get(ui_manager_t *ui)
{
    return &ui->scrCharge;
}

static inline scrSmartHome_t *scrSmartHome_get(ui_manager_t *ui)
{
    return &ui->scrSmartHome;
}

static inline scrPhotoViewer_t *scrPhotoViewer_get(ui_manager_t *ui)
{
    return &ui->scrPhotoViewer;
}

static inline scrAbout_t *scrAbout_get(ui_manager_t *ui)
{
    return &ui->scrAbout;
}


void scrMain_create(ui_manager_t *ui);
void scrCharge_create(ui_manager_t *ui);
void scrSmartHome_create(ui_manager_t *ui);
void scrPhotoViewer_create(ui_manager_t *ui);
void scrAbout_create(ui_manager_t *ui);


extern lv_font_t *fs_droidsansfallback_140;
extern lv_font_t *fs_droidsansfallback_60;
extern lv_font_t *fs_montserratmedium_36;
extern lv_font_t *fs_montserratmedium_40;
extern lv_font_t *fs_montserratmedium_180;
extern lv_font_t *fs_montserratmedium_50;
extern lv_font_t *fs_montserratmedium_30;
extern lv_font_t *fs_montserratmedium_80;
extern lv_font_t *fs_montserratmedium_24;
extern lv_font_t *fs_montserratmedium_60;
extern lv_font_t *fs_montserratmedium_35;
extern lv_font_t *fs_montserratmedium_100;
extern lv_font_t *fs_montserratmedium_70;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
