/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) scrCopy_custom_load_start(void) {
}

static void scrCopy_load_start (lv_event_t *e) {
    scrCopy_custom_load_start();
}

static void scrCopy_btn_next_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrLoad
        scrLoad_create(&ui_manager);
        // load scrLoad
        lv_scr_load_anim(scrLoad_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void scrCopy_btn_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrMain
        scrMain_create(&ui_manager);
        // load scrMain
        lv_scr_load_anim(scrMain_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}

void __attribute__((weak)) scrCopy_btn_minus_custom_clicked(void) {
}

static void scrCopy_btn_minus_clicked (lv_event_t *e) {
    scrCopy_btn_minus_custom_clicked();
}

void __attribute__((weak)) scrCopy_btn_plus_custom_clicked(void) {
}

static void scrCopy_btn_plus_clicked (lv_event_t *e) {
    scrCopy_btn_plus_custom_clicked();
}


void scrCopy_create(ui_manager_t *ui)
{
    scrCopy_t *scr = scrCopy_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrCopy_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->cont_top
    scr->cont_top = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_top, 0, 60);
    lv_obj_set_size(scr->cont_top, 1280, 80);
    lv_obj_set_scrollbar_mode(scr->cont_top, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_top
    lv_obj_set_style_bg_color(scr->cont_top, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_16
    scr->label_16 = lv_label_create(scr->cont_top);
    lv_label_set_text(scr->label_16, "COPPING_IMAGE");
    lv_label_set_long_mode(scr->label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_16, 390, 20);
    lv_obj_set_size(scr->label_16, 500, 40);

    // Set style of scr->label_16
    lv_obj_set_style_text_align(scr->label_16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_16, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_16, fs_droidsansfallback_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_main
    scr->cont_main = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_main, 0, 140);
    lv_obj_set_size(scr->cont_main, 1280, 400);
    lv_obj_set_scrollbar_mode(scr->cont_main, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_main
    lv_obj_set_style_bg_color(scr->cont_main, lv_color_hex(0xf3f9fe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_scan
    scr->image_scan = lv_img_create(scr->cont_main);
    lv_img_set_src(scr->image_scan, LVGL_IMAGE_PATH(birds_700x400.png));
    lv_img_set_pivot(scr->image_scan, 50, 50);
    lv_img_set_offset_x(scr->image_scan, 0);
    lv_img_set_offset_y(scr->image_scan, 0);
    lv_img_set_angle(scr->image_scan, 0);
    lv_obj_set_pos(scr->image_scan, 0, 0);

    // Init scr->cont_select
    scr->cont_select = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->cont_select, 720, 20);
    lv_obj_set_size(scr->cont_select, 250, 360);
    lv_obj_set_scrollbar_mode(scr->cont_select, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_select
    lv_obj_set_style_border_width(scr->cont_select, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_select, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_select, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_select, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_select, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_select, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->dropdown_1
    scr->dropdown_1 = lv_dropdown_create(scr->cont_select);
    lv_obj_set_style_max_height(lv_dropdown_get_list(scr->dropdown_1), 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_dropdown_set_dir(scr->dropdown_1, LV_DIR_BOTTOM);
    lv_dropdown_set_symbol(scr->dropdown_1, LV_SYMBOL_DOWN);
    lv_dropdown_set_options(scr->dropdown_1, "Best\nNormal\nDraft");
    lv_obj_set_pos(scr->dropdown_1, 25, 20);
    lv_obj_set_size(scr->dropdown_1, 200, 60);

    // Set style of scr->dropdown_1
    lv_obj_set_style_bg_color(scr->dropdown_1, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->dropdown_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->dropdown_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->dropdown_1, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(scr->dropdown_1), fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->dropdown_1, LV_FONT_DEFAULT, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->dropdown_2
    scr->dropdown_2 = lv_dropdown_create(scr->cont_select);
    lv_obj_set_style_max_height(lv_dropdown_get_list(scr->dropdown_2), 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_dropdown_set_dir(scr->dropdown_2, LV_DIR_BOTTOM);
    lv_dropdown_set_symbol(scr->dropdown_2, LV_SYMBOL_DOWN);
    lv_dropdown_set_options(scr->dropdown_2, "72 DPI\n96 DPI\n150 DPI\n300 DPI");
    lv_obj_set_pos(scr->dropdown_2, 25, 280);
    lv_obj_set_size(scr->dropdown_2, 200, 60);

    // Set style of scr->dropdown_2
    lv_obj_set_style_bg_color(scr->dropdown_2, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->dropdown_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->dropdown_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->dropdown_2, fs_montserratmedium_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(scr->dropdown_2), fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->dropdown_2, LV_FONT_DEFAULT, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->btn_next
    scr->btn_next = lv_btn_create(scr->cont_main);
    lv_obj_t *btn_next_label = lv_label_create(scr->btn_next);
    lv_label_set_text(btn_next_label, "Next");
    lv_obj_align(btn_next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_next, 1040, 320);
    lv_obj_set_size(scr->btn_next, 200, 60);

    // Set style of scr->btn_next
    lv_obj_set_style_bg_color(scr->btn_next, lv_color_hex(0x2ab620), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_next, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_next
    lv_obj_add_event_cb(scr->btn_next, scrCopy_btn_next_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->btn_back
    scr->btn_back = lv_btn_create(scr->cont_main);
    lv_obj_t *btn_back_label = lv_label_create(scr->btn_back);
    lv_label_set_text(btn_back_label, "Back");
    lv_obj_align(btn_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_back, 1040, 220);
    lv_obj_set_size(scr->btn_back, 200, 60);

    // Set style of scr->btn_back
    lv_obj_set_style_bg_color(scr->btn_back, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_back, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_back
    lv_obj_add_event_cb(scr->btn_back, scrCopy_btn_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_48
    scr->container_48 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_48, 1004, 20);
    lv_obj_set_size(scr->container_48, 250, 180);
    lv_obj_set_scrollbar_mode(scr->container_48, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_48
    lv_obj_set_style_border_width(scr->container_48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_48, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->switch_1
    scr->switch_1 = lv_switch_create(scr->container_48);
    lv_obj_set_pos(scr->switch_1, 25, 140);
    lv_obj_set_size(scr->switch_1, 50, 25);

    // Init scr->switch_2
    scr->switch_2 = lv_switch_create(scr->container_48);
    lv_obj_set_pos(scr->switch_2, 175, 140);
    lv_obj_set_size(scr->switch_2, 50, 25);

    // Init scr->label_24
    scr->label_24 = lv_label_create(scr->container_48);
    lv_label_set_text(scr->label_24, "Color");
    lv_label_set_long_mode(scr->label_24, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_24, 10, 110);
    lv_obj_set_size(scr->label_24, 80, 20);

    // Set style of scr->label_24
    lv_obj_set_style_text_align(scr->label_24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_24, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_25
    scr->label_25 = lv_label_create(scr->container_48);
    lv_label_set_text(scr->label_25, "Vertical");
    lv_label_set_long_mode(scr->label_25, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_25, 160, 110);
    lv_obj_set_size(scr->label_25, 80, 20);

    // Set style of scr->label_25
    lv_obj_set_style_text_align(scr->label_25, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_25, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_27
    scr->label_27 = lv_label_create(scr->container_48);
    lv_label_set_text(scr->label_27, "Copies");
    lv_label_set_long_mode(scr->label_27, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_27, 75, 10);
    lv_obj_set_size(scr->label_27, 100, 30);

    // Set style of scr->label_27
    lv_obj_set_style_text_align(scr->label_27, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_27, fs_montserratmedium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->btn_minus
    scr->btn_minus = lv_btn_create(scr->container_48);
    lv_obj_t *btn_minus_label = lv_label_create(scr->btn_minus);
    lv_label_set_text(btn_minus_label, "-");
    lv_obj_align(btn_minus_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_minus, 25, 50);
    lv_obj_set_size(scr->btn_minus, 50, 50);

    // Set style of scr->btn_minus
    lv_obj_set_style_bg_color(scr->btn_minus, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_minus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_minus, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_minus
    lv_obj_add_event_cb(scr->btn_minus, scrCopy_btn_minus_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->btn_plus
    scr->btn_plus = lv_btn_create(scr->container_48);
    lv_obj_t *btn_plus_label = lv_label_create(scr->btn_plus);
    lv_label_set_text(btn_plus_label, "+");
    lv_obj_align(btn_plus_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_plus, 175, 50);
    lv_obj_set_size(scr->btn_plus, 50, 50);

    // Set style of scr->btn_plus
    lv_obj_set_style_bg_color(scr->btn_plus, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_plus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_plus, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_plus
    lv_obj_add_event_cb(scr->btn_plus, scrCopy_btn_plus_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_num
    scr->label_num = lv_label_create(scr->container_48);
    lv_label_set_text(scr->label_num, "1");
    lv_label_set_long_mode(scr->label_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_num, 95, 56);
    lv_obj_set_size(scr->label_num, 60, 40);

    // Set style of scr->label_num
    lv_obj_set_style_text_align(scr->label_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->label_num, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->label_num, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_num, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);


}


