/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) scrLoad_custom_loaded(void) {
}

static void scrLoad_loaded (lv_event_t *e) {
    scrLoad_custom_loaded();
}


void scrLoad_create(ui_manager_t *ui)
{
    scrLoad_t *scr = scrLoad_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrLoad_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->container_49
    scr->container_49 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_49, 0, 60);
    lv_obj_set_size(scr->container_49, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_49, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_49
    lv_obj_set_style_pad_top(scr->container_49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_49, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_49, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_prog
    scr->arc_prog = lv_arc_create(scr->container_49);
    lv_arc_set_mode(scr->arc_prog, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_prog, 0, 100);
    lv_arc_set_value(scr->arc_prog, 0);
    lv_arc_set_bg_angles(scr->arc_prog, 0, 360);
    lv_arc_set_angles(scr->arc_prog, 0, 0);
    lv_arc_set_rotation(scr->arc_prog, 270);
    lv_arc_set_change_rate(scr->arc_prog, 720);
    lv_obj_set_pos(scr->arc_prog, 490, 50);
    lv_obj_set_size(scr->arc_prog, 300, 300);

    // Init scr->label_30
    scr->label_30 = lv_label_create(scr->container_49);
    lv_label_set_text(scr->label_30, "Printing, please waiting...");
    lv_label_set_long_mode(scr->label_30, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_30, 240, 400);
    lv_obj_set_size(scr->label_30, 800, 60);

    // Set style of scr->label_30
    lv_obj_set_style_text_color(scr->label_30, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_30, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_prog
    scr->label_prog = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_prog, "0%");
    lv_label_set_long_mode(scr->label_prog, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_prog, 565, 320);
    lv_obj_set_size(scr->label_prog, 150, 60);

    // Set style of scr->label_prog
    lv_obj_set_style_text_color(scr->label_prog, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_prog, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_prog, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);


}


