/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) scrMain_custom_load_start(void) {
}

static void scrMain_load_start (lv_event_t *e) {
    scrMain_custom_load_start();
}

static void scrMain_cont_copy_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrCopy
        scrCopy_create(&ui_manager);
        // load scrCopy
        lv_scr_load_anim(scrCopy_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}

static void scrMain_cont_scan_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrScan
        scrScan_create(&ui_manager);
        // load scrScan
        lv_scr_load_anim(scrScan_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}

static void scrMain_cont_print_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrPrint
        scrPrint_create(&ui_manager);
        // load scrPrint
        lv_scr_load_anim(scrPrint_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}

static void scrMain_cont_setup_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrSetup
        scrSetup_create(&ui_manager);
        // load scrSetup
        lv_scr_load_anim(scrSetup_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}


void scrMain_create(ui_manager_t *ui)
{
    scrMain_t *scr = scrMain_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrMain_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->bg
    scr->bg = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->bg, 0, 60);
    lv_obj_set_size(scr->bg, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->bg, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->bg
    lv_obj_set_style_bg_color(scr->bg, lv_color_hex(0xe8f2fd), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->top_cont
    scr->top_cont = lv_obj_create(scr->bg);
    lv_obj_set_pos(scr->top_cont, 0, 0);
    lv_obj_set_size(scr->top_cont, 1280, 80);
    lv_obj_set_scrollbar_mode(scr->top_cont, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->top_cont
    lv_obj_set_style_bg_color(scr->top_cont, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->top_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->top_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->top_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->top_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->top_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->top_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->top_cont);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(wifi.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 100, 23);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->top_cont);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(tel.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 180, 22);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->top_cont);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(eco.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 260, 23);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->top_cont);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(pc.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_offset_x(scr->image_4, 0);
    lv_img_set_offset_y(scr->image_4, 0);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_pos(scr->image_4, 340, 25);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->top_cont);
    lv_label_set_text(scr->label_1, "17 Jun 2026 14:30");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 800, 25);
    lv_obj_set_size(scr->label_1, 400, 30);

    // Set style of scr->label_1
    lv_obj_set_style_text_align(scr->label_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_main
    scr->cont_main = lv_obj_create(scr->bg);
    lv_obj_set_pos(scr->cont_main, 100, 100);
    lv_obj_set_size(scr->cont_main, 1080, 220);
    lv_obj_set_scrollbar_mode(scr->cont_main, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_main
    lv_obj_set_style_border_width(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_main, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_copy
    scr->cont_copy = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->cont_copy, 50, 10);
    lv_obj_set_size(scr->cont_copy, 160, 200);
    lv_obj_set_scrollbar_mode(scr->cont_copy, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_copy
    lv_obj_set_style_border_width(scr->cont_copy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_copy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_copy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_copy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_copy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->cont_copy, LVGL_IMAGE_PATH(btn_bg_1.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_copy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cont_copy
    lv_obj_add_event_cb(scr->cont_copy, scrMain_cont_copy_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_19
    scr->image_19 = lv_img_create(scr->cont_copy);
    lv_img_set_src(scr->image_19, LVGL_IMAGE_PATH(copy.png));
    lv_img_set_pivot(scr->image_19, 50, 50);
    lv_img_set_offset_x(scr->image_19, 0);
    lv_img_set_offset_y(scr->image_19, 0);
    lv_img_set_angle(scr->image_19, 0);
    lv_obj_set_pos(scr->image_19, 90, 20);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->cont_copy);
    lv_label_set_text(scr->label_4, "COPY");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 20, 145);
    lv_obj_set_size(scr->label_4, 120, 35);

    // Set style of scr->label_4
    lv_obj_set_style_text_color(scr->label_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_scan
    scr->cont_scan = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->cont_scan, 300, 10);
    lv_obj_set_size(scr->cont_scan, 160, 200);
    lv_obj_set_scrollbar_mode(scr->cont_scan, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_scan
    lv_obj_set_style_border_width(scr->cont_scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->cont_scan, LVGL_IMAGE_PATH(btn_bg_2.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cont_scan
    lv_obj_add_event_cb(scr->cont_scan, scrMain_cont_scan_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_20
    scr->image_20 = lv_img_create(scr->cont_scan);
    lv_img_set_src(scr->image_20, LVGL_IMAGE_PATH(scan.png));
    lv_img_set_pivot(scr->image_20, 50, 50);
    lv_img_set_offset_x(scr->image_20, 0);
    lv_img_set_offset_y(scr->image_20, 0);
    lv_img_set_angle(scr->image_20, 0);
    lv_obj_set_pos(scr->image_20, 90, 20);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->cont_scan);
    lv_label_set_text(scr->label_5, "SCAN");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 20, 145);
    lv_obj_set_size(scr->label_5, 120, 35);

    // Set style of scr->label_5
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_print
    scr->cont_print = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->cont_print, 600, 10);
    lv_obj_set_size(scr->cont_print, 160, 200);
    lv_obj_set_scrollbar_mode(scr->cont_print, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_print
    lv_obj_set_style_border_width(scr->cont_print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->cont_print, LVGL_IMAGE_PATH(btn_bg_3.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_print, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cont_print
    lv_obj_add_event_cb(scr->cont_print, scrMain_cont_print_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_21
    scr->image_21 = lv_img_create(scr->cont_print);
    lv_img_set_src(scr->image_21, LVGL_IMAGE_PATH(print_60x60.png));
    lv_img_set_pivot(scr->image_21, 50, 50);
    lv_img_set_offset_x(scr->image_21, 0);
    lv_img_set_offset_y(scr->image_21, 0);
    lv_img_set_angle(scr->image_21, 0);
    lv_obj_set_pos(scr->image_21, 80, 20);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->cont_print);
    lv_label_set_text(scr->label_6, "PRINT");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 20, 145);
    lv_obj_set_size(scr->label_6, 120, 35);

    // Set style of scr->label_6
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_setup
    scr->cont_setup = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->cont_setup, 870, 10);
    lv_obj_set_size(scr->cont_setup, 160, 200);
    lv_obj_set_scrollbar_mode(scr->cont_setup, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_setup
    lv_obj_set_style_border_width(scr->cont_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->cont_setup, LVGL_IMAGE_PATH(btn_bg_4.png), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cont_setup
    lv_obj_add_event_cb(scr->cont_setup, scrMain_cont_setup_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_22
    scr->image_22 = lv_img_create(scr->cont_setup);
    lv_img_set_src(scr->image_22, LVGL_IMAGE_PATH(setup.png));
    lv_img_set_pivot(scr->image_22, 50, 50);
    lv_img_set_offset_x(scr->image_22, 0);
    lv_img_set_offset_y(scr->image_22, 0);
    lv_img_set_angle(scr->image_22, 0);
    lv_obj_set_pos(scr->image_22, 80, 20);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->cont_setup);
    lv_label_set_text(scr->label_12, "SETUP");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 20, 145);
    lv_obj_set_size(scr->label_12, 120, 35);

    // Set style of scr->label_12
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_12, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_label
    scr->cont_label = lv_obj_create(scr->bg);
    lv_obj_set_pos(scr->cont_label, 100, 350);
    lv_obj_set_size(scr->cont_label, 600, 100);
    lv_obj_set_scrollbar_mode(scr->cont_label, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_label
    lv_obj_set_style_border_width(scr->cont_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_label, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->cont_label);
    lv_label_set_text(scr->label_3, "What do you want do today?");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 37, 34);
    lv_obj_set_size(scr->label_3, 526, 32);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_bar
    scr->cont_bar = lv_obj_create(scr->bg);
    lv_obj_set_pos(scr->cont_bar, 800, 350);
    lv_obj_set_size(scr->cont_bar, 380, 100);
    lv_obj_set_scrollbar_mode(scr->cont_bar, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_bar
    lv_obj_set_style_border_width(scr->cont_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_bar, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_1
    scr->bar_1 = lv_bar_create(scr->cont_bar);
    lv_bar_set_mode(scr->bar_1, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->bar_1, 0, 100);
    lv_bar_set_value(scr->bar_1, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_1, 40, 10);
    lv_obj_set_size(scr->bar_1, 30, 80);

    // Set style of scr->bar_1
    lv_obj_set_style_bg_opa(scr->bar_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_2
    scr->bar_2 = lv_bar_create(scr->cont_bar);
    lv_bar_set_mode(scr->bar_2, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->bar_2, 0, 100);
    lv_bar_set_value(scr->bar_2, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_2, 130, 10);
    lv_obj_set_size(scr->bar_2, 30, 80);

    // Set style of scr->bar_2
    lv_obj_set_style_bg_opa(scr->bar_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_3
    scr->bar_3 = lv_bar_create(scr->cont_bar);
    lv_bar_set_mode(scr->bar_3, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->bar_3, 0, 100);
    lv_bar_set_value(scr->bar_3, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_3, 220, 10);
    lv_obj_set_size(scr->bar_3, 30, 80);

    // Set style of scr->bar_3
    lv_obj_set_style_bg_opa(scr->bar_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bar_4
    scr->bar_4 = lv_bar_create(scr->cont_bar);
    lv_bar_set_mode(scr->bar_4, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->bar_4, 0, 100);
    lv_bar_set_value(scr->bar_4, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_4, 310, 10);
    lv_obj_set_size(scr->bar_4, 30, 80);

    // Set style of scr->bar_4
    lv_obj_set_style_bg_opa(scr->bar_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}


