/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void scrPrintFinish_btn_continue_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrMain
        scrMain_create(&ui_manager);
        // load scrMain
        lv_scr_load_anim(scrMain_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}


void scrPrintFinish_create(ui_manager_t *ui)
{
    scrPrintFinish_t *scr = scrPrintFinish_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_50
    scr->container_50 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_50, 0, 60);
    lv_obj_set_size(scr->container_50, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_50, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_50
    lv_obj_set_style_pad_top(scr->container_50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_50, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_50, lv_color_hex(0x2ab620), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_48
    scr->image_48 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_48, LVGL_IMAGE_PATH(ready_160x160.png));
    lv_img_set_pivot(scr->image_48, 50, 50);
    lv_img_set_offset_x(scr->image_48, 0);
    lv_img_set_offset_y(scr->image_48, 0);
    lv_img_set_angle(scr->image_48, 0);
    lv_obj_set_pos(scr->image_48, 560, 100);

    // Init scr->label_31
    scr->label_31 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_31, "Print Finished.");
    lv_label_set_long_mode(scr->label_31, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_31, 240, 300);
    lv_obj_set_size(scr->label_31, 800, 60);

    // Set style of scr->label_31
    lv_obj_set_style_text_color(scr->label_31, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_31, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_31, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->btn_continue
    scr->btn_continue = lv_btn_create(scr->obj);
    lv_obj_t *btn_continue_label = lv_label_create(scr->btn_continue);
    lv_label_set_text(btn_continue_label, "Continue");
    lv_obj_align(btn_continue_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_continue, 465, 400);
    lv_obj_set_size(scr->btn_continue, 350, 100);

    // Set style of scr->btn_continue
    lv_obj_set_style_bg_opa(scr->btn_continue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->btn_continue, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_continue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->btn_continue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->btn_continue, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_continue, fs_montserratmedium_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_continue
    lv_obj_add_event_cb(scr->btn_continue, scrPrintFinish_btn_continue_clicked, LV_EVENT_CLICKED, NULL);


}


