/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void scrPrintMobile_btn_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrPrint
        scrPrint_create(&ui_manager);
        // load scrPrint
        lv_scr_load_anim(scrPrint_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}


void scrPrintMobile_create(ui_manager_t *ui)
{
    scrPrintMobile_t *scr = scrPrintMobile_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_2, 0, 60);
    lv_obj_set_size(scr->container_2, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_2
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(printer2_150x150.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 421, 78);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(phone_110x130.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_offset_x(scr->image_4, 0);
    lv_img_set_offset_y(scr->image_4, 0);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_pos(scr->image_4, 705, 85);

    // Init scr->btn_back
    scr->btn_back = lv_btn_create(scr->container_2);
    lv_obj_t *btn_back_label = lv_label_create(scr->btn_back);
    lv_label_set_text(btn_back_label, "BACK");
    lv_obj_align(btn_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_back, 465, 340);
    lv_obj_set_size(scr->btn_back, 350, 100);

    // Set style of scr->btn_back
    lv_obj_set_style_bg_opa(scr->btn_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->btn_back, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->btn_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->btn_back, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_back, fs_montserratmedium_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_back
    lv_obj_add_event_cb(scr->btn_back, scrPrintMobile_btn_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(wave_50x80.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 615, 110);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->container_2);
    lv_label_set_text(scr->label_2, "Put your phone near to the printer");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 240, 260);
    lv_obj_set_size(scr->label_2, 800, 50);

    // Set style of scr->label_2
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);


}


