/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void scrSetup_btn_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrMain
        scrMain_create(&ui_manager);
        // load scrMain
        lv_scr_load_anim(scrMain_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}


void scrSetup_create(ui_manager_t *ui)
{
    scrSetup_t *scr = scrSetup_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_main
    scr->cont_main = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_main, 0, 60);
    lv_obj_set_size(scr->cont_main, 1280, 480);
    lv_obj_set_scrollbar_mode(scr->cont_main, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_main
    lv_obj_set_style_bg_color(scr->cont_main, lv_color_hex(0xe12e2e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_8
    scr->image_8 = lv_img_create(scr->cont_main);
    lv_img_set_src(scr->image_8, LVGL_IMAGE_PATH(nopermission_128x128.png));
    lv_img_set_pivot(scr->image_8, 50, 50);
    lv_img_set_offset_x(scr->image_8, 0);
    lv_img_set_offset_y(scr->image_8, 0);
    lv_img_set_angle(scr->image_8, 0);
    lv_obj_set_pos(scr->image_8, 576, 71);

    // Set style of scr->image_8
    lv_obj_set_style_img_recolor_opa(scr->image_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(scr->image_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->btn_back
    scr->btn_back = lv_btn_create(scr->cont_main);
    lv_obj_t *btn_back_label = lv_label_create(scr->btn_back);
    lv_label_set_text(btn_back_label, "BACK");
    lv_obj_align(btn_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_back, 465, 340);
    lv_obj_set_size(scr->btn_back, 350, 100);

    // Set style of scr->btn_back
    lv_obj_set_style_bg_opa(scr->btn_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->btn_back, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->btn_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->btn_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->btn_back, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_back, fs_montserratmedium_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_back
    lv_obj_add_event_cb(scr->btn_back, scrSetup_btn_back_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->cont_main);
    lv_label_set_text(scr->label_4, "Do Not Have Permission To Operate");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 240, 260);
    lv_obj_set_size(scr->label_4, 800, 50);

    // Set style of scr->label_4
    lv_obj_set_style_text_align(scr->label_4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_4, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_4, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);


}


