/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) scrScan_custom_load_start(void) {
}

static void scrScan_load_start (lv_event_t *e) {
    scrScan_custom_load_start();
}

void __attribute__((weak)) scrScan_slider_hue_custom_value_changed(void) {
}

static void scrScan_slider_hue_value_changed (lv_event_t *e) {
    scrScan_slider_hue_custom_value_changed();
}

void __attribute__((weak)) scrScan_slider_bright_custom_value_changed(void) {
}

static void scrScan_slider_bright_value_changed (lv_event_t *e) {
    scrScan_slider_bright_custom_value_changed();
}

static void scrScan_btn_next_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrScanFinish
        scrScanFinish_create(&ui_manager);
        // load scrScanFinish
        lv_scr_load_anim(scrScanFinish_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}

static void scrScan_btn_back_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create scrMain
        scrMain_create(&ui_manager);
        // load scrMain
        lv_scr_load_anim(scrMain_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_OUT, 200, 0, ui_manager.auto_del);
    }
}


void scrScan_create(ui_manager_t *ui)
{
    scrScan_t *scr = scrScan_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrScan_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->cont_top
    scr->cont_top = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_top, 0, 60);
    lv_obj_set_size(scr->cont_top, 1280, 80);
    lv_obj_set_scrollbar_mode(scr->cont_top, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_top
    lv_obj_set_style_pad_top(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_top, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->cont_top);
    lv_label_set_text(scr->label_13, "17  Jun  2026  14:30");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 900, 25);
    lv_obj_set_size(scr->label_13, 300, 30);

    // Set style of scr->label_13
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_13, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_13, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->Topic
    scr->Topic = lv_label_create(scr->cont_top);
    lv_label_set_text(scr->Topic, "SCANNING_IMAGE");
    lv_label_set_long_mode(scr->Topic, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->Topic, 390, 20);
    lv_obj_set_size(scr->Topic, 500, 40);

    // Set style of scr->Topic
    lv_obj_set_style_text_color(scr->Topic, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->Topic, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->Topic, fs_droidsansfallback_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_main
    scr->cont_main = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_main, 0, 140);
    lv_obj_set_size(scr->cont_main, 1280, 400);
    lv_obj_set_scrollbar_mode(scr->cont_main, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_main
    lv_obj_set_style_pad_top(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_main, lv_color_hex(0xf3f9fe), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_bird
    scr->image_bird = lv_img_create(scr->cont_main);
    lv_img_set_src(scr->image_bird, LVGL_IMAGE_PATH(birds_700x400.png));
    lv_img_set_pivot(scr->image_bird, 50, 50);
    lv_img_set_offset_x(scr->image_bird, 0);
    lv_img_set_offset_y(scr->image_bird, 0);
    lv_img_set_angle(scr->image_bird, 0);
    lv_obj_set_pos(scr->image_bird, 0, 0);

    // Init scr->container_33
    scr->container_33 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_33, 700, 0);
    lv_obj_set_size(scr->container_33, 300, 400);
    lv_obj_set_scrollbar_mode(scr->container_33, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_33
    lv_obj_set_style_pad_top(scr->container_33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_33, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->slider_hue
    scr->slider_hue = lv_slider_create(scr->container_33);
    lv_slider_set_mode(scr->slider_hue, LV_SLIDER_MODE_NORMAL);
    lv_slider_set_range(scr->slider_hue, 0, 100);
    lv_slider_set_value(scr->slider_hue, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_hue, 200, 80);
    lv_obj_set_size(scr->slider_hue, 30, 300);

    // Set style of scr->slider_hue
    lv_obj_set_style_bg_color(scr->slider_hue, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->slider_hue
    lv_obj_add_event_cb(scr->slider_hue, scrScan_slider_hue_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->slider_bright
    scr->slider_bright = lv_slider_create(scr->container_33);
    lv_slider_set_mode(scr->slider_bright, LV_SLIDER_MODE_NORMAL);
    lv_slider_set_range(scr->slider_bright, 0, 100);
    lv_slider_set_value(scr->slider_bright, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->slider_bright, 75, 80);
    lv_obj_set_size(scr->slider_bright, 30, 300);

    // Set style of scr->slider_bright
    lv_obj_set_style_bg_color(scr->slider_bright, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->slider_bright
    lv_obj_add_event_cb(scr->slider_bright, scrScan_slider_bright_value_changed, LV_EVENT_VALUE_CHANGED, NULL);

    // Init scr->img_bright
    scr->img_bright = lv_img_create(scr->container_33);
    lv_img_set_src(scr->img_bright, LVGL_IMAGE_PATH(bright_40x40.png));
    lv_img_set_pivot(scr->img_bright, 50, 50);
    lv_img_set_offset_x(scr->img_bright, 0);
    lv_img_set_offset_y(scr->img_bright, 0);
    lv_img_set_angle(scr->img_bright, 0);
    lv_obj_set_pos(scr->img_bright, 70, 20);

    // Init scr->img_hue
    scr->img_hue = lv_img_create(scr->container_33);
    lv_img_set_src(scr->img_hue, LVGL_IMAGE_PATH(hue_35x35.png));
    lv_img_set_pivot(scr->img_hue, 50, 50);
    lv_img_set_offset_x(scr->img_hue, 0);
    lv_img_set_offset_y(scr->img_hue, 0);
    lv_img_set_angle(scr->img_hue, 0);
    lv_obj_set_pos(scr->img_hue, 195, 20);

    // Init scr->btn_next
    scr->btn_next = lv_btn_create(scr->cont_main);
    lv_obj_t *btn_next_label = lv_label_create(scr->btn_next);
    lv_label_set_text(btn_next_label, "Next");
    lv_obj_align(btn_next_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_next, 1020, 320);
    lv_obj_set_size(scr->btn_next, 200, 60);

    // Set style of scr->btn_next
    lv_obj_set_style_shadow_width(scr->btn_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->btn_next, lv_color_hex(0x2ab620), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_next, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_next
    lv_obj_add_event_cb(scr->btn_next, scrScan_btn_next_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->btn_back
    scr->btn_back = lv_btn_create(scr->cont_main);
    lv_obj_t *btn_back_label = lv_label_create(scr->btn_back);
    lv_label_set_text(btn_back_label, "Back");
    lv_obj_align(btn_back_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->btn_back, 1020, 220);
    lv_obj_set_size(scr->btn_back, 200, 60);

    // Set style of scr->btn_back
    lv_obj_set_style_shadow_width(scr->btn_back, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->btn_back, lv_color_hex(0x2f3243), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->btn_back, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->btn_back
    lv_obj_add_event_cb(scr->btn_back, scrScan_btn_back_clicked, LV_EVENT_CLICKED, NULL);


}


