/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_montserratmedium_40;
lv_font_t *fs_montserratmedium_50;
lv_font_t *fs_montserratmedium_30;
lv_font_t *fs_montserratmedium_24;
lv_font_t *fs_montserratmedium_32;
lv_font_t *fs_droidsansfallback_36;
lv_font_t *fs_montserratmedium_20;
lv_font_t *fs_montserratmedium_26;
lv_font_t *fs_montserratmedium_42;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_montserratmedium_40 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 40);
    fs_montserratmedium_50 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 50);
    fs_montserratmedium_30 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 30);
    fs_montserratmedium_24 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 24);
    fs_montserratmedium_32 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 32);
    fs_droidsansfallback_36 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 36);
    fs_montserratmedium_20 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 20);
    fs_montserratmedium_26 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 26);
    fs_montserratmedium_42 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 42);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_montserratmedium_40) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_40");
    	return;
    }
    if (!fs_montserratmedium_50) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_50");
    	return;
    }
    if (!fs_montserratmedium_30) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_30");
    	return;
    }
    if (!fs_montserratmedium_24) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_24");
    	return;
    }
    if (!fs_montserratmedium_32) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_32");
    	return;
    }
    if (!fs_droidsansfallback_36) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_36");
    	return;
    }
    if (!fs_montserratmedium_20) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_20");
    	return;
    }
    if (!fs_montserratmedium_26) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_26");
    	return;
    }
    if (!fs_montserratmedium_42) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_42");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    scrMain_create(&ui_manager);
    lv_scr_load(scrMain_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
