/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *bg;
    lv_obj_t *top_cont;
    lv_obj_t *image_1;
    lv_obj_t *image_2;
    lv_obj_t *image_3;
    lv_obj_t *image_4;
    lv_obj_t *label_1;
    lv_obj_t *cont_main;
    lv_obj_t *cont_copy;
    lv_obj_t *image_19;
    lv_obj_t *label_4;
    lv_obj_t *cont_scan;
    lv_obj_t *image_20;
    lv_obj_t *label_5;
    lv_obj_t *cont_print;
    lv_obj_t *image_21;
    lv_obj_t *label_6;
    lv_obj_t *cont_setup;
    lv_obj_t *image_22;
    lv_obj_t *label_12;
    lv_obj_t *cont_label;
    lv_obj_t *label_3;
    lv_obj_t *cont_bar;
    lv_obj_t *bar_1;
    lv_obj_t *bar_2;
    lv_obj_t *bar_3;
    lv_obj_t *bar_4;
} scrMain_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *cont_top;
    lv_obj_t *label_13;
    lv_obj_t *Topic;
    lv_obj_t *cont_main;
    lv_obj_t *image_bird;
    lv_obj_t *container_33;
    lv_obj_t *slider_hue;
    lv_obj_t *slider_bright;
    lv_obj_t *img_bright;
    lv_obj_t *img_hue;
    lv_obj_t *btn_next;
    lv_obj_t *btn_back;
} scrScan_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *cont_top;
    lv_obj_t *label_16;
    lv_obj_t *cont_main;
    lv_obj_t *image_scan;
    lv_obj_t *cont_select;
    lv_obj_t *dropdown_1;
    lv_obj_t *dropdown_2;
    lv_obj_t *btn_next;
    lv_obj_t *btn_back;
    lv_obj_t *container_48;
    lv_obj_t *switch_1;
    lv_obj_t *switch_2;
    lv_obj_t *label_24;
    lv_obj_t *label_25;
    lv_obj_t *label_27;
    lv_obj_t *btn_minus;
    lv_obj_t *btn_plus;
    lv_obj_t *label_num;
} scrCopy_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *cont_top;
    lv_obj_t *Topic;
    lv_obj_t *button_4;
    lv_obj_t *cont_main;
    lv_obj_t *cont_item;
    lv_obj_t *cont_inter;
    lv_obj_t *image_45;
    lv_obj_t *image_44;
    lv_obj_t *label_22;
    lv_obj_t *cont_mobil;
    lv_obj_t *image_47;
    lv_obj_t *image_43;
    lv_obj_t *label_21;
    lv_obj_t *cont_usb;
    lv_obj_t *image_46;
    lv_obj_t *image_42;
    lv_obj_t *label_20;
    lv_obj_t *cont_bottom;
    lv_obj_t *label_23;
} scrPrint_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *cont_main;
    lv_obj_t *image_8;
    lv_obj_t *btn_back;
    lv_obj_t *label_4;
} scrSetup_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_49;
    lv_obj_t *arc_prog;
    lv_obj_t *label_30;
    lv_obj_t *label_prog;
} scrLoad_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_50;
    lv_obj_t *image_48;
    lv_obj_t *label_31;
    lv_obj_t *btn_continue;
} scrPrintFinish_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_1;
    lv_obj_t *image_1;
    lv_obj_t *label_1;
    lv_obj_t *button_1;
} scrScanFinish_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_2;
    lv_obj_t *image_2;
    lv_obj_t *image_4;
    lv_obj_t *btn_back;
    lv_obj_t *image_3;
    lv_obj_t *label_2;
} scrPrintMobile_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_3;
    lv_obj_t *btn_back;
    lv_obj_t *label_3;
    lv_obj_t *image_5;
    lv_obj_t *image_6;
    lv_obj_t *image_7;
} scrPrintfInter_t;

typedef struct {
    lv_obj_t *obj;
} screen_4_t;


typedef struct {
    bool auto_del;
    scrMain_t scrMain;
    scrScan_t scrScan;
    scrCopy_t scrCopy;
    scrPrint_t scrPrint;
    scrSetup_t scrSetup;
    scrLoad_t scrLoad;
    scrPrintFinish_t scrPrintFinish;
    scrScanFinish_t scrScanFinish;
    scrPrintMobile_t scrPrintMobile;
    scrPrintfInter_t scrPrintfInter;
    screen_4_t screen_4;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline scrMain_t *scrMain_get(ui_manager_t *ui)
{
    return &ui->scrMain;
}

static inline scrScan_t *scrScan_get(ui_manager_t *ui)
{
    return &ui->scrScan;
}

static inline scrCopy_t *scrCopy_get(ui_manager_t *ui)
{
    return &ui->scrCopy;
}

static inline scrPrint_t *scrPrint_get(ui_manager_t *ui)
{
    return &ui->scrPrint;
}

static inline scrSetup_t *scrSetup_get(ui_manager_t *ui)
{
    return &ui->scrSetup;
}

static inline scrLoad_t *scrLoad_get(ui_manager_t *ui)
{
    return &ui->scrLoad;
}

static inline scrPrintFinish_t *scrPrintFinish_get(ui_manager_t *ui)
{
    return &ui->scrPrintFinish;
}

static inline scrScanFinish_t *scrScanFinish_get(ui_manager_t *ui)
{
    return &ui->scrScanFinish;
}

static inline scrPrintMobile_t *scrPrintMobile_get(ui_manager_t *ui)
{
    return &ui->scrPrintMobile;
}

static inline scrPrintfInter_t *scrPrintfInter_get(ui_manager_t *ui)
{
    return &ui->scrPrintfInter;
}

static inline screen_4_t *screen_4_get(ui_manager_t *ui)
{
    return &ui->screen_4;
}


void scrMain_create(ui_manager_t *ui);
void scrScan_create(ui_manager_t *ui);
void scrCopy_create(ui_manager_t *ui);
void scrPrint_create(ui_manager_t *ui);
void scrSetup_create(ui_manager_t *ui);
void scrLoad_create(ui_manager_t *ui);
void scrPrintFinish_create(ui_manager_t *ui);
void scrScanFinish_create(ui_manager_t *ui);
void scrPrintMobile_create(ui_manager_t *ui);
void scrPrintfInter_create(ui_manager_t *ui);
void screen_4_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_montserratmedium_32;
extern lv_font_t *fs_droidsansfallback_36;
extern lv_font_t *fs_montserratmedium_24;
extern lv_font_t *fs_montserratmedium_20;
extern lv_font_t *fs_montserratmedium_26;
extern lv_font_t *fs_montserratmedium_50;
extern lv_font_t *fs_montserratmedium_30;
extern lv_font_t *fs_montserratmedium_42;
extern lv_font_t *fs_montserratmedium_40;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
