/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_1;
    lv_obj_t *arc_1;
    lv_obj_t *image_2;
    lv_obj_t *image_3;
    lv_obj_t *image_4;
    lv_obj_t *image_5;
    lv_obj_t *image_6;
    lv_obj_t *image_7;
    lv_obj_t *image_8;
    lv_obj_t *image_9;
    lv_obj_t *image_10;
    lv_obj_t *image_11;
    lv_obj_t *image_12;
    lv_obj_t *image_13;
    lv_obj_t *image_14;
    lv_obj_t *image_15;
    lv_obj_t *image_16;
    lv_obj_t *image_17;
    lv_obj_t *image_18;
    lv_obj_t *image_19;
    lv_obj_t *image_20;
    lv_obj_t *image_21;
    lv_obj_t *image_22;
    lv_obj_t *image_23;
    lv_obj_t *image_24;
    lv_obj_t *image_25;
    lv_obj_t *image_26;
    lv_obj_t *image_27;
    lv_obj_t *image_28;
    lv_obj_t *roller_1;
} dashboard_t;


typedef struct {
    bool auto_del;
    dashboard_t dashboard;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline dashboard_t *dashboard_get(ui_manager_t *ui)
{
    return &ui->dashboard;
}


void dashboard_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_droidsansfallback_24;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
