/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_16;
lv_font_t *fs_sourcehansanscn_bold_36;
lv_font_t *fs_sourcehansanscn_bold_24;

void ui_init(void)
{
    fs_montserratmedium_16 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 16);
    fs_sourcehansanscn_bold_36 = ui_font_init(LVGL_FONT_PATH(SourceHanSansCN-Bold.subset.ttf), 36);
    fs_sourcehansanscn_bold_24 = ui_font_init(LVGL_FONT_PATH(SourceHanSansCN-Bold.subset.ttf), 24);
    if (!fs_montserratmedium_16) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_16");
    	return;
    }
    if (!fs_sourcehansanscn_bold_36) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanscn_bold_36");
    	return;
    }
    if (!fs_sourcehansanscn_bold_24) {
    	LV_LOG_ERROR("Failed to init fs_sourcehansanscn_bold_24");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    main_screen_create(&ui_manager);
    lv_scr_load(main_screen_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
