/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *player;
    lv_obj_t *control_container;
    lv_obj_t *next_img;
    lv_obj_t *last_img;
    lv_obj_t *loop_img;
    lv_obj_t *play_img;
    lv_obj_t *zoom_img;
    lv_obj_t *file_name_label;
    lv_obj_t *author_label;
} main_screen_t;


typedef struct {
    bool auto_del;
    main_screen_t main_screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline main_screen_t *main_screen_get(ui_manager_t *ui)
{
    return &ui->main_screen;
}


void main_screen_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_16;
extern lv_font_t *fs_sourcehansanscn_bold_36;
extern lv_font_t *fs_sourcehansanscn_bold_24;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
