/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_custom_load_start(void) {
}

static void scrMain_load_start (lv_event_t *e) {
    screen_custom_load_start();
}


void scrMain_create(ui_manager_t *ui)
{
    scrMain_t *scr = scrMain_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrMain_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->cont_main
    scr->cont_main = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_main, 0, 0);
    lv_obj_set_size(scr->cont_main, 1080, 1080);
    lv_obj_set_scrollbar_mode(scr->cont_main, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_main
    lv_obj_set_style_border_width(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_main, 540, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->cont_main);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(图标1_60x30.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 302, 82);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->cont_main);
    lv_label_set_text(scr->label_1, "10:09");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 490, 32);
    lv_obj_set_size(scr->label_1, 100, 40);

    // Set style of scr->label_1
    lv_obj_set_style_text_color(scr->label_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_1, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->cont_main);
    lv_label_set_text(scr->label_2, "Health");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 465, 72);
    lv_obj_set_size(scr->label_2, 150, 40);

    // Set style of scr->label_2
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_2, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_1
    scr->container_1 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_1, 672, 142);
    lv_obj_set_size(scr->container_1, 300, 170);
    lv_obj_set_scrollbar_mode(scr->container_1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_1
    lv_obj_set_style_bg_grad_dir(scr->container_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_1, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_4
    scr->image_4 = lv_img_create(scr->container_1);
    lv_img_set_src(scr->image_4, LVGL_IMAGE_PATH(图标3_50x50.png));
    lv_img_set_pivot(scr->image_4, 50, 50);
    lv_img_set_offset_x(scr->image_4, 0);
    lv_img_set_offset_y(scr->image_4, 0);
    lv_img_set_angle(scr->image_4, 0);
    lv_obj_set_pos(scr->image_4, 11, 11);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_5, "Calories");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 81, 16);
    lv_obj_set_size(scr->label_5, 150, 40);

    // Set style of scr->label_5
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_5, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_15
    scr->label_15 = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_15, "kcal");
    lv_label_set_long_mode(scr->label_15, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_15, 201, 75);
    lv_obj_set_size(scr->label_15, 100, 40);

    // Set style of scr->label_15
    lv_obj_set_style_text_color(scr->label_15, lv_color_hex(0x929393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_15, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_calories
    scr->label_calories = lv_label_create(scr->container_1);
    lv_label_set_text(scr->label_calories, "650");
    lv_label_set_long_mode(scr->label_calories, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_calories, 80, 50);
    lv_obj_set_size(scr->label_calories, 150, 80);

    // Set style of scr->label_calories
    lv_obj_set_style_text_color(scr->label_calories, lv_color_hex(0xf91530), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_calories, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chart_calory
    scr->chart_calory = lv_chart_create(scr->container_1);
    lv_chart_set_type(scr->chart_calory, LV_CHART_TYPE_BAR);
    lv_chart_set_range(scr->chart_calory, LV_CHART_AXIS_PRIMARY_Y, 100, 650);
    lv_chart_set_point_count(scr->chart_calory, 10);

    lv_chart_series_t *chart_calory_series_0 = lv_chart_add_series(scr->chart_calory, lv_color_hex(0xf91530), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 500);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 420);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 246);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 610);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 290);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 411);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 396);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 361);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 650);
    lv_chart_set_next_value(scr->chart_calory, chart_calory_series_0, 480);

    lv_obj_set_pos(scr->chart_calory, 25, 120);
    lv_obj_set_size(scr->chart_calory, 250, 50);

    // Set style of scr->chart_calory
    lv_obj_set_style_line_width(scr->chart_calory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->chart_calory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->chart_calory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_2
    scr->container_2 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_2, 672, 322);
    lv_obj_set_size(scr->container_2, 370, 180);
    lv_obj_set_scrollbar_mode(scr->container_2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_2
    lv_obj_set_style_bg_grad_dir(scr->container_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_2, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_5
    scr->image_5 = lv_img_create(scr->container_2);
    lv_img_set_src(scr->image_5, LVGL_IMAGE_PATH(图标4_50x50.png));
    lv_img_set_pivot(scr->image_5, 50, 50);
    lv_img_set_offset_x(scr->image_5, 0);
    lv_img_set_offset_y(scr->image_5, 0);
    lv_img_set_angle(scr->image_5, 0);
    lv_obj_set_pos(scr->image_5, 11, 11);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->container_2);
    lv_label_set_text(scr->label_6, "Steps");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 81, 16);
    lv_obj_set_size(scr->label_6, 150, 40);

    // Set style of scr->label_6
    lv_obj_set_style_text_color(scr->label_6, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_6, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_steps
    scr->label_steps = lv_label_create(scr->container_2);
    lv_label_set_text(scr->label_steps, "8426");
    lv_label_set_long_mode(scr->label_steps, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_steps, 81, 51);
    lv_obj_set_size(scr->label_steps, 170, 80);

    // Set style of scr->label_steps
    lv_obj_set_style_text_color(scr->label_steps, lv_color_hex(0x69b003), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_steps, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_19
    scr->label_19 = lv_label_create(scr->container_2);
    lv_label_set_text(scr->label_19, "/10000");
    lv_label_set_long_mode(scr->label_19, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_19, 261, 76);
    lv_obj_set_size(scr->label_19, 120, 40);

    // Set style of scr->label_19
    lv_obj_set_style_text_color(scr->label_19, lv_color_hex(0x929393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_19, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chart_2
    scr->chart_2 = lv_chart_create(scr->container_2);
    lv_chart_set_type(scr->chart_2, LV_CHART_TYPE_BAR);
    lv_chart_set_range(scr->chart_2, LV_CHART_AXIS_PRIMARY_Y, 0, 10000);
    lv_chart_set_point_count(scr->chart_2, 18);

    lv_chart_series_t *chart_2_series_0 = lv_chart_add_series(scr->chart_2, lv_color_hex(0x76c004), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 7192);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 8426);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 9146);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 8864);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 7813);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 7545);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 9607);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 6956);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 7812);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 9814);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 8247);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 8334);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 6966);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 6867);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 9107);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 5769);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 8711);
    lv_chart_set_next_value(scr->chart_2, chart_2_series_0, 7449);

    lv_obj_set_pos(scr->chart_2, 20, 111);
    lv_obj_set_size(scr->chart_2, 330, 60);

    // Set style of scr->chart_2
    lv_obj_set_style_line_width(scr->chart_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->chart_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->chart_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_3
    scr->container_3 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_3, 672, 512);
    lv_obj_set_size(scr->container_3, 370, 170);
    lv_obj_set_scrollbar_mode(scr->container_3, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_3
    lv_obj_set_style_bg_grad_dir(scr->container_3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_3, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_6
    scr->image_6 = lv_img_create(scr->container_3);
    lv_img_set_src(scr->image_6, LVGL_IMAGE_PATH(图标5_50x50.png));
    lv_img_set_pivot(scr->image_6, 50, 50);
    lv_img_set_offset_x(scr->image_6, 0);
    lv_img_set_offset_y(scr->image_6, 0);
    lv_img_set_angle(scr->image_6, 0);
    lv_obj_set_pos(scr->image_6, 11, 11);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_13, "Active Time");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 81, 16);
    lv_obj_set_size(scr->label_13, 200, 40);

    // Set style of scr->label_13
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_13, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_min
    scr->label_min = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_min, "62");
    lv_label_set_long_mode(scr->label_min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_min, 81, 51);
    lv_obj_set_size(scr->label_min, 100, 80);

    // Set style of scr->label_min
    lv_obj_set_style_text_color(scr->label_min, lv_color_hex(0x7043da), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_min, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_21
    scr->label_21 = lv_label_create(scr->container_3);
    lv_label_set_text(scr->label_21, "min");
    lv_label_set_long_mode(scr->label_21, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_21, 191, 76);
    lv_obj_set_size(scr->label_21, 120, 40);

    // Set style of scr->label_21
    lv_obj_set_style_text_color(scr->label_21, lv_color_hex(0x929393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_21, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->chart_3
    scr->chart_3 = lv_chart_create(scr->container_3);
    lv_chart_set_type(scr->chart_3, LV_CHART_TYPE_BAR);
    lv_chart_set_range(scr->chart_3, LV_CHART_AXIS_PRIMARY_Y, 0, 100);
    lv_chart_set_point_count(scr->chart_3, 22);

    lv_chart_series_t *chart_3_series_0 = lv_chart_add_series(scr->chart_3, lv_color_hex(0x7043da), LV_CHART_AXIS_PRIMARY_Y);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 71);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 82);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 61);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 59);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 78);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 65);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 63);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 62);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 47);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 80);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 61);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 74);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 55);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 43);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 37);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 74);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 91);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 58);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 66);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 67);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 70);
    lv_chart_set_next_value(scr->chart_3, chart_3_series_0, 61);

    lv_obj_set_pos(scr->chart_3, 20, 111);
    lv_obj_set_size(scr->chart_3, 330, 50);

    // Set style of scr->chart_3
    lv_obj_set_style_line_width(scr->chart_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->chart_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->chart_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_4
    scr->container_4 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_4, 65, 692);
    lv_obj_set_size(scr->container_4, 950, 120);
    lv_obj_set_scrollbar_mode(scr->container_4, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_4
    lv_obj_set_style_bg_grad_stop(scr->container_4, 106, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(scr->container_4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_4, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_7
    scr->image_7 = lv_img_create(scr->container_4);
    lv_img_set_src(scr->image_7, LVGL_IMAGE_PATH(图标6_60x60.png));
    lv_img_set_pivot(scr->image_7, 50, 50);
    lv_img_set_offset_x(scr->image_7, 0);
    lv_img_set_offset_y(scr->image_7, 0);
    lv_img_set_angle(scr->image_7, 0);
    lv_obj_set_pos(scr->image_7, 21, 21);

    // Init scr->label_14
    scr->label_14 = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_14, "Heart Rate");
    lv_label_set_long_mode(scr->label_14, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_14, 101, 21);
    lv_obj_set_size(scr->label_14, 200, 40);

    // Set style of scr->label_14
    lv_obj_set_style_text_color(scr->label_14, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_14, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_bpm
    scr->label_bpm = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_bpm, "89");
    lv_label_set_long_mode(scr->label_bpm, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_bpm, 101, 56);
    lv_obj_set_size(scr->label_bpm, 100, 60);

    // Set style of scr->label_bpm
    lv_obj_set_style_text_color(scr->label_bpm, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_bpm, fs_montserratmedium_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_23
    scr->label_23 = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_23, "BPM");
    lv_label_set_long_mode(scr->label_23, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_23, 181, 71);
    lv_obj_set_size(scr->label_23, 100, 40);

    // Set style of scr->label_23
    lv_obj_set_style_text_color(scr->label_23, lv_color_hex(0xf61530), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_23, fs_montserratmedium_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_8
    scr->image_8 = lv_img_create(scr->container_4);
    lv_img_set_src(scr->image_8, LVGL_IMAGE_PATH(bpm_450x80.png));
    lv_img_set_pivot(scr->image_8, 50, 50);
    lv_img_set_offset_x(scr->image_8, 0);
    lv_img_set_offset_y(scr->image_8, 0);
    lv_img_set_angle(scr->image_8, 0);
    lv_obj_set_pos(scr->image_8, 301, 20);

    // Set style of scr->image_8
    lv_obj_set_style_img_recolor(scr->image_8, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_opa(scr->image_8, 187, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_7, "Max");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 781, 21);
    lv_obj_set_size(scr->label_7, 100, 40);

    // Set style of scr->label_7
    lv_obj_set_style_text_color(scr->label_7, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_7, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_8, "Min");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 781, 71);
    lv_obj_set_size(scr->label_8, 100, 40);

    // Set style of scr->label_8
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_9, "128");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 861, 21);
    lv_obj_set_size(scr->label_9, 80, 40);

    // Set style of scr->label_9
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0xf61530), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_9, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->container_4);
    lv_label_set_text(scr->label_10, "56");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 861, 71);
    lv_obj_set_size(scr->label_10, 80, 40);

    // Set style of scr->label_10
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xf61530), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_10, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_5
    scr->container_5 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_5, 450, 832);
    lv_obj_set_size(scr->container_5, 180, 180);
    lv_obj_set_scrollbar_mode(scr->container_5, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_5
    lv_obj_set_style_bg_grad_dir(scr->container_5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_5, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_10
    scr->image_10 = lv_img_create(scr->container_5);
    lv_img_set_src(scr->image_10, LVGL_IMAGE_PATH(图标8_70x70.png));
    lv_img_set_pivot(scr->image_10, 50, 50);
    lv_img_set_offset_x(scr->image_10, 0);
    lv_img_set_offset_y(scr->image_10, 0);
    lv_img_set_angle(scr->image_10, 0);
    lv_obj_set_pos(scr->image_10, 5, 40);

    // Init scr->label_brpm
    scr->label_brpm = lv_label_create(scr->container_5);
    lv_label_set_text(scr->label_brpm, "16");
    lv_label_set_long_mode(scr->label_brpm, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_brpm, 60, 40);
    lv_obj_set_size(scr->label_brpm, 100, 40);

    // Set style of scr->label_brpm
    lv_obj_set_style_text_color(scr->label_brpm, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_brpm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_brpm, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_24
    scr->label_24 = lv_label_create(scr->container_5);
    lv_label_set_text(scr->label_24, "brpm");
    lv_label_set_long_mode(scr->label_24, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_24, 70, 85);
    lv_obj_set_size(scr->label_24, 100, 40);

    // Set style of scr->label_24
    lv_obj_set_style_text_color(scr->label_24, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_24, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_brpm
    scr->arc_brpm = lv_arc_create(scr->container_5);
    lv_arc_set_mode(scr->arc_brpm, LV_ARC_MODE_REVERSE);
    lv_arc_set_range(scr->arc_brpm, 0, 200);
    lv_arc_set_value(scr->arc_brpm, 50);
    lv_arc_set_bg_angles(scr->arc_brpm, 30, 150);
    lv_arc_set_angles(scr->arc_brpm, 120, 150);
    lv_arc_set_rotation(scr->arc_brpm, 0);
    lv_arc_set_change_rate(scr->arc_brpm, 720);
    lv_obj_set_pos(scr->arc_brpm, 0, 0);
    lv_obj_set_size(scr->arc_brpm, 180, 180);

    // Set style of scr->arc_brpm
    lv_obj_set_style_arc_opa(scr->arc_brpm, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_brpm, lv_color_hex(0x04d9e7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_brpm, lv_color_hex(0x04d9e7), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_brpm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->container_6
    scr->container_6 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_6, 658, 832);
    lv_obj_set_size(scr->container_6, 180, 180);
    lv_obj_set_scrollbar_mode(scr->container_6, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_6
    lv_obj_set_style_bg_grad_dir(scr->container_6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_6, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_11
    scr->image_11 = lv_img_create(scr->container_6);
    lv_img_set_src(scr->image_11, LVGL_IMAGE_PATH(图标9_70x70.png));
    lv_img_set_pivot(scr->image_11, 50, 50);
    lv_img_set_offset_x(scr->image_11, 0);
    lv_img_set_offset_y(scr->image_11, 0);
    lv_img_set_angle(scr->image_11, 0);
    lv_obj_set_pos(scr->image_11, 3, 45);

    // Init scr->label_slp_hour
    scr->label_slp_hour = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_slp_hour, "7");
    lv_label_set_long_mode(scr->label_slp_hour, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_slp_hour, 70, 45);
    lv_obj_set_size(scr->label_slp_hour, 30, 40);

    // Set style of scr->label_slp_hour
    lv_obj_set_style_text_color(scr->label_slp_hour, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_slp_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_slp_hour, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_slp_min
    scr->label_slp_min = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_slp_min, "30");
    lv_label_set_long_mode(scr->label_slp_min, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_slp_min, 105, 45);
    lv_obj_set_size(scr->label_slp_min, 50, 40);

    // Set style of scr->label_slp_min
    lv_obj_set_style_text_color(scr->label_slp_min, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_slp_min, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_slp_min, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_27
    scr->label_27 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_27, "h");
    lv_label_set_long_mode(scr->label_27, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_27, 90, 55);
    lv_obj_set_size(scr->label_27, 25, 25);

    // Set style of scr->label_27
    lv_obj_set_style_text_color(scr->label_27, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_27, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_27, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_28
    scr->label_28 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_28, "m");
    lv_label_set_long_mode(scr->label_28, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_28, 148, 55);
    lv_obj_set_size(scr->label_28, 25, 25);

    // Set style of scr->label_28
    lv_obj_set_style_text_color(scr->label_28, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_28, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_28, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_29
    scr->label_29 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_29, "sleep");
    lv_label_set_long_mode(scr->label_29, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_29, 70, 85);
    lv_obj_set_size(scr->label_29, 100, 40);

    // Set style of scr->label_29
    lv_obj_set_style_text_color(scr->label_29, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_29, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_29, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_sleep
    scr->arc_sleep = lv_arc_create(scr->container_6);
    lv_arc_set_mode(scr->arc_sleep, LV_ARC_MODE_REVERSE);
    lv_arc_set_range(scr->arc_sleep, 0, 200);
    lv_arc_set_value(scr->arc_sleep, 160);
    lv_arc_set_bg_angles(scr->arc_sleep, 30, 150);
    lv_arc_set_angles(scr->arc_sleep, 54, 150);
    lv_arc_set_rotation(scr->arc_sleep, 0);
    lv_arc_set_change_rate(scr->arc_sleep, 720);
    lv_obj_set_pos(scr->arc_sleep, 0, 0);
    lv_obj_set_size(scr->arc_sleep, 180, 180);

    // Set style of scr->arc_sleep
    lv_obj_set_style_arc_opa(scr->arc_sleep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_sleep, lv_color_hex(0x6147e3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_sleep, lv_color_hex(0x6147e3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_sleep, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->container_7
    scr->container_7 = lv_obj_create(scr->cont_main);
    lv_obj_set_pos(scr->container_7, 242, 832);
    lv_obj_set_size(scr->container_7, 180, 180);
    lv_obj_set_scrollbar_mode(scr->container_7, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_7
    lv_obj_set_style_bg_grad_dir(scr->container_7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_7, lv_color_hex(0x191a1e), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_9
    scr->image_9 = lv_img_create(scr->container_7);
    lv_img_set_src(scr->image_9, LVGL_IMAGE_PATH(图标7_70x70.png));
    lv_img_set_pivot(scr->image_9, 50, 50);
    lv_img_set_offset_x(scr->image_9, 0);
    lv_img_set_offset_y(scr->image_9, 0);
    lv_img_set_angle(scr->image_9, 0);
    lv_obj_set_pos(scr->image_9, 5, 40);

    // Init scr->label_spo2
    scr->label_spo2 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->label_spo2, "98%");
    lv_label_set_long_mode(scr->label_spo2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_spo2, 60, 40);
    lv_obj_set_size(scr->label_spo2, 120, 60);

    // Set style of scr->label_spo2
    lv_obj_set_style_text_color(scr->label_spo2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_spo2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_spo2, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->label_12, "SpO");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 60, 85);
    lv_obj_set_size(scr->label_12, 100, 40);

    // Set style of scr->label_12
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_12, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_18
    scr->label_18 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->label_18, "2");
    lv_label_set_long_mode(scr->label_18, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_18, 140, 100);
    lv_obj_set_size(scr->label_18, 20, 20);

    // Set style of scr->label_18
    lv_obj_set_style_text_color(scr->label_18, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_18, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_spo2
    scr->arc_spo2 = lv_arc_create(scr->container_7);
    lv_arc_set_mode(scr->arc_spo2, LV_ARC_MODE_REVERSE);
    lv_arc_set_range(scr->arc_spo2, 0, 200);
    lv_arc_set_value(scr->arc_spo2, 60);
    lv_arc_set_bg_angles(scr->arc_spo2, 30, 150);
    lv_arc_set_angles(scr->arc_spo2, 114, 150);
    lv_arc_set_rotation(scr->arc_spo2, 0);
    lv_arc_set_change_rate(scr->arc_spo2, 720);
    lv_obj_set_pos(scr->arc_spo2, 0, 0);
    lv_obj_set_size(scr->arc_spo2, 180, 180);

    // Set style of scr->arc_spo2
    lv_obj_set_style_arc_opa(scr->arc_spo2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_spo2, lv_color_hex(0x1fa6f4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_spo2, lv_color_hex(0x1fa6f4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_spo2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(图标2_60x30.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 700, 80);

    // Init scr->cont_arc
    scr->cont_arc = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_arc, 60, 150);
    lv_obj_set_size(scr->cont_arc, 600, 600);
    lv_obj_set_scrollbar_mode(scr->cont_arc, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_arc
    lv_obj_set_style_border_width(scr->cont_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_arc, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cont_arc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->cont_arc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_red
    scr->arc_red = lv_arc_create(scr->cont_arc);
    lv_arc_set_mode(scr->arc_red, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_red, 0, 600);
    lv_arc_set_value(scr->arc_red, 5);
    lv_arc_set_bg_angles(scr->arc_red, 135, 45);
    lv_arc_set_angles(scr->arc_red, 135, 137);
    lv_arc_set_rotation(scr->arc_red, 0);
    lv_arc_set_change_rate(scr->arc_red, 720);
    lv_obj_set_pos(scr->arc_red, 0, 0);
    lv_obj_set_size(scr->arc_red, 600, 600);

    // Set style of scr->arc_red
    lv_obj_set_style_arc_opa(scr->arc_red, 78, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_red, lv_color_hex(0xf31d38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_red, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_red, lv_color_hex(0xfc203d), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_red, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->arc_red, LVGL_IMAGE_PATH(icon1.png), LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->arc_green
    scr->arc_green = lv_arc_create(scr->cont_arc);
    lv_arc_set_mode(scr->arc_green, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_green, 0, 1000);
    lv_arc_set_value(scr->arc_green, 1);
    lv_arc_set_bg_angles(scr->arc_green, 135, 45);
    lv_arc_set_angles(scr->arc_green, 135, 135);
    lv_arc_set_rotation(scr->arc_green, 0);
    lv_arc_set_change_rate(scr->arc_green, 720);
    lv_obj_set_pos(scr->arc_green, 75, 75);
    lv_obj_set_size(scr->arc_green, 450, 450);

    // Set style of scr->arc_green
    lv_obj_set_style_arc_opa(scr->arc_green, 78, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_green, lv_color_hex(0x73bd03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_green, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_green, lv_color_hex(0x76c004), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_green, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->arc_green, LVGL_IMAGE_PATH(icon2.png), LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->arc_purple
    scr->arc_purple = lv_arc_create(scr->cont_arc);
    lv_arc_set_mode(scr->arc_purple, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_purple, 0, 200);
    lv_arc_set_value(scr->arc_purple, 2);
    lv_arc_set_bg_angles(scr->arc_purple, 135, 45);
    lv_arc_set_angles(scr->arc_purple, 135, 137);
    lv_arc_set_rotation(scr->arc_purple, 0);
    lv_arc_set_change_rate(scr->arc_purple, 720);
    lv_obj_set_pos(scr->arc_purple, 150, 150);
    lv_obj_set_size(scr->arc_purple, 300, 300);

    // Set style of scr->arc_purple
    lv_obj_set_style_arc_opa(scr->arc_purple, 78, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_purple, lv_color_hex(0x7043da), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_purple, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_purple, lv_color_hex(0x7043da), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_purple, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->arc_purple, LVGL_IMAGE_PATH(icon3.png), LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->label_mainstep
    scr->label_mainstep = lv_label_create(scr->cont_arc);
    lv_label_set_text(scr->label_mainstep, "8426");
    lv_label_set_long_mode(scr->label_mainstep, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_mainstep, 210, 292);
    lv_obj_set_size(scr->label_mainstep, 180, 60);

    // Set style of scr->label_mainstep
    lv_obj_set_style_text_color(scr->label_mainstep, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_mainstep, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_mainstep, fs_montserratmedium_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->cont_arc);
    lv_label_set_text(scr->label_3, "Steps");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 250, 251);
    lv_obj_set_size(scr->label_3, 100, 40);

    // Set style of scr->label_3
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_3, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_30
    scr->label_30 = lv_label_create(scr->cont_arc);
    lv_label_set_text(scr->label_30, "/10000");
    lv_label_set_long_mode(scr->label_30, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_30, 240, 370);
    lv_obj_set_size(scr->label_30, 120, 40);

    // Set style of scr->label_30
    lv_obj_set_style_text_color(scr->label_30, lv_color_hex(0x929393), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_30, fs_montserratmedium_30, LV_PART_MAIN | LV_STATE_DEFAULT);


}


