/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_30;
lv_font_t *fs_montserratmedium_40;
lv_font_t *fs_montserratmedium_60;
lv_font_t *fs_montserratmedium_50;
lv_font_t *fs_montserratmedium_35;
lv_font_t *fs_montserratmedium_20;

void ui_init(void)
{
    fs_montserratmedium_30 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 30);
    fs_montserratmedium_40 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 40);
    fs_montserratmedium_60 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 60);
    fs_montserratmedium_50 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 50);
    fs_montserratmedium_35 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 35);
    fs_montserratmedium_20 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 20);
    if (!fs_montserratmedium_30) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_30");
    	return;
    }
    if (!fs_montserratmedium_40) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_40");
    	return;
    }
    if (!fs_montserratmedium_60) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_60");
    	return;
    }
    if (!fs_montserratmedium_50) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_50");
    	return;
    }
    if (!fs_montserratmedium_35) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_35");
    	return;
    }
    if (!fs_montserratmedium_20) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_20");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    scrMain_create(&ui_manager);
    lv_scr_load(scrMain_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
