/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) scrRace_custom_load_start(void) {
}
void __attribute__((weak)) scrRace_custom_unloaded(void) {
}

static void scrRace_load_start (lv_event_t *e) {
    scrRace_custom_load_start();
}

static void scrRace_unloaded (lv_event_t *e) {
    scrRace_custom_unloaded();
}


void scrRace_create(ui_manager_t *ui)
{
    scrRace_t *scr = scrRace_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, scrRace_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, scrRace_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);

    // Init scr->player_move
    scr->player_move = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->player_move, LVGL_VIDEO_PATH(car_move.png));
    lv_aic_player_set_auto_restart(scr->player_move, true);
    lv_aic_player_set_cmd(scr->player_move, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->player_move, 301, 420);
    lv_obj_set_size(scr->player_move, 422, 211);

    // Init scr->img_gradient2
    scr->img_gradient2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->img_gradient2, LVGL_IMAGE_PATH(screen4/gradient2.png));
    lv_img_set_pivot(scr->img_gradient2, 50, 50);
    lv_img_set_offset_x(scr->img_gradient2, 0);
    lv_img_set_offset_y(scr->img_gradient2, 0);
    lv_img_set_angle(scr->img_gradient2, 0);
    lv_obj_set_pos(scr->img_gradient2, 662, 318);

    // Init scr->img_gradient1
    scr->img_gradient1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->img_gradient1, LVGL_IMAGE_PATH(screen4/gradient1.png));
    lv_img_set_pivot(scr->img_gradient1, 50, 50);
    lv_img_set_offset_x(scr->img_gradient1, 0);
    lv_img_set_offset_y(scr->img_gradient1, 0);
    lv_img_set_angle(scr->img_gradient1, 0);
    lv_obj_set_pos(scr->img_gradient1, 26, 318);

    // Init scr->cont_cover2
    scr->cont_cover2 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_cover2, 800, 290);
    lv_obj_set_size(scr->cont_cover2, 200, 200);
    lv_obj_set_scrollbar_mode(scr->cont_cover2, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_cover2
    lv_obj_set_style_bg_color(scr->cont_cover2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_cover2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_cover2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_cover2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_cover2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_cover2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_cover2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_cover1
    scr->cont_cover1 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_cover1, 30, 290);
    lv_obj_set_size(scr->cont_cover1, 200, 200);
    lv_obj_set_scrollbar_mode(scr->cont_cover1, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_cover1
    lv_obj_set_style_bg_color(scr->cont_cover1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_cover1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_cover1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_cover1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_cover1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_cover1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_cover1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_right
    scr->cont_right = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_right, 570, 226);
    lv_obj_set_size(scr->cont_right, 428, 315);
    lv_obj_set_scrollbar_mode(scr->cont_right, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_right
    lv_obj_set_style_bg_color(scr->cont_right, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_25
    scr->image_25 = lv_img_create(scr->cont_right);
    lv_img_set_src(scr->image_25, LVGL_IMAGE_PATH(screen4/screen4_right_428x315.png));
    lv_img_set_pivot(scr->image_25, 50, 50);
    lv_img_set_offset_x(scr->image_25, 0);
    lv_img_set_offset_y(scr->image_25, 0);
    lv_img_set_angle(scr->image_25, 0);
    lv_obj_set_pos(scr->image_25, 0, 0);

    // Init scr->label_rpm
    scr->label_rpm = lv_label_create(scr->cont_right);
    lv_label_set_text(scr->label_rpm, "10.0");
    lv_label_set_long_mode(scr->label_rpm, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_rpm, 150, 100);
    lv_obj_set_size(scr->label_rpm, 146, 80);

    // Set style of scr->label_rpm
    lv_obj_set_style_text_color(scr->label_rpm, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_rpm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_rpm, fs_montserratmedium_70, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_14
    scr->label_14 = lv_label_create(scr->cont_right);
    lv_label_set_text(scr->label_14, "x1000rpm");
    lv_label_set_long_mode(scr->label_14, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_14, 170, 190);
    lv_obj_set_size(scr->label_14, 120, 30);

    // Set style of scr->label_14
    lv_obj_set_style_text_color(scr->label_14, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_14, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cont_left
    scr->cont_left = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_left, 30, 226);
    lv_obj_set_size(scr->cont_left, 428, 315);
    lv_obj_set_scrollbar_mode(scr->cont_left, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_left
    lv_obj_set_style_bg_color(scr->cont_left, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_24
    scr->image_24 = lv_img_create(scr->cont_left);
    lv_img_set_src(scr->image_24, LVGL_IMAGE_PATH(screen4/screen4_left_428x315.png));
    lv_img_set_pivot(scr->image_24, 50, 50);
    lv_img_set_offset_x(scr->image_24, 0);
    lv_img_set_offset_y(scr->image_24, 0);
    lv_img_set_angle(scr->image_24, 0);
    lv_obj_set_pos(scr->image_24, 0, 0);

    // Init scr->label_speed
    scr->label_speed = lv_label_create(scr->cont_left);
    lv_label_set_text(scr->label_speed, "200");
    lv_label_set_long_mode(scr->label_speed, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_speed, 100, 100);
    lv_obj_set_size(scr->label_speed, 200, 100);

    // Set style of scr->label_speed
    lv_obj_set_style_text_color(scr->label_speed, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_speed, fs_montserratmedium_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->cont_left);
    lv_label_set_text(scr->label_12, "KM/H");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 145, 200);
    lv_obj_set_size(scr->label_12, 100, 30);

    // Set style of scr->label_12
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_12, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->img_bottom
    scr->img_bottom = lv_img_create(scr->obj);
    lv_img_set_src(scr->img_bottom, LVGL_IMAGE_PATH(screen2/down.png));
    lv_img_set_pivot(scr->img_bottom, 50, 50);
    lv_img_set_offset_x(scr->img_bottom, 0);
    lv_img_set_offset_y(scr->img_bottom, 0);
    lv_img_set_angle(scr->img_bottom, 0);
    lv_obj_set_pos(scr->img_bottom, 119, 657);

    // Init scr->img_mid
    scr->img_mid = lv_img_create(scr->obj);
    lv_img_set_src(scr->img_mid, LVGL_IMAGE_PATH(screen2/screen2_mid_400x216.png));
    lv_img_set_pivot(scr->img_mid, 50, 50);
    lv_img_set_offset_x(scr->img_mid, 0);
    lv_img_set_offset_y(scr->img_mid, 0);
    lv_img_set_angle(scr->img_mid, 0);
    lv_obj_set_pos(scr->img_mid, 312, 200);

    // Set style of scr->img_mid
    lv_obj_set_style_img_opa(scr->img_mid, 104, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->img_top
    scr->img_top = lv_img_create(scr->obj);
    lv_img_set_src(scr->img_top, LVGL_IMAGE_PATH(screen4/screen4_up.png));
    lv_img_set_pivot(scr->img_top, 50, 50);
    lv_img_set_offset_x(scr->img_top, 0);
    lv_img_set_offset_y(scr->img_top, 0);
    lv_img_set_angle(scr->img_top, 0);
    lv_obj_set_pos(scr->img_top, 161, 0);

    // Init scr->label_10
    scr->label_10 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_10, "19:20");
    lv_label_set_long_mode(scr->label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_10, 439, 5);
    lv_obj_set_size(scr->label_10, 146, 50);

    // Set style of scr->label_10
    lv_obj_set_style_text_color(scr->label_10, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_10, fs_montserratmedium_35, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_30
    scr->image_30 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_30, LVGL_IMAGE_PATH(screen3/cloudy_img.png));
    lv_img_set_pivot(scr->image_30, 50, 50);
    lv_img_set_offset_x(scr->image_30, 0);
    lv_img_set_offset_y(scr->image_30, 0);
    lv_img_set_angle(scr->image_30, 0);
    lv_obj_set_pos(scr->image_30, 630, 8);

    // Init scr->cont_dir
    scr->cont_dir = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->cont_dir, 312, 100);
    lv_obj_set_size(scr->cont_dir, 400, 200);
    lv_obj_set_scrollbar_mode(scr->cont_dir, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->cont_dir
    lv_obj_set_style_bg_color(scr->cont_dir, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->cont_dir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->img_dir
    scr->img_dir = lv_img_create(scr->cont_dir);
    lv_img_set_src(scr->img_dir, LVGL_IMAGE_PATH(turn/straight2.png));
    lv_img_set_pivot(scr->img_dir, 50, 50);
    lv_img_set_offset_x(scr->img_dir, 0);
    lv_img_set_offset_y(scr->img_dir, 0);
    lv_img_set_angle(scr->img_dir, 0);
    lv_obj_set_pos(scr->img_dir, 300, 23);

    // Init scr->label_dir
    scr->label_dir = lv_label_create(scr->cont_dir);
    lv_label_set_text(scr->label_dir, "直行进入珠海大桥");
    lv_label_set_long_mode(scr->label_dir, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_dir, 50, 100);
    lv_obj_set_size(scr->label_dir, 300, 50);

    // Set style of scr->label_dir
    lv_obj_set_style_text_color(scr->label_dir, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_dir, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_dir, fs_droidsansfallback_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_dist
    scr->label_dist = lv_label_create(scr->cont_dir);
    lv_label_set_text(scr->label_dist, "500m");
    lv_label_set_long_mode(scr->label_dist, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_dist, 100, 27);
    lv_obj_set_size(scr->label_dist, 200, 50);

    // Set style of scr->label_dist
    lv_obj_set_style_text_color(scr->label_dist, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_dist, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_dist, fs_droidsansfallback_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->img_light
    scr->img_light = lv_img_create(scr->cont_dir);
    lv_img_set_src(scr->img_light, LVGL_IMAGE_PATH(screen2/light_50x50.png));
    lv_img_set_pivot(scr->img_light, 50, 50);
    lv_img_set_offset_x(scr->img_light, 0);
    lv_img_set_offset_y(scr->img_light, 0);
    lv_img_set_angle(scr->img_light, 0);
    lv_obj_set_pos(scr->img_light, 50, 35);

    // Set style of scr->img_light
    lv_obj_set_style_img_recolor_opa(scr->img_light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(scr->img_light, lv_color_hex(0xffaa00), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_33
    scr->image_33 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_33, LVGL_IMAGE_PATH(turn/right.png));
    lv_img_set_pivot(scr->image_33, 50, 50);
    lv_img_set_offset_x(scr->image_33, 0);
    lv_img_set_offset_y(scr->image_33, 0);
    lv_img_set_angle(scr->image_33, 0);
    lv_obj_set_pos(scr->image_33, 1134, 146);
    lv_obj_add_flag(scr->image_33, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_34
    scr->image_34 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_34, LVGL_IMAGE_PATH(turn/left.png));
    lv_img_set_pivot(scr->image_34, 50, 50);
    lv_img_set_offset_x(scr->image_34, 0);
    lv_img_set_offset_y(scr->image_34, 0);
    lv_img_set_angle(scr->image_34, 0);
    lv_obj_set_pos(scr->image_34, 1132, 272);
    lv_obj_add_flag(scr->image_34, LV_OBJ_FLAG_HIDDEN);

    // Init scr->img_gear
    scr->img_gear = lv_img_create(scr->obj);
    lv_img_set_src(scr->img_gear, LVGL_IMAGE_PATH(gear/D.png));
    lv_img_set_pivot(scr->img_gear, 50, 50);
    lv_img_set_offset_x(scr->img_gear, 0);
    lv_img_set_offset_y(scr->img_gear, 0);
    lv_img_set_angle(scr->img_gear, 0);
    lv_obj_set_pos(scr->img_gear, 362, 700);


}


