/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_50;
lv_font_t *fs_montserratmedium_70;
lv_font_t *fs_montserratmedium_20;
lv_font_t *fs_droidsansfallback_50;
lv_font_t *fs_droidsansfallback_30;
lv_font_t *fs_montserratmedium_35;
lv_font_t *fs_montserratmedium_80;

void ui_init(void)
{
    fs_montserratmedium_50 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 50);
    fs_montserratmedium_70 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 70);
    fs_montserratmedium_20 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 20);
    fs_droidsansfallback_50 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 50);
    fs_droidsansfallback_30 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 30);
    fs_montserratmedium_35 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 35);
    fs_montserratmedium_80 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 80);
    if (!fs_montserratmedium_50) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_50");
    	return;
    }
    if (!fs_montserratmedium_70) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_70");
    	return;
    }
    if (!fs_montserratmedium_20) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_20");
    	return;
    }
    if (!fs_droidsansfallback_50) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_50");
    	return;
    }
    if (!fs_droidsansfallback_30) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_30");
    	return;
    }
    if (!fs_montserratmedium_35) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_35");
    	return;
    }
    if (!fs_montserratmedium_80) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_80");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    scrSport_create(&ui_manager);
    lv_scr_load(scrSport_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
