/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *player_move;
    lv_obj_t *img_gradient2;
    lv_obj_t *img_gradient1;
    lv_obj_t *cont_cover2;
    lv_obj_t *cont_cover1;
    lv_obj_t *cont_right;
    lv_obj_t *image_25;
    lv_obj_t *label_rpm;
    lv_obj_t *label_14;
    lv_obj_t *cont_left;
    lv_obj_t *image_24;
    lv_obj_t *label_speed;
    lv_obj_t *label_12;
    lv_obj_t *img_bottom;
    lv_obj_t *img_mid;
    lv_obj_t *img_top;
    lv_obj_t *label_10;
    lv_obj_t *image_30;
    lv_obj_t *cont_dir;
    lv_obj_t *img_dir;
    lv_obj_t *label_dir;
    lv_obj_t *label_dist;
    lv_obj_t *img_light;
    lv_obj_t *image_33;
    lv_obj_t *image_34;
    lv_obj_t *img_gear;
} scrRace_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *player_2;
    lv_obj_t *image_shadow;
    lv_obj_t *img_bottom;
    lv_obj_t *cont_left;
    lv_obj_t *image_3;
    lv_obj_t *arc_left;
    lv_obj_t *label_speed;
    lv_obj_t *label_3;
    lv_obj_t *cont_right;
    lv_obj_t *image_4;
    lv_obj_t *arc_right;
    lv_obj_t *label_rpm;
    lv_obj_t *label_4;
    lv_obj_t *image_top;
    lv_obj_t *cont_dir;
    lv_obj_t *image_dir;
    lv_obj_t *label_dir;
    lv_obj_t *label_dist;
    lv_obj_t *image_light;
    lv_obj_t *label_time;
    lv_obj_t *image_9;
    lv_obj_t *image_10;
    lv_obj_t *image_36;
} scrSport_t;


typedef struct {
    bool auto_del;
    scrRace_t scrRace;
    scrSport_t scrSport;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline scrRace_t *scrRace_get(ui_manager_t *ui)
{
    return &ui->scrRace;
}

static inline scrSport_t *scrSport_get(ui_manager_t *ui)
{
    return &ui->scrSport;
}


void scrRace_create(ui_manager_t *ui);
void scrSport_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_50;
extern lv_font_t *fs_montserratmedium_70;
extern lv_font_t *fs_montserratmedium_20;
extern lv_font_t *fs_droidsansfallback_50;
extern lv_font_t *fs_droidsansfallback_30;
extern lv_font_t *fs_montserratmedium_35;
extern lv_font_t *fs_montserratmedium_80;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
