/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "custom.h"
#include "lv_aic_player.h"
#include "my_custom.h"

static void set_player(void);

static void switch_hidden_status_cb(lv_event_t *e);
static void switch_play_status_cb(lv_event_t *e);
static void set_player_scale_cb(lv_event_t *e);
static void set_next_player_cb(lv_event_t *e);
static void set_last_player_cb(lv_event_t *e);

void custom_init()
{
    /* Add your codes here */
    player_list_init();

    if (player_list_get_count() < 0) {
        printf("Warning: No video files found\n");
    } else {
        player_list.current++;
        if (player_list.current >= player_list.count)
            player_list.current = 0; 
    }

    lv_obj_t *player = main_screen_get(&ui_manager)->player;
    lv_obj_add_event_cb(player, switch_hidden_status_cb, LV_EVENT_ALL, NULL);

    lv_obj_t *play_img = main_screen_get(&ui_manager)->play_img;
    lv_obj_add_event_cb(play_img, switch_play_status_cb, LV_EVENT_ALL, player);

    lv_obj_t *zoom_img = main_screen_get(&ui_manager)->zoom_img;
    lv_obj_add_event_cb(zoom_img, set_player_scale_cb, LV_EVENT_ALL, player);

    lv_obj_t *next_img = main_screen_get(&ui_manager)->next_img;
    lv_obj_add_event_cb(next_img, set_next_player_cb, LV_EVENT_ALL, player);

    lv_obj_t *last_img = main_screen_get(&ui_manager)->last_img;
    lv_obj_add_event_cb(last_img, set_last_player_cb, LV_EVENT_ALL, player);
}

static void switch_hidden_status_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *control_container = main_screen_get(&ui_manager)->control_container;
    lv_obj_t *file_name = main_screen_get(&ui_manager)->file_name_label;
    lv_obj_t *author_label = main_screen_get(&ui_manager)->author_label;

    if (code == LV_EVENT_CLICKED)
    {
        if (lv_obj_has_flag(control_container, LV_OBJ_FLAG_HIDDEN))
        {
            lv_obj_clear_flag(control_container, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(file_name, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(author_label, LV_OBJ_FLAG_HIDDEN);
        }
        else
        {
            lv_obj_add_flag(control_container, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(file_name, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(author_label, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

static void switch_play_status_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *play_img = lv_event_get_current_target(e);
    lv_obj_t *player = lv_event_get_user_data(e);

    if (code == LV_EVENT_CLICKED)
    {
        const char *src = lv_img_get_src(play_img);
        if (src && strstr(src, "play.png"))
        {
            lv_img_set_src(play_img, LVGL_IMAGE_PATH(pause.png));
            lv_aic_player_set_cmd(player, LV_AIC_PLAYER_CMD_PAUSE, NULL);
        }
        else
        {
            lv_img_set_src(play_img, LVGL_IMAGE_PATH(play.png));
            lv_aic_player_set_cmd(player, LV_AIC_PLAYER_CMD_RESUME, NULL);
        }
    }
}

static void set_player_scale_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *zoom_img = lv_event_get_current_target(e);
    lv_obj_t *player = lv_event_get_user_data(e);

    if (code == LV_EVENT_CLICKED)
    {
        if (strstr(lv_img_get_src(zoom_img), "zoom_in.png"))
        {
            lv_img_set_src(zoom_img, LVGL_IMAGE_PATH(zoom_out.png));
            lv_obj_center(player);
            lv_aic_player_set_scale(player, 128);
        }
        else
        {
            lv_img_set_src(zoom_img, LVGL_IMAGE_PATH(zoom_in.png));
            lv_obj_center(player);
            lv_aic_player_set_scale(player, 256);
        }
    }
}

static void set_player(void)
{
    lv_obj_t *player = main_screen_get(&ui_manager)->player;
    lv_obj_t *file_name_label = main_screen_get(&ui_manager)->file_name_label;
    lv_obj_t *play_img = main_screen_get(&ui_manager)->play_img;

    const char *path = player_list_get_path(player_list.current);
    const char *name = player_list_get_name(player_list.current);
    
    if (path && name) {
        lv_aic_player_set_src(player, path);
        lv_aic_player_set_cmd(player, LV_AIC_PLAYER_CMD_START, NULL);
        lv_label_set_text(file_name_label, name);
        lv_img_set_src(play_img, LVGL_IMAGE_PATH(play.png));
    } else {
        printf("Error: Invalid path or name at index %d\n", player_list.current);
    }
}

static void set_next_player_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_CLICKED)
    {
        player_list.current++;
        if (player_list.current >= player_list.count)
            player_list.current = 0;
        set_player();
    }
}

static void set_last_player_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_CLICKED)
    {
        player_list.current--;
        if (player_list.current < 0)
            player_list.current = player_list.count - 1;
        set_player();
    }
}
