/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) screen_1_roller_created(void) {
}

static void screen_1_loaded (lv_event_t *e) {
    screen_1_roller_created();
}

static void screen_1_container_home_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen_main
        screen_main_create(&ui_manager);
        // load screen_main
        lv_scr_load_anim(screen_main_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void screen_1_image_home_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen_main
        screen_main_create(&ui_manager);
        // load screen_main
        lv_scr_load_anim(screen_main_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void screen_1_create(ui_manager_t *ui)
{
    screen_1_t *scr = screen_1_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_1_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->container_home
    scr->container_home = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_home, 63, 54);
    lv_obj_set_size(scr->container_home, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_home, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_home, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_home
    lv_obj_set_style_bg_color(scr->container_home, lv_color_hex(0x2bbaba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_home, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->container_home
    lv_obj_add_event_cb(scr->container_home, screen_1_container_home_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->image_home
    scr->image_home = lv_img_create(scr->container_home);
    lv_img_set_src(scr->image_home, LVGL_IMAGE_PATH(main/left/home-fill.png));
    lv_img_set_pivot(scr->image_home, 50, 50);
    lv_img_set_offset_x(scr->image_home, 0);
    lv_img_set_offset_y(scr->image_home, 0);
    lv_img_set_angle(scr->image_home, 0);
    lv_obj_set_pos(scr->image_home, 15, 15);
    lv_obj_add_flag(scr->image_home, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_home
    lv_obj_add_event_cb(scr->image_home, screen_1_image_home_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->container_camera
    scr->container_camera = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_camera, 63, 160);
    lv_obj_set_size(scr->container_camera, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_camera, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_camera, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_camera
    lv_obj_set_style_bg_color(scr->container_camera, lv_color_hex(0x2bbaba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_camera, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_camera
    scr->image_camera = lv_img_create(scr->container_camera);
    lv_img_set_src(scr->image_camera, LVGL_IMAGE_PATH(main/left/camera-fill.png));
    lv_img_set_pivot(scr->image_camera, 50, 50);
    lv_img_set_offset_x(scr->image_camera, 0);
    lv_img_set_offset_y(scr->image_camera, 0);
    lv_img_set_angle(scr->image_camera, 0);
    lv_obj_set_pos(scr->image_camera, 17, 17);
    lv_obj_add_flag(scr->image_camera, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_phone
    scr->container_phone = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_phone, 63, 265);
    lv_obj_set_size(scr->container_phone, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_phone, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_phone, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_phone
    lv_obj_set_style_bg_color(scr->container_phone, lv_color_hex(0x2bbaba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_phone, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_phone
    scr->image_phone = lv_img_create(scr->container_phone);
    lv_img_set_src(scr->image_phone, LVGL_IMAGE_PATH(main/left/phone-fill.png));
    lv_img_set_pivot(scr->image_phone, 50, 50);
    lv_img_set_offset_x(scr->image_phone, 0);
    lv_img_set_offset_y(scr->image_phone, 0);
    lv_img_set_angle(scr->image_phone, 0);
    lv_obj_set_pos(scr->image_phone, 17, 17);
    lv_obj_add_flag(scr->image_phone, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_play
    scr->container_play = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_play, 63, 370);
    lv_obj_set_size(scr->container_play, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_play, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_play, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_play
    lv_obj_set_style_bg_color(scr->container_play, lv_color_hex(0x2bbaba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_play, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_play
    scr->image_play = lv_img_create(scr->container_play);
    lv_img_set_src(scr->image_play, LVGL_IMAGE_PATH(main/left/play-fill.png));
    lv_img_set_pivot(scr->image_play, 50, 50);
    lv_img_set_offset_x(scr->image_play, 0);
    lv_img_set_offset_y(scr->image_play, 0);
    lv_img_set_angle(scr->image_play, 0);
    lv_obj_set_pos(scr->image_play, 17, 17);
    lv_obj_add_flag(scr->image_play, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_set
    scr->container_set = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_set, 63, 478);
    lv_obj_set_size(scr->container_set, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_set, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_set
    lv_obj_set_style_bg_color(scr->container_set, lv_color_hex(0x05ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_set, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_set
    scr->image_set = lv_img_create(scr->container_set);
    lv_img_set_src(scr->image_set, LVGL_IMAGE_PATH(main/left/setting.png));
    lv_img_set_pivot(scr->image_set, 50, 50);
    lv_img_set_offset_x(scr->image_set, 0);
    lv_img_set_offset_y(scr->image_set, 0);
    lv_img_set_angle(scr->image_set, 0);
    lv_obj_set_pos(scr->image_set, 17, 17);

    // Init scr->container_car
    scr->container_car = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_car, 489, 0);
    lv_obj_set_size(scr->container_car, 467, 600);
    lv_obj_set_scrollbar_mode(scr->container_car, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(scr->container_car, LV_OBJ_FLAG_SCROLLABLE);

    // Set style of scr->container_car
    lv_obj_set_style_bg_opa(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_car, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_car, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->container_car);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(screen1/car2.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_offset_x(scr->image_2, 0);
    lv_img_set_offset_y(scr->image_2, 0);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_pos(scr->image_2, 56, 179);
    lv_obj_add_flag(scr->image_2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->image_2, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_3
    scr->image_3 = lv_img_create(scr->container_car);
    lv_img_set_src(scr->image_3, LVGL_IMAGE_PATH(screen1/car3.png));
    lv_img_set_pivot(scr->image_3, 50, 50);
    lv_img_set_offset_x(scr->image_3, 0);
    lv_img_set_offset_y(scr->image_3, 0);
    lv_img_set_angle(scr->image_3, 0);
    lv_obj_set_pos(scr->image_3, 57, 471);
    lv_obj_add_flag(scr->image_3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->image_3, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->container_car);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(screen1/car1.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 56, -113);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_text
    scr->container_text = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_text, 195, 134);
    lv_obj_set_size(scr->container_text, 258, 300);
    lv_obj_set_scrollbar_mode(scr->container_text, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_text
    lv_obj_set_style_bg_opa(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_text, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->text_1
    scr->text_1 = lv_label_create(scr->container_text);
    lv_label_set_text(scr->text_1, "街道模式");
    lv_label_set_long_mode(scr->text_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->text_1, 39, 0);
    lv_obj_set_size(scr->text_1, 180, 55);
    lv_obj_add_flag(scr->text_1, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->text_1
    lv_obj_set_style_text_color(scr->text_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->text_1, fs_droidsansfallback_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->text_2
    scr->text_2 = lv_label_create(scr->container_text);
    lv_label_set_text(scr->text_2, "运动模式");
    lv_label_set_long_mode(scr->text_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->text_2, 39, 122);
    lv_obj_set_size(scr->text_2, 180, 55);
    lv_obj_add_flag(scr->text_2, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->text_2
    lv_obj_set_style_text_color(scr->text_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->text_2, fs_droidsansfallback_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->text_3
    scr->text_3 = lv_label_create(scr->container_text);
    lv_label_set_text(scr->text_3, "竞速模式");
    lv_label_set_long_mode(scr->text_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->text_3, 39, 245);
    lv_obj_set_size(scr->text_3, 180, 55);
    lv_obj_add_flag(scr->text_3, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->text_3
    lv_obj_set_style_text_color(scr->text_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->text_3, fs_droidsansfallback_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_wait
    scr->label_wait = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_wait, "功能开发中");
    lv_label_set_long_mode(scr->label_wait, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_wait, 384, 18);
    lv_obj_set_size(scr->label_wait, 100, 28);
    lv_obj_add_flag(scr->label_wait, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->label_wait
    lv_obj_set_style_text_color(scr->label_wait, lv_color_hex(0x31fcf9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_wait, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_wait, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);


}


