/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) test_speed_simulator_init(void) {
}

static void screen_2_loaded (lv_event_t *e) {
    test_speed_simulator_init();
}

void __attribute__((weak)) screen_2_anim_cleanup(void) {
}

static void screen_2_image_1_clicked (lv_event_t *e) {
    screen_2_anim_cleanup();
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen_1
        screen_1_create(&ui_manager);
        // load screen_1
        lv_scr_load_anim(screen_1_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void screen_2_create(ui_manager_t *ui)
{
    screen_2_t *scr = screen_2_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->obj, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_2_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->image_arc_up
    scr->image_arc_up = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_arc_up, LVGL_IMAGE_PATH(screen2/screen2_up.png));
    lv_img_set_pivot(scr->image_arc_up, 50, 50);
    lv_img_set_offset_x(scr->image_arc_up, 0);
    lv_img_set_offset_y(scr->image_arc_up, 0);
    lv_img_set_angle(scr->image_arc_up, 0);
    lv_obj_set_pos(scr->image_arc_up, 142, 1);

    // Init scr->image_arc_down
    scr->image_arc_down = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_arc_down, LVGL_IMAGE_PATH(screen2/down.png));
    lv_img_set_pivot(scr->image_arc_down, 50, 50);
    lv_img_set_offset_x(scr->image_arc_down, 0);
    lv_img_set_offset_y(scr->image_arc_down, 0);
    lv_img_set_angle(scr->image_arc_down, 0);
    lv_obj_set_pos(scr->image_arc_down, 119, 489);

    // Init scr->image_shadow
    scr->image_shadow = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_shadow, LVGL_IMAGE_PATH(screen2/screen2_mid.png));
    lv_img_set_pivot(scr->image_shadow, 50, 50);
    lv_img_set_offset_x(scr->image_shadow, 0);
    lv_img_set_offset_y(scr->image_shadow, 0);
    lv_img_set_angle(scr->image_shadow, 0);
    lv_obj_set_pos(scr->image_shadow, 256, 165);

    // Set style of scr->image_shadow
    lv_obj_set_style_img_opa(scr->image_shadow, 102, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_gear
    scr->container_gear = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_gear, 382, 540);
    lv_obj_set_size(scr->container_gear, 300, 60);
    lv_obj_set_scrollbar_mode(scr->container_gear, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_gear
    lv_obj_set_style_bg_opa(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_gear, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_gear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_P
    scr->image_P = lv_img_create(scr->container_gear);
    lv_img_set_src(scr->image_P, LVGL_IMAGE_PATH(gear/P.png));
    lv_img_set_pivot(scr->image_P, 50, 50);
    lv_img_set_offset_x(scr->image_P, 0);
    lv_img_set_offset_y(scr->image_P, 0);
    lv_img_set_angle(scr->image_P, 0);
    lv_obj_set_pos(scr->image_P, 0, 3);

    // Init scr->image_R
    scr->image_R = lv_img_create(scr->container_gear);
    lv_img_set_src(scr->image_R, LVGL_IMAGE_PATH(gear/R.png));
    lv_img_set_pivot(scr->image_R, 50, 50);
    lv_img_set_offset_x(scr->image_R, 0);
    lv_img_set_offset_y(scr->image_R, 0);
    lv_img_set_angle(scr->image_R, 0);
    lv_obj_set_pos(scr->image_R, 0, 0);
    lv_obj_add_flag(scr->image_R, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_N
    scr->image_N = lv_img_create(scr->container_gear);
    lv_img_set_src(scr->image_N, LVGL_IMAGE_PATH(gear/N.png));
    lv_img_set_pivot(scr->image_N, 50, 50);
    lv_img_set_offset_x(scr->image_N, 0);
    lv_img_set_offset_y(scr->image_N, 0);
    lv_img_set_angle(scr->image_N, 0);
    lv_obj_set_pos(scr->image_N, 0, 0);
    lv_obj_add_flag(scr->image_N, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_D
    scr->image_D = lv_img_create(scr->container_gear);
    lv_img_set_src(scr->image_D, LVGL_IMAGE_PATH(gear/D.png));
    lv_img_set_pivot(scr->image_D, 50, 50);
    lv_img_set_offset_x(scr->image_D, 0);
    lv_img_set_offset_y(scr->image_D, 0);
    lv_img_set_angle(scr->image_D, 0);
    lv_obj_set_pos(scr->image_D, 0, 0);
    lv_obj_add_flag(scr->image_D, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_S
    scr->image_S = lv_img_create(scr->container_gear);
    lv_img_set_src(scr->image_S, LVGL_IMAGE_PATH(gear/S.png));
    lv_img_set_pivot(scr->image_S, 50, 50);
    lv_img_set_offset_x(scr->image_S, 0);
    lv_img_set_offset_y(scr->image_S, 0);
    lv_img_set_angle(scr->image_S, 0);
    lv_obj_set_pos(scr->image_S, 0, 0);
    lv_obj_add_flag(scr->image_S, LV_OBJ_FLAG_HIDDEN);

    // Init scr->player_car_move
    scr->player_car_move = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->player_car_move, LVGL_VIDEO_PATH(car_move.png));
    lv_aic_player_set_auto_restart(scr->player_car_move, true);
    lv_aic_player_set_cmd(scr->player_car_move, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->player_car_move, 306, 276);
    lv_obj_set_size(scr->player_car_move, 422, 211);

    // Init scr->container_information
    scr->container_information = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_information, 410, 96);
    lv_obj_set_size(scr->container_information, 268, 100);
    lv_obj_set_scrollbar_mode(scr->container_information, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_information
    lv_obj_set_style_bg_opa(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_information, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_light
    scr->image_light = lv_img_create(scr->container_information);
    lv_img_set_src(scr->image_light, LVGL_IMAGE_PATH(screen2/light.png));
    lv_img_set_pivot(scr->image_light, 50, 50);
    lv_img_set_offset_x(scr->image_light, 0);
    lv_img_set_offset_y(scr->image_light, 0);
    lv_img_set_angle(scr->image_light, 0);
    lv_obj_set_pos(scr->image_light, 12, 13);

    // Init scr->image_turn_right
    scr->image_turn_right = lv_img_create(scr->container_information);
    lv_img_set_src(scr->image_turn_right, LVGL_IMAGE_PATH(turn/right.png));
    lv_img_set_pivot(scr->image_turn_right, 50, 50);
    lv_img_set_offset_x(scr->image_turn_right, 0);
    lv_img_set_offset_y(scr->image_turn_right, 0);
    lv_img_set_angle(scr->image_turn_right, 0);
    lv_obj_set_pos(scr->image_turn_right, 195, 0);
    lv_obj_add_flag(scr->image_turn_right, LV_OBJ_FLAG_HIDDEN);

    // Init scr->label_address
    scr->label_address = lv_label_create(scr->container_information);
    lv_label_set_text(scr->label_address, "右转进入珠海大桥\n");
    lv_label_set_long_mode(scr->label_address, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_address, 36, 72);
    lv_obj_set_size(scr->label_address, 177, 27);

    // Set style of scr->label_address
    lv_obj_set_style_text_color(scr->label_address, lv_color_hex(0xf6f6f6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_address, fs_droidsansfallback_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_meter
    scr->label_meter = lv_label_create(scr->container_information);
    lv_label_set_text(scr->label_meter, "420");
    lv_label_set_long_mode(scr->label_meter, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_meter, 68, 10);
    lv_obj_set_size(scr->label_meter, 77, 42);

    // Set style of scr->label_meter
    lv_obj_set_style_text_color(scr->label_meter, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_meter, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_meter, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_meter, fs_montserratmedium_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_m
    scr->label_m = lv_label_create(scr->container_information);
    lv_label_set_text(scr->label_m, "m");
    lv_label_set_long_mode(scr->label_m, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_m, 152, 11);
    lv_obj_set_size(scr->label_m, 28, 43);

    // Set style of scr->label_m
    lv_obj_set_style_text_color(scr->label_m, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_m, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_m, fs_montserratmedium_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_straight
    scr->image_straight = lv_img_create(scr->container_information);
    lv_img_set_src(scr->image_straight, LVGL_IMAGE_PATH(turn/straight2.png));
    lv_img_set_pivot(scr->image_straight, 50, 50);
    lv_img_set_offset_x(scr->image_straight, 0);
    lv_img_set_offset_y(scr->image_straight, 0);
    lv_img_set_angle(scr->image_straight, 0);
    lv_obj_set_pos(scr->image_straight, 195, 0);

    // Init scr->image_turn_left
    scr->image_turn_left = lv_img_create(scr->container_information);
    lv_img_set_src(scr->image_turn_left, LVGL_IMAGE_PATH(turn/left.png));
    lv_img_set_pivot(scr->image_turn_left, 50, 50);
    lv_img_set_offset_x(scr->image_turn_left, 0);
    lv_img_set_offset_y(scr->image_turn_left, 0);
    lv_img_set_angle(scr->image_turn_left, 0);
    lv_obj_set_pos(scr->image_turn_left, 195, 0);
    lv_obj_add_flag(scr->image_turn_left, LV_OBJ_FLAG_HIDDEN);

    // Init scr->container_left
    scr->container_left = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_left, 27, 107);
    lv_obj_set_size(scr->container_left, 372, 373);
    lv_obj_set_scrollbar_mode(scr->container_left, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_left
    lv_obj_set_style_bg_opa(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_left, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->left_circlr_img
    scr->left_circlr_img = lv_img_create(scr->container_left);
    lv_img_set_src(scr->left_circlr_img, LVGL_IMAGE_PATH(screen2/speedometer_372x372.png));
    lv_img_set_pivot(scr->left_circlr_img, 50, 50);
    lv_img_set_offset_x(scr->left_circlr_img, 0);
    lv_img_set_offset_y(scr->left_circlr_img, 0);
    lv_img_set_angle(scr->left_circlr_img, 0);
    lv_obj_set_pos(scr->left_circlr_img, 0, 0);

    // Set style of scr->left_circlr_img
    lv_obj_set_style_img_recolor(scr->left_circlr_img, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_speed
    scr->arc_speed = lv_arc_create(scr->container_left);
    lv_arc_set_mode(scr->arc_speed, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_speed, 0, 100);
    lv_arc_set_value(scr->arc_speed, 50);
    lv_arc_set_bg_angles(scr->arc_speed, 135, 45);
    lv_arc_set_angles(scr->arc_speed, 135, 270);
    lv_arc_set_rotation(scr->arc_speed, 0);
    lv_arc_set_change_rate(scr->arc_speed, 720);
    lv_obj_set_pos(scr->arc_speed, 73, 78);
    lv_obj_set_size(scr->arc_speed, 220, 220);
    lv_obj_clear_flag(scr->arc_speed, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->arc_speed
    lv_obj_set_style_bg_color(scr->arc_speed, lv_color_hex(0x024f4c), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(scr->arc_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(scr->arc_speed, lv_color_hex(0x004f4a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(scr->arc_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_speed, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_speed, lv_color_hex(0x004f4a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(scr->arc_speed, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_speed, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_speed, lv_color_hex(0x63fdfb), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_speed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->label_speed
    scr->label_speed = lv_label_create(scr->container_left);
    lv_label_set_text(scr->label_speed, "200");
    lv_label_set_long_mode(scr->label_speed, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_speed, 130, 162);
    lv_obj_set_size(scr->label_speed, 104, 50);

    // Set style of scr->label_speed
    lv_obj_set_style_text_color(scr->label_speed, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_speed, fs_montserratmedium_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_mileage
    scr->label_mileage = lv_label_create(scr->container_left);
    lv_label_set_text(scr->label_mileage, "2584km");
    lv_label_set_long_mode(scr->label_mileage, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_mileage, 154, 286);
    lv_obj_set_size(scr->label_mileage, 62, 17);

    // Set style of scr->label_mileage
    lv_obj_set_style_text_color(scr->label_mileage, lv_color_hex(0x45b6b4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_mileage, fs_montserratmedium_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_km
    scr->image_km = lv_img_create(scr->container_left);
    lv_img_set_src(scr->image_km, LVGL_IMAGE_PATH(screen2/KM_H.png));
    lv_img_set_pivot(scr->image_km, 50, 50);
    lv_img_set_offset_x(scr->image_km, 0);
    lv_img_set_offset_y(scr->image_km, 0);
    lv_img_set_angle(scr->image_km, 0);
    lv_obj_set_pos(scr->image_km, 160, 217);

    // Init scr->container_right
    scr->container_right = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_right, 655, 142);
    lv_obj_set_size(scr->container_right, 317, 317);
    lv_obj_set_scrollbar_mode(scr->container_right, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_right
    lv_obj_set_style_bg_opa(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_right, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->right_circlr_img
    scr->right_circlr_img = lv_img_create(scr->container_right);
    lv_img_set_src(scr->right_circlr_img, LVGL_IMAGE_PATH(screen2/right_circle_317x317.png));
    lv_img_set_pivot(scr->right_circlr_img, 50, 50);
    lv_img_set_offset_x(scr->right_circlr_img, 0);
    lv_img_set_offset_y(scr->right_circlr_img, 0);
    lv_img_set_angle(scr->right_circlr_img, 0);
    lv_obj_set_pos(scr->right_circlr_img, 0, 0);

    // Init scr->image_point
    scr->image_point = lv_img_create(scr->container_right);
    lv_img_set_src(scr->image_point, LVGL_IMAGE_PATH(screen2/point.png));
    lv_img_set_pivot(scr->image_point, 50, 50);
    lv_img_set_offset_x(scr->image_point, 0);
    lv_img_set_offset_y(scr->image_point, 0);
    lv_img_set_angle(scr->image_point, 0);
    lv_obj_set_pos(scr->image_point, 118, 110);

    // Init scr->arc_rmp
    scr->arc_rmp = lv_arc_create(scr->container_right);
    lv_arc_set_mode(scr->arc_rmp, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_rmp, 0, 100);
    lv_arc_set_value(scr->arc_rmp, 50);
    lv_arc_set_bg_angles(scr->arc_rmp, 90, 89);
    lv_arc_set_angles(scr->arc_rmp, 90, 269);
    lv_arc_set_rotation(scr->arc_rmp, 0);
    lv_arc_set_change_rate(scr->arc_rmp, 720);
    lv_obj_set_pos(scr->arc_rmp, 28, 26);
    lv_obj_set_size(scr->arc_rmp, 266, 265);
    lv_obj_clear_flag(scr->arc_rmp, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->arc_rmp
    lv_obj_set_style_arc_width(scr->arc_rmp, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(scr->arc_rmp, 97, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_rmp, lv_color_hex(0x297079), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(scr->arc_rmp, 11, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_rmp, lv_color_hex(0x31fcf9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->arc_rmp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Init scr->image_rmp
    scr->image_rmp = lv_img_create(scr->container_right);
    lv_img_set_src(scr->image_rmp, LVGL_IMAGE_PATH(screen2/1000rmp.png));
    lv_img_set_pivot(scr->image_rmp, 50, 50);
    lv_img_set_offset_x(scr->image_rmp, 0);
    lv_img_set_offset_y(scr->image_rmp, 0);
    lv_img_set_angle(scr->image_rmp, 0);
    lv_obj_set_pos(scr->image_rmp, 124, 190);

    // Init scr->label_left
    scr->label_left = lv_label_create(scr->container_right);
    lv_label_set_text(scr->label_left, "9");
    lv_label_set_long_mode(scr->label_left, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_left, 84, 110);
    lv_obj_set_size(scr->label_left, 64, 73);

    // Set style of scr->label_left
    lv_obj_set_style_text_color(scr->label_left, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_left, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_left, fs_montserratmedium_62, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_right
    scr->label_right = lv_label_create(scr->container_right);
    lv_label_set_text(scr->label_right, "9");
    lv_label_set_long_mode(scr->label_right, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_right, 167, 110);
    lv_obj_set_size(scr->label_right, 35, 73);

    // Set style of scr->label_right
    lv_obj_set_style_text_color(scr->label_right, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_right, fs_montserratmedium_62, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->screen2_time
    scr->screen2_time = lv_label_create(scr->obj);
    lv_label_set_text(scr->screen2_time, "16:17");
    lv_label_set_long_mode(scr->screen2_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->screen2_time, 460, 12);
    lv_obj_set_size(scr->screen2_time, 104, 31);

    // Set style of scr->screen2_time
    lv_obj_set_style_text_color(scr->screen2_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->screen2_time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->screen2_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->screen2_time, fs_montserratmedium_29, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(screen2/back.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 27, 20);
    lv_obj_add_flag(scr->image_1, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->image_1
    lv_obj_add_event_cb(scr->image_1, screen_2_image_1_clicked, LV_EVENT_CLICKED, NULL);


}


