/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

#include "lv_aic_player.h"

void __attribute__((weak)) screen_main_custom_init(void) {
}

static void screen_main_loaded (lv_event_t *e) {
    screen_main_custom_init();
}


void screen_main_create(ui_manager_t *ui)
{
    screen_main_t *scr = screen_main_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_main_loaded, LV_EVENT_SCREEN_LOADED, NULL);

    // Init scr->container_home
    scr->container_home = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_home, 63, 54);
    lv_obj_set_size(scr->container_home, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_home, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_home
    lv_obj_set_style_bg_color(scr->container_home, lv_color_hex(0x05ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_home, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_home, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_home
    scr->image_home = lv_img_create(scr->container_home);
    lv_img_set_src(scr->image_home, LVGL_IMAGE_PATH(main/left/home-fill.png));
    lv_img_set_pivot(scr->image_home, 50, 50);
    lv_img_set_offset_x(scr->image_home, 0);
    lv_img_set_offset_y(scr->image_home, 0);
    lv_img_set_angle(scr->image_home, 0);
    lv_obj_set_pos(scr->image_home, 15, 15);

    // Init scr->container_camera
    scr->container_camera = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_camera, 63, 160);
    lv_obj_set_size(scr->container_camera, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_camera, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_camera, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_camera
    lv_obj_set_style_bg_color(scr->container_camera, lv_color_hex(0x2cb8ba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_camera, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_camera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_camera
    scr->image_camera = lv_img_create(scr->container_camera);
    lv_img_set_src(scr->image_camera, LVGL_IMAGE_PATH(main/left/camera-fill.png));
    lv_img_set_pivot(scr->image_camera, 50, 50);
    lv_img_set_offset_x(scr->image_camera, 0);
    lv_img_set_offset_y(scr->image_camera, 0);
    lv_img_set_angle(scr->image_camera, 0);
    lv_obj_set_pos(scr->image_camera, 17, 17);
    lv_obj_add_flag(scr->image_camera, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_phone
    scr->container_phone = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_phone, 63, 265);
    lv_obj_set_size(scr->container_phone, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_phone, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_phone, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_phone
    lv_obj_set_style_bg_color(scr->container_phone, lv_color_hex(0x2cb8ba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_phone, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_phone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_phone
    scr->image_phone = lv_img_create(scr->container_phone);
    lv_img_set_src(scr->image_phone, LVGL_IMAGE_PATH(main/left/phone-fill.png));
    lv_img_set_pivot(scr->image_phone, 50, 50);
    lv_img_set_offset_x(scr->image_phone, 0);
    lv_img_set_offset_y(scr->image_phone, 0);
    lv_img_set_angle(scr->image_phone, 0);
    lv_obj_set_pos(scr->image_phone, 17, 17);
    lv_obj_add_flag(scr->image_phone, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_play
    scr->container_play = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_play, 63, 370);
    lv_obj_set_size(scr->container_play, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_play, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_play, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_play
    lv_obj_set_style_bg_color(scr->container_play, lv_color_hex(0x2cb8ba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_play, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_play, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_play
    scr->image_play = lv_img_create(scr->container_play);
    lv_img_set_src(scr->image_play, LVGL_IMAGE_PATH(main/left/play-fill.png));
    lv_img_set_pivot(scr->image_play, 50, 50);
    lv_img_set_offset_x(scr->image_play, 0);
    lv_img_set_offset_y(scr->image_play, 0);
    lv_img_set_angle(scr->image_play, 0);
    lv_obj_set_pos(scr->image_play, 17, 17);
    lv_obj_add_flag(scr->image_play, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_set
    scr->container_set = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_set, 63, 478);
    lv_obj_set_size(scr->container_set, 70, 70);
    lv_obj_set_scrollbar_mode(scr->container_set, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(scr->container_set, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->container_set
    lv_obj_set_style_bg_color(scr->container_set, lv_color_hex(0x2cb8ba), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_set, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_set, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_set
    scr->image_set = lv_img_create(scr->container_set);
    lv_img_set_src(scr->image_set, LVGL_IMAGE_PATH(main/left/setting.png));
    lv_img_set_pivot(scr->image_set, 50, 50);
    lv_img_set_offset_x(scr->image_set, 0);
    lv_img_set_offset_y(scr->image_set, 0);
    lv_img_set_angle(scr->image_set, 0);
    lv_obj_set_pos(scr->image_set, 17, 17);
    lv_obj_add_flag(scr->image_set, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->container_music
    scr->container_music = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_music, 213, 443);
    lv_obj_set_size(scr->container_music, 479, 104);
    lv_obj_set_scrollbar_mode(scr->container_music, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_music
    lv_obj_set_style_bg_color(scr->container_music, lv_color_hex(0x1d4b4a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(scr->container_music, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->container_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_album1
    scr->image_album1 = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_album1, LVGL_IMAGE_PATH(main/play/album_cover.png));
    lv_img_set_pivot(scr->image_album1, 50, 50);
    lv_img_set_offset_x(scr->image_album1, 0);
    lv_img_set_offset_y(scr->image_album1, 0);
    lv_img_set_angle(scr->image_album1, 0);
    lv_obj_set_pos(scr->image_album1, 20, 19);

    // Init scr->image_pre
    scr->image_pre = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_pre, LVGL_IMAGE_PATH(main/play/previous.png));
    lv_img_set_pivot(scr->image_pre, 50, 50);
    lv_img_set_offset_x(scr->image_pre, 0);
    lv_img_set_offset_y(scr->image_pre, 0);
    lv_img_set_angle(scr->image_pre, 0);
    lv_obj_set_pos(scr->image_pre, 163, 23);
    lv_obj_add_flag(scr->image_pre, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_back
    scr->image_back = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_back, LVGL_IMAGE_PATH(main/play/skip-back.png));
    lv_img_set_pivot(scr->image_back, 50, 50);
    lv_img_set_offset_x(scr->image_back, 0);
    lv_img_set_offset_y(scr->image_back, 0);
    lv_img_set_angle(scr->image_back, 0);
    lv_obj_set_pos(scr->image_back, 215, 25);
    lv_obj_add_flag(scr->image_back, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_stop
    scr->image_stop = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_stop, LVGL_IMAGE_PATH(main/play/stop-fill.png));
    lv_img_set_pivot(scr->image_stop, 50, 50);
    lv_img_set_offset_x(scr->image_stop, 0);
    lv_img_set_offset_y(scr->image_stop, 0);
    lv_img_set_angle(scr->image_stop, 0);
    lv_obj_set_pos(scr->image_stop, 283, 24);
    lv_obj_add_flag(scr->image_stop, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_forward
    scr->image_forward = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_forward, LVGL_IMAGE_PATH(main/play/skip-forward.png));
    lv_img_set_pivot(scr->image_forward, 50, 50);
    lv_img_set_offset_x(scr->image_forward, 0);
    lv_img_set_offset_y(scr->image_forward, 0);
    lv_img_set_angle(scr->image_forward, 0);
    lv_obj_set_pos(scr->image_forward, 359, 27);
    lv_obj_add_flag(scr->image_forward, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->image_next
    scr->image_next = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_next, LVGL_IMAGE_PATH(main/play/next.png));
    lv_img_set_pivot(scr->image_next, 50, 50);
    lv_img_set_offset_x(scr->image_next, 0);
    lv_img_set_offset_y(scr->image_next, 0);
    lv_img_set_angle(scr->image_next, 0);
    lv_obj_set_pos(scr->image_next, 419, 26);
    lv_obj_add_flag(scr->image_next, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->bar_progress
    scr->bar_progress = lv_bar_create(scr->container_music);
    lv_bar_set_mode(scr->bar_progress, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->bar_progress, 0, 100);
    lv_bar_set_value(scr->bar_progress, 50, LV_ANIM_OFF);
    lv_obj_set_pos(scr->bar_progress, 157, 64);
    lv_obj_set_size(scr->bar_progress, 293, 8);

    // Set style of scr->bar_progress
    lv_obj_set_style_bg_opa(scr->bar_progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_progress, lv_color_hex(0xa5a5a5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_progress, lv_color_hex(0x2bbaba), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->image_start
    scr->image_start = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_start, LVGL_IMAGE_PATH(main/start_14x18.png));
    lv_img_set_pivot(scr->image_start, 50, 50);
    lv_img_set_offset_x(scr->image_start, 0);
    lv_img_set_offset_y(scr->image_start, 0);
    lv_img_set_angle(scr->image_start, 0);
    lv_obj_set_pos(scr->image_start, 290, 27);
    lv_obj_add_flag(scr->image_start, LV_OBJ_FLAG_CLICKABLE);

    // Init scr->label_time_start
    scr->label_time_start = lv_label_create(scr->container_music);
    lv_label_set_text(scr->label_time_start, "0:00");
    lv_label_set_long_mode(scr->label_time_start, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_time_start, 155, 75);
    lv_obj_set_size(scr->label_time_start, 39, 15);

    // Set style of scr->label_time_start
    lv_obj_set_style_text_color(scr->label_time_start, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_time_start, fs_montserratmedium_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_time_end
    scr->label_time_end = lv_label_create(scr->container_music);
    lv_label_set_text(scr->label_time_end, "2:20");
    lv_label_set_long_mode(scr->label_time_end, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_time_end, 421, 75);
    lv_obj_set_size(scr->label_time_end, 33, 15);

    // Set style of scr->label_time_end
    lv_obj_set_style_text_color(scr->label_time_end, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_time_end, fs_montserratmedium_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_album3
    scr->image_album3 = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_album3, LVGL_IMAGE_PATH(main/play/album3.png));
    lv_img_set_pivot(scr->image_album3, 50, 50);
    lv_img_set_offset_x(scr->image_album3, 0);
    lv_img_set_offset_y(scr->image_album3, 0);
    lv_img_set_angle(scr->image_album3, 0);
    lv_obj_set_pos(scr->image_album3, 20, 19);
    lv_obj_add_flag(scr->image_album3, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_album2
    scr->image_album2 = lv_img_create(scr->container_music);
    lv_img_set_src(scr->image_album2, LVGL_IMAGE_PATH(main/play/album2.png));
    lv_img_set_pivot(scr->image_album2, 50, 50);
    lv_img_set_offset_x(scr->image_album2, 0);
    lv_img_set_offset_y(scr->image_album2, 0);
    lv_img_set_angle(scr->image_album2, 0);
    lv_obj_set_pos(scr->image_album2, 20, 19);
    lv_obj_add_flag(scr->image_album2, LV_OBJ_FLAG_HIDDEN);

    // Init scr->image_function_card3
    scr->image_function_card3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_function_card3, LVGL_IMAGE_PATH(main/right/road.png));
    lv_img_set_pivot(scr->image_function_card3, 50, 50);
    lv_img_set_offset_x(scr->image_function_card3, 0);
    lv_img_set_offset_y(scr->image_function_card3, 0);
    lv_img_set_angle(scr->image_function_card3, 0);
    lv_obj_set_pos(scr->image_function_card3, 718, 396);

    // Init scr->image_function_card2
    scr->image_function_card2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_function_card2, LVGL_IMAGE_PATH(main/right2.png));
    lv_img_set_pivot(scr->image_function_card2, 50, 50);
    lv_img_set_offset_x(scr->image_function_card2, 0);
    lv_img_set_offset_y(scr->image_function_card2, 0);
    lv_img_set_angle(scr->image_function_card2, 0);
    lv_obj_set_pos(scr->image_function_card2, 718, 199);

    // Init scr->image_straight
    scr->image_straight = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_straight, LVGL_IMAGE_PATH(main/straight.png));
    lv_img_set_pivot(scr->image_straight, 50, 50);
    lv_img_set_offset_x(scr->image_straight, 0);
    lv_img_set_offset_y(scr->image_straight, 0);
    lv_img_set_angle(scr->image_straight, 0);
    lv_obj_set_pos(scr->image_straight, 749, 229);

    // Init scr->label_meter
    scr->label_meter = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_meter, "380");
    lv_label_set_long_mode(scr->label_meter, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_meter, 794, 232);
    lv_obj_set_size(scr->label_meter, 76, 42);

    // Set style of scr->label_meter
    lv_obj_set_style_text_color(scr->label_meter, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->label_meter, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_meter, fs_montserratmedium_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_m
    scr->label_m = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_m, "m");
    lv_label_set_long_mode(scr->label_m, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_m, 864, 231);
    lv_obj_set_size(scr->label_m, 28, 34);

    // Set style of scr->label_m
    lv_obj_set_style_text_color(scr->label_m, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_m, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_m, fs_montserratmedium_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_function_card1
    scr->image_function_card1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_function_card1, LVGL_IMAGE_PATH(main/right1.png));
    lv_img_set_pivot(scr->image_function_card1, 50, 50);
    lv_img_set_offset_x(scr->image_function_card1, 0);
    lv_img_set_offset_y(scr->image_function_card1, 0);
    lv_img_set_angle(scr->image_function_card1, 0);
    lv_obj_set_pos(scr->image_function_card1, 718, 45);

    // Init scr->label_temp
    scr->label_temp = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_temp, "23");
    lv_label_set_long_mode(scr->label_temp, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_temp, 733, 56);
    lv_obj_set_size(scr->label_temp, 63, 48);

    // Set style of scr->label_temp
    lv_obj_set_style_text_color(scr->label_temp, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_temp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_temp, fs_montserratmedium_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_address
    scr->label_address = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_address, "Turn right onto Zhuhai Bridge");
    lv_label_set_long_mode(scr->label_address, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_address, 747, 302);
    lv_obj_set_size(scr->label_address, 183, 9);

    // Set style of scr->label_address
    lv_obj_set_style_text_color(scr->label_address, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_address, fs_montserratmedium_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->screen_time
    scr->screen_time = lv_label_create(scr->obj);
    lv_label_set_text(scr->screen_time, "16:17");
    lv_label_set_long_mode(scr->screen_time, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->screen_time, 930, 6);
    lv_obj_set_size(scr->screen_time, 83, 31);

    // Set style of scr->screen_time
    lv_obj_set_style_text_color(scr->screen_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->screen_time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->screen_time, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->screen_time, fs_montserratmedium_29, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_temp
    scr->image_temp = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_temp, LVGL_IMAGE_PATH(main/temp11.png));
    lv_img_set_pivot(scr->image_temp, 50, 50);
    lv_img_set_offset_x(scr->image_temp, 0);
    lv_img_set_offset_y(scr->image_temp, 0);
    lv_img_set_angle(scr->image_temp, 0);
    lv_obj_set_pos(scr->image_temp, 793, 51);

    // Init scr->image_turn_left
    scr->image_turn_left = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_turn_left, LVGL_IMAGE_PATH(screen4/corner _ up-right (1)_31x40.png));
    lv_img_set_pivot(scr->image_turn_left, 50, 50);
    lv_img_set_offset_x(scr->image_turn_left, 0);
    lv_img_set_offset_y(scr->image_turn_left, 0);
    lv_img_set_angle(scr->image_turn_left, 0);
    lv_obj_set_pos(scr->image_turn_left, 749, 229);

    // Init scr->image_turn_right
    scr->image_turn_right = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_turn_right, LVGL_IMAGE_PATH(screen2/corner _ up-right_31x40.png));
    lv_img_set_pivot(scr->image_turn_right, 50, 50);
    lv_img_set_offset_x(scr->image_turn_right, 0);
    lv_img_set_offset_y(scr->image_turn_right, 0);
    lv_img_set_angle(scr->image_turn_right, 0);
    lv_obj_set_pos(scr->image_turn_right, 749, 229);

    // Init scr->label_wait
    scr->label_wait = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_wait, "功能开发中");
    lv_label_set_long_mode(scr->label_wait, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_wait, 384, 18);
    lv_obj_set_size(scr->label_wait, 100, 28);
    lv_obj_add_flag(scr->label_wait, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->label_wait
    lv_obj_set_style_text_color(scr->label_wait, lv_color_hex(0x31fcf9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_wait, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_wait, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->player_rotate
    scr->player_rotate = lv_aic_player_create(scr->obj);
    lv_aic_player_set_src(scr->player_rotate, LVGL_VIDEO_PATH(car_main.mp4));
    lv_aic_player_set_cmd(scr->player_rotate, LV_AIC_PLAYER_CMD_START, NULL);
    lv_obj_set_pos(scr->player_rotate, 169, 133);
    lv_obj_set_size(scr->player_rotate, 516, 263);


}


