/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_montserratmedium_13;
lv_font_t *fs_montserratmedium_34;
lv_font_t *fs_montserratmedium_32;
lv_font_t *fs_montserratmedium_46;
lv_font_t *fs_montserratmedium_8;
lv_font_t *fs_montserratmedium_29;
lv_font_t *fs_droidsansfallback_18;
lv_font_t *fs_droidsansfallback_40;
lv_font_t *fs_droidsansfallback_22;
lv_font_t *fs_montserratmedium_40;
lv_font_t *fs_montserratmedium_38;
lv_font_t *fs_montserratmedium_48;
lv_font_t *fs_montserratmedium_14;
lv_font_t *fs_montserratmedium_62;
lv_font_t *fs_montserratmedium_22;
lv_font_t *fs_montserratmedium_80;
lv_font_t *fs_montserratmedium_42;

void ui_init(void)
{
    fs_montserratmedium_13 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 13);
    fs_montserratmedium_34 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 34);
    fs_montserratmedium_32 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 32);
    fs_montserratmedium_46 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 46);
    fs_montserratmedium_8 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 8);
    fs_montserratmedium_29 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 29);
    fs_droidsansfallback_18 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 18);
    fs_droidsansfallback_40 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 40);
    fs_droidsansfallback_22 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 22);
    fs_montserratmedium_40 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 40);
    fs_montserratmedium_38 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 38);
    fs_montserratmedium_48 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 48);
    fs_montserratmedium_14 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 14);
    fs_montserratmedium_62 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 62);
    fs_montserratmedium_22 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 22);
    fs_montserratmedium_80 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 80);
    fs_montserratmedium_42 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 42);
    if (!fs_montserratmedium_13) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_13");
    	return;
    }
    if (!fs_montserratmedium_34) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_34");
    	return;
    }
    if (!fs_montserratmedium_32) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_32");
    	return;
    }
    if (!fs_montserratmedium_46) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_46");
    	return;
    }
    if (!fs_montserratmedium_8) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_8");
    	return;
    }
    if (!fs_montserratmedium_29) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_29");
    	return;
    }
    if (!fs_droidsansfallback_18) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_18");
    	return;
    }
    if (!fs_droidsansfallback_40) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_40");
    	return;
    }
    if (!fs_droidsansfallback_22) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_22");
    	return;
    }
    if (!fs_montserratmedium_40) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_40");
    	return;
    }
    if (!fs_montserratmedium_38) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_38");
    	return;
    }
    if (!fs_montserratmedium_48) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_48");
    	return;
    }
    if (!fs_montserratmedium_14) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_14");
    	return;
    }
    if (!fs_montserratmedium_62) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_62");
    	return;
    }
    if (!fs_montserratmedium_22) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_22");
    	return;
    }
    if (!fs_montserratmedium_80) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_80");
    	return;
    }
    if (!fs_montserratmedium_42) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_42");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    screen_4_create(&ui_manager);
    lv_scr_load(screen_4_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
