/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_home;
    lv_obj_t *image_home;
    lv_obj_t *container_camera;
    lv_obj_t *image_camera;
    lv_obj_t *container_phone;
    lv_obj_t *image_phone;
    lv_obj_t *container_play;
    lv_obj_t *image_play;
    lv_obj_t *container_set;
    lv_obj_t *image_set;
    lv_obj_t *container_music;
    lv_obj_t *image_album1;
    lv_obj_t *image_pre;
    lv_obj_t *image_back;
    lv_obj_t *image_stop;
    lv_obj_t *image_forward;
    lv_obj_t *image_next;
    lv_obj_t *bar_progress;
    lv_obj_t *image_start;
    lv_obj_t *label_time_start;
    lv_obj_t *label_time_end;
    lv_obj_t *image_album3;
    lv_obj_t *image_album2;
    lv_obj_t *image_function_card3;
    lv_obj_t *image_function_card2;
    lv_obj_t *image_straight;
    lv_obj_t *label_meter;
    lv_obj_t *label_m;
    lv_obj_t *image_function_card1;
    lv_obj_t *label_temp;
    lv_obj_t *label_address;
    lv_obj_t *screen_time;
    lv_obj_t *image_temp;
    lv_obj_t *image_turn_left;
    lv_obj_t *image_turn_right;
    lv_obj_t *label_wait;
    lv_obj_t *player_rotate;
} screen_main_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *container_home;
    lv_obj_t *image_home;
    lv_obj_t *container_camera;
    lv_obj_t *image_camera;
    lv_obj_t *container_phone;
    lv_obj_t *image_phone;
    lv_obj_t *container_play;
    lv_obj_t *image_play;
    lv_obj_t *container_set;
    lv_obj_t *image_set;
    lv_obj_t *container_car;
    lv_obj_t *image_2;
    lv_obj_t *image_3;
    lv_obj_t *image_1;
    lv_obj_t *container_text;
    lv_obj_t *text_1;
    lv_obj_t *text_2;
    lv_obj_t *text_3;
    lv_obj_t *label_wait;
} screen_1_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_arc_up;
    lv_obj_t *image_arc_down;
    lv_obj_t *image_shadow;
    lv_obj_t *container_gear;
    lv_obj_t *image_P;
    lv_obj_t *image_R;
    lv_obj_t *image_N;
    lv_obj_t *image_D;
    lv_obj_t *image_S;
    lv_obj_t *player_car_move;
    lv_obj_t *container_information;
    lv_obj_t *image_light;
    lv_obj_t *image_turn_right;
    lv_obj_t *label_address;
    lv_obj_t *label_meter;
    lv_obj_t *label_m;
    lv_obj_t *image_straight;
    lv_obj_t *image_turn_left;
    lv_obj_t *container_left;
    lv_obj_t *left_circlr_img;
    lv_obj_t *arc_speed;
    lv_obj_t *label_speed;
    lv_obj_t *label_mileage;
    lv_obj_t *image_km;
    lv_obj_t *container_right;
    lv_obj_t *right_circlr_img;
    lv_obj_t *image_point;
    lv_obj_t *arc_rmp;
    lv_obj_t *image_rmp;
    lv_obj_t *label_left;
    lv_obj_t *label_right;
    lv_obj_t *screen2_time;
    lv_obj_t *image_1;
} screen_2_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_cloud;
    lv_obj_t *image_shadow;
    lv_obj_t *image_arc_down;
    lv_obj_t *player_car_move;
    lv_obj_t *right_circlr_img;
    lv_obj_t *left_circlr_img;
    lv_obj_t *screen3_time;
    lv_obj_t *image_point;
    lv_obj_t *label_km;
    lv_obj_t *image_km;
    lv_obj_t *image_rmp;
    lv_obj_t *label_left;
    lv_obj_t *label_right;
    lv_obj_t *label_temp;
    lv_obj_t *image_P;
    lv_obj_t *image_bar1;
    lv_obj_t *image_bar2;
    lv_obj_t *image_bar3;
    lv_obj_t *image_bar4;
    lv_obj_t *image_bar5;
    lv_obj_t *image_bar6;
    lv_obj_t *image_bar7;
    lv_obj_t *image_2;
} screen_3_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_arc_down;
    lv_obj_t *image_shadow;
    lv_obj_t *image_arc_up;
    lv_obj_t *player_car_move;
    lv_obj_t *right_circlr_img;
    lv_obj_t *left_circlr_img;
    lv_obj_t *container_p;
    lv_obj_t *image_P;
    lv_obj_t *container_information;
    lv_obj_t *label_meter;
    lv_obj_t *label_m;
    lv_obj_t *image_light;
    lv_obj_t *label_address;
    lv_obj_t *image_rmp;
    lv_obj_t *image_km;
    lv_obj_t *label_km;
    lv_obj_t *image_point;
    lv_obj_t *image_cloud1;
    lv_obj_t *label_left;
    lv_obj_t *label_right;
    lv_obj_t *image_turn;
    lv_obj_t *container_gradient1;
    lv_obj_t *image_gradient1;
    lv_obj_t *container_gradient2;
    lv_obj_t *image_gradient2;
    lv_obj_t *screen4_time;
    lv_obj_t *image_temp;
    lv_obj_t *image_cloud2;
    lv_obj_t *image_3;
} screen_4_t;


typedef struct {
    bool auto_del;
    screen_main_t screen_main;
    screen_1_t screen_1;
    screen_2_t screen_2;
    screen_3_t screen_3;
    screen_4_t screen_4;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_main_t *screen_main_get(ui_manager_t *ui)
{
    return &ui->screen_main;
}

static inline screen_1_t *screen_1_get(ui_manager_t *ui)
{
    return &ui->screen_1;
}

static inline screen_2_t *screen_2_get(ui_manager_t *ui)
{
    return &ui->screen_2;
}

static inline screen_3_t *screen_3_get(ui_manager_t *ui)
{
    return &ui->screen_3;
}

static inline screen_4_t *screen_4_get(ui_manager_t *ui)
{
    return &ui->screen_4;
}


void screen_main_create(ui_manager_t *ui);
void screen_1_create(ui_manager_t *ui);
void screen_2_create(ui_manager_t *ui);
void screen_3_create(ui_manager_t *ui);
void screen_4_create(ui_manager_t *ui);


extern lv_font_t *fs_montserratmedium_13;
extern lv_font_t *fs_montserratmedium_34;
extern lv_font_t *fs_montserratmedium_32;
extern lv_font_t *fs_montserratmedium_46;
extern lv_font_t *fs_montserratmedium_8;
extern lv_font_t *fs_montserratmedium_29;
extern lv_font_t *fs_droidsansfallback_18;
extern lv_font_t *fs_droidsansfallback_40;
extern lv_font_t *fs_droidsansfallback_22;
extern lv_font_t *fs_montserratmedium_40;
extern lv_font_t *fs_montserratmedium_38;
extern lv_font_t *fs_montserratmedium_48;
extern lv_font_t *fs_montserratmedium_14;
extern lv_font_t *fs_montserratmedium_62;
extern lv_font_t *fs_montserratmedium_22;
extern lv_font_t *fs_montserratmedium_80;
extern lv_font_t *fs_montserratmedium_42;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
