/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_custom_load_start(void) {
}

static void screen_load_start (lv_event_t *e) {
    screen_custom_load_start();
}


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_image_opa(scr->obj, 99, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x211043), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(scr->obj, lv_color_hex(0x295ca3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(scr->obj, 101, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(scr->obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->arc_2
    scr->arc_2 = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->arc_2, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_2, 0, 100);
    lv_arc_set_value(scr->arc_2, 40);
    lv_arc_set_bg_angles(scr->arc_2, 0, 360);
    lv_arc_set_angles(scr->arc_2, 0, 120);
    lv_arc_set_rotation(scr->arc_2, 0);
    lv_arc_set_change_rate(scr->arc_2, 720);
    lv_obj_set_pos(scr->arc_2, 275, 715);
    lv_obj_set_size(scr->arc_2, 180, 180);

    // Set style of scr->arc_2
    lv_obj_set_style_arc_width(scr->arc_2, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_2, lv_color_hex(0x166fec), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->arc_1
    scr->arc_1 = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->arc_1, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->arc_1, 0, 100);
    lv_arc_set_value(scr->arc_1, 50);
    lv_arc_set_bg_angles(scr->arc_1, 0, 360);
    lv_arc_set_angles(scr->arc_1, 0, 180);
    lv_arc_set_rotation(scr->arc_1, 0);
    lv_arc_set_change_rate(scr->arc_1, 720);
    lv_obj_set_pos(scr->arc_1, 25, 715);
    lv_obj_set_size(scr->arc_1, 180, 180);

    // Set style of scr->arc_1
    lv_obj_set_style_arc_width(scr->arc_1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->arc_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(scr->arc_1, lv_color_hex(0x166fec), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->top_img
    scr->top_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->top_img, LVGL_IMAGE_PATH(top.png));
    lv_img_set_pivot(scr->top_img, 50, 50);
    lv_img_set_offset_x(scr->top_img, 0);
    lv_img_set_offset_y(scr->top_img, 0);
    lv_img_set_angle(scr->top_img, 0);
    lv_obj_set_pos(scr->top_img, 0, 0);

    // Init scr->bar_cont
    scr->bar_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->bar_cont, 0, 80);
    lv_obj_set_size(scr->bar_cont, 480, 440);
    lv_obj_set_scrollbar_mode(scr->bar_cont, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->bar_cont
    lv_obj_set_style_radius(scr->bar_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->bar_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->bar_cont, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->bar_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->bar_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->bar_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->bar_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(scr->bar_cont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->o2_bar
    scr->o2_bar = lv_bar_create(scr->bar_cont);
    lv_bar_set_mode(scr->o2_bar, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->o2_bar, 0, 100);
    lv_bar_set_value(scr->o2_bar, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->o2_bar, 118, 18);
    lv_obj_set_size(scr->o2_bar, 60, 370);

    // Set style of scr->o2_bar
    lv_obj_set_style_bg_opa(scr->o2_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->o2_bar, lv_color_hex(0x1f5b84), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->o2_bar, lv_color_hex(0x253976), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->air_bar
    scr->air_bar = lv_bar_create(scr->bar_cont);
    lv_bar_set_mode(scr->air_bar, LV_BAR_MODE_NORMAL);
    lv_bar_set_range(scr->air_bar, 0, 100);
    lv_bar_set_value(scr->air_bar, 0, LV_ANIM_OFF);
    lv_obj_set_pos(scr->air_bar, 298, 18);
    lv_obj_set_size(scr->air_bar, 60, 370);

    // Set style of scr->air_bar
    lv_obj_set_style_bg_opa(scr->air_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->air_bar, lv_color_hex(0x1f5b84), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->air_bar, lv_color_hex(0x253976), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->scale_cont
    scr->scale_cont = lv_obj_create(scr->bar_cont);
    lv_obj_set_pos(scr->scale_cont, 183, 0);
    lv_obj_set_size(scr->scale_cont, 110, 380);
    lv_obj_set_scrollbar_mode(scr->scale_cont, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->scale_cont
    lv_obj_set_style_radius(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->scale_cont, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->scale_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->scale_label
    scr->scale_label = lv_label_create(scr->scale_cont);
    lv_label_set_text(scr->scale_label, "_20_\n\n_15_\n\n_10_\n\n_5_\n\n_1_\n\n_0.5_\n\n_0_");
    lv_label_set_long_mode(scr->scale_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->scale_label, 20, 25);
    lv_obj_set_size(scr->scale_label, 70, 350);

    // Set style of scr->scale_label
    lv_obj_set_style_text_color(scr->scale_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->scale_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->scale_label, fs_montserratmedium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_8
    scr->label_8 = lv_label_create(scr->bar_cont);
    lv_label_set_text(scr->label_8, "O2");
    lv_label_set_long_mode(scr->label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_8, 125, 390);
    lv_obj_set_size(scr->label_8, 47, 28);

    // Set style of scr->label_8
    lv_obj_set_style_text_color(scr->label_8, lv_color_hex(0xff9500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_8, fs_montserratmedium_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_9
    scr->label_9 = lv_label_create(scr->bar_cont);
    lv_label_set_text(scr->label_9, "Air");
    lv_label_set_long_mode(scr->label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_9, 300, 390);
    lv_obj_set_size(scr->label_9, 54, 28);

    // Set style of scr->label_9
    lv_obj_set_style_text_color(scr->label_9, lv_color_hex(0x00aaff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_9, fs_montserratmedium_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_17
    scr->label_17 = lv_label_create(scr->bar_cont);
    lv_label_set_text(scr->label_17, "1/min");
    lv_label_set_long_mode(scr->label_17, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_17, 188, 394);
    lv_obj_set_size(scr->label_17, 100, 32);

    // Set style of scr->label_17
    lv_obj_set_style_text_color(scr->label_17, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_17, fs_montserratmedium_23, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->data_cont
    scr->data_cont = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->data_cont, 0, 525);
    lv_obj_set_size(scr->data_cont, 480, 135);
    lv_obj_set_scrollbar_mode(scr->data_cont, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->data_cont
    lv_obj_set_style_radius(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->data_cont, lv_color_hex(0xeff8f5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->data_cont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->fio2_num
    scr->fio2_num = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->fio2_num, "60");
    lv_label_set_long_mode(scr->fio2_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->fio2_num, 23, 55);
    lv_obj_set_size(scr->fio2_num, 70, 80);

    // Set style of scr->fio2_num
    lv_obj_set_style_text_color(scr->fio2_num, lv_color_hex(0xffff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->fio2_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->fio2_num, fs_droidsansfallback_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->peepe_num
    scr->peepe_num = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->peepe_num, "8");
    lv_label_set_long_mode(scr->peepe_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->peepe_num, 200, 55);
    lv_obj_set_size(scr->peepe_num, 70, 80);

    // Set style of scr->peepe_num
    lv_obj_set_style_text_color(scr->peepe_num, lv_color_hex(0x01afee), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->peepe_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->peepe_num, fs_droidsansfallback_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->ecg_num
    scr->ecg_num = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->ecg_num, "92");
    lv_label_set_long_mode(scr->ecg_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->ecg_num, 332, 55);
    lv_obj_set_size(scr->ecg_num, 70, 80);

    // Set style of scr->ecg_num
    lv_obj_set_style_text_color(scr->ecg_num, lv_color_hex(0xfa5a7f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->ecg_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->ecg_num, fs_droidsansfallback_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line_2
    scr->line_2 = lv_line_create(scr->data_cont);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_2_point[] ={{0, 0}, {0, 100}};
#else
    static lv_point_precise_t line_2_point[] ={{0, 0}, {0, 100}};
#endif
    lv_line_set_points(scr->line_2, line_2_point, 2);
    lv_obj_set_pos(scr->line_2, 300, 25);
    lv_obj_set_size(scr->line_2, 20, 100);

    // Set style of scr->line_2
    lv_obj_set_style_line_width(scr->line_2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(scr->line_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->line_3
    scr->line_3 = lv_line_create(scr->data_cont);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t line_3_point[] ={{0, 0}, {0, 100}};
#else
    static lv_point_precise_t line_3_point[] ={{0, 0}, {0, 100}};
#endif
    lv_line_set_points(scr->line_3, line_3_point, 2);
    lv_obj_set_pos(scr->line_3, 165, 25);
    lv_obj_set_size(scr->line_3, 15, 100);

    // Set style of scr->line_3
    lv_obj_set_style_line_width(scr->line_3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(scr->line_3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_12
    scr->label_12 = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->label_12, "%");
    lv_label_set_long_mode(scr->label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_12, 90, 90);
    lv_obj_set_size(scr->label_12, 50, 30);

    // Set style of scr->label_12
    lv_obj_set_style_text_color(scr->label_12, lv_color_hex(0xffff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_12, fs_montserratmedium_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_11
    scr->label_11 = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->label_11, "FiO2");
    lv_label_set_long_mode(scr->label_11, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_11, 25, 30);
    lv_obj_set_size(scr->label_11, 70, 25);

    // Set style of scr->label_11
    lv_obj_set_style_text_color(scr->label_11, lv_color_hex(0xffff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_11, fs_montserratmedium_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_13
    scr->label_13 = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->label_13, "PEEPe");
    lv_label_set_long_mode(scr->label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_13, 200, 30);
    lv_obj_set_size(scr->label_13, 80, 25);

    // Set style of scr->label_13
    lv_obj_set_style_text_color(scr->label_13, lv_color_hex(0x01afee), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_13, fs_droidsansfallback_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_14
    scr->label_14 = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->label_14, "HR/ECG");
    lv_label_set_long_mode(scr->label_14, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_14, 320, 30);
    lv_obj_set_size(scr->label_14, 100, 25);

    // Set style of scr->label_14
    lv_obj_set_style_text_color(scr->label_14, lv_color_hex(0xfa5a7f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_14, fs_droidsansfallback_25, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_16
    scr->label_16 = lv_label_create(scr->data_cont);
    lv_label_set_text(scr->label_16, "1/min");
    lv_label_set_long_mode(scr->label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_16, 405, 95);
    lv_obj_set_size(scr->label_16, 60, 25);

    // Set style of scr->label_16
    lv_obj_set_style_text_color(scr->label_16, lv_color_hex(0xfa5a7f), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_16, fs_droidsansfallback_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_6
    scr->container_6 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_6, 70, 760);
    lv_obj_set_size(scr->container_6, 90, 90);
    lv_obj_set_scrollbar_mode(scr->container_6, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_6
    lv_obj_set_style_radius(scr->container_6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(scr->container_6, lv_color_hex(0x0e25cf), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(scr->container_6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_6, lv_color_hex(0x1779f1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->container_6, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->vt_1
    scr->vt_1 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->vt_1, "45");
    lv_label_set_long_mode(scr->vt_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->vt_1, 15, 18);
    lv_obj_set_size(scr->vt_1, 56, 30);

    // Set style of scr->vt_1
    lv_obj_set_style_text_color(scr->vt_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->vt_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->vt_1, fs_montserratmedium_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_30
    scr->label_30 = lv_label_create(scr->container_6);
    lv_label_set_text(scr->label_30, "(VT Ml)");
    lv_label_set_long_mode(scr->label_30, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_30, 3, 48);
    lv_obj_set_size(scr->label_30, 81, 22);

    // Set style of scr->label_30
    lv_obj_set_style_text_color(scr->label_30, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_30, fs_montserratmedium_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->container_7
    scr->container_7 = lv_obj_create(scr->obj);
    lv_obj_set_pos(scr->container_7, 320, 760);
    lv_obj_set_size(scr->container_7, 90, 90);
    lv_obj_set_scrollbar_mode(scr->container_7, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->container_7
    lv_obj_set_style_radius(scr->container_7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(scr->container_7, lv_color_hex(0x0d2acf), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(scr->container_7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->container_7, lv_color_hex(0x157cf1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(scr->container_7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->container_7, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->vt_2
    scr->vt_2 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->vt_2, "500");
    lv_label_set_long_mode(scr->vt_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->vt_2, 14, 18);
    lv_obj_set_size(scr->vt_2, 58, 30);

    // Set style of scr->vt_2
    lv_obj_set_style_text_color(scr->vt_2, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->vt_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->vt_2, fs_montserratmedium_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_31
    scr->label_31 = lv_label_create(scr->container_7);
    lv_label_set_text(scr->label_31, "(VT Ml)");
    lv_label_set_long_mode(scr->label_31, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_31, 3, 48);
    lv_obj_set_size(scr->label_31, 81, 22);

    // Set style of scr->label_31
    lv_obj_set_style_text_color(scr->label_31, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->label_31, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->label_31, fs_montserratmedium_18, LV_PART_MAIN | LV_STATE_DEFAULT);


}


