/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *arc_2;
    lv_obj_t *arc_1;
    lv_obj_t *top_img;
    lv_obj_t *bar_cont;
    lv_obj_t *o2_bar;
    lv_obj_t *air_bar;
    lv_obj_t *scale_cont;
    lv_obj_t *scale_label;
    lv_obj_t *label_8;
    lv_obj_t *label_9;
    lv_obj_t *label_17;
    lv_obj_t *data_cont;
    lv_obj_t *fio2_num;
    lv_obj_t *peepe_num;
    lv_obj_t *ecg_num;
    lv_obj_t *line_2;
    lv_obj_t *line_3;
    lv_obj_t *label_12;
    lv_obj_t *label_11;
    lv_obj_t *label_13;
    lv_obj_t *label_14;
    lv_obj_t *label_16;
    lv_obj_t *container_6;
    lv_obj_t *vt_1;
    lv_obj_t *label_30;
    lv_obj_t *container_7;
    lv_obj_t *vt_2;
    lv_obj_t *label_31;
} screen_t;


typedef struct {
    bool auto_del;
    screen_t screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}


void screen_create(ui_manager_t *ui);


extern lv_font_t *fs_droidsansfallback_60;
extern lv_font_t *fs_montserratmedium_18;
extern lv_font_t *fs_montserratmedium_23;
extern lv_font_t *fs_montserratmedium_25;
extern lv_font_t *fs_montserratmedium_26;
extern lv_font_t *fs_montserratmedium_28;
extern lv_font_t *fs_droidsansfallback_25;
extern lv_font_t *fs_droidsansfallback_22;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
