/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void Devices_to_do_list_imgbtn_pressed (lv_event_t *e) {
    lv_obj_t *Devices_todo_label = Devices_get(&ui_manager)->todo_label;
    lv_obj_clear_flag(Devices_todo_label, LV_OBJ_FLAG_HIDDEN);
    lv_anim_t anim_Devices_todo_label_x;
    lv_anim_init(&anim_Devices_todo_label_x);
    lv_anim_set_var(&anim_Devices_todo_label_x, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_Devices_todo_label_x, 563, 563);
    lv_anim_set_time(&anim_Devices_todo_label_x, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_x, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_x, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_x, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_x);

    lv_anim_t anim_Devices_todo_label_y;
    lv_anim_init(&anim_Devices_todo_label_y);
    lv_anim_set_var(&anim_Devices_todo_label_y, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_Devices_todo_label_y, 3, -50);
    lv_anim_set_time(&anim_Devices_todo_label_y, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_y, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_y, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_y, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_y);

}

static void Devices_to_do_list_imgbtn_pressing (lv_event_t *e) {
    lv_obj_t *Devices_to_do_list_label = Devices_get(&ui_manager)->to_do_list_label;
    lv_obj_set_style_text_color(Devices_to_do_list_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_to_do_list_imgbtn_released (lv_event_t *e) {
    lv_obj_t *Devices_to_do_list_label = Devices_get(&ui_manager)->to_do_list_label;
    lv_obj_set_style_text_color(Devices_to_do_list_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_statictics_imgbtn_pressed (lv_event_t *e) {
    lv_obj_t *Devices_statictics_label = Devices_get(&ui_manager)->statictics_label;
    lv_obj_set_style_text_color(Devices_statictics_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *Devices_todo_label = Devices_get(&ui_manager)->todo_label;
    lv_obj_clear_flag(Devices_todo_label, LV_OBJ_FLAG_HIDDEN);
    lv_anim_t anim_Devices_todo_label_x;
    lv_anim_init(&anim_Devices_todo_label_x);
    lv_anim_set_var(&anim_Devices_todo_label_x, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_Devices_todo_label_x, 563, 563);
    lv_anim_set_time(&anim_Devices_todo_label_x, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_x, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_x, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_x, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_x);

    lv_anim_t anim_Devices_todo_label_y;
    lv_anim_init(&anim_Devices_todo_label_y);
    lv_anim_set_var(&anim_Devices_todo_label_y, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_Devices_todo_label_y, 3, -50);
    lv_anim_set_time(&anim_Devices_todo_label_y, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_y, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_y, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_y, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_y);

}

static void Devices_statictics_imgbtn_pressing (lv_event_t *e) {
    lv_obj_t *Devices_statictics_label = Devices_get(&ui_manager)->statictics_label;
    lv_obj_set_style_text_color(Devices_statictics_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_statictics_imgbtn_released (lv_event_t *e) {
    lv_obj_t *Devices_statictics_label = Devices_get(&ui_manager)->statictics_label;
    lv_obj_set_style_text_color(Devices_statictics_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_cooking_imgbtn_pressed (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create Cooking
        Cooking_create(&ui_manager);
        // load Cooking
        lv_scr_load_anim(Cooking_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 1, 0, ui_manager.auto_del);
    }
    lv_obj_t *Devices_cooking_label = Devices_get(&ui_manager)->cooking_label;
    lv_obj_set_style_text_color(Devices_cooking_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_cooking_imgbtn_pressing (lv_event_t *e) {
    lv_obj_t *Devices_cooking_label = Devices_get(&ui_manager)->cooking_label;
    lv_obj_set_style_text_color(Devices_cooking_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_cooking_imgbtn_released (lv_event_t *e) {
    lv_obj_t *Devices_cooking_label = Devices_get(&ui_manager)->cooking_label;
    lv_obj_set_style_text_color(Devices_cooking_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_cooking_label_pressed (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create Cooking
        Cooking_create(&ui_manager);
        // load Cooking
        lv_scr_load_anim(Cooking_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}

static void Devices_cooking_label_pressing (lv_event_t *e) {
    lv_obj_t *Devices_cooking_label = Devices_get(&ui_manager)->cooking_label;
    lv_obj_set_style_text_color(Devices_cooking_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_cooking_label_released (lv_event_t *e) {
    lv_obj_t *Devices_cooking_label = Devices_get(&ui_manager)->cooking_label;
    lv_obj_set_style_text_color(Devices_cooking_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_devices_ingbtn_pressed (lv_event_t *e) {
    lv_obj_t *Devices_devices_label = Devices_get(&ui_manager)->devices_label;
    lv_obj_set_style_text_color(Devices_devices_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *Devices_todo_label = Devices_get(&ui_manager)->todo_label;
    lv_obj_clear_flag(Devices_todo_label, LV_OBJ_FLAG_HIDDEN);
    lv_anim_t anim_Devices_todo_label_x;
    lv_anim_init(&anim_Devices_todo_label_x);
    lv_anim_set_var(&anim_Devices_todo_label_x, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_Devices_todo_label_x, 563, 563);
    lv_anim_set_time(&anim_Devices_todo_label_x, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_x, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_x, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_x, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_x);

    lv_anim_t anim_Devices_todo_label_y;
    lv_anim_init(&anim_Devices_todo_label_y);
    lv_anim_set_var(&anim_Devices_todo_label_y, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_Devices_todo_label_y, 3, -50);
    lv_anim_set_time(&anim_Devices_todo_label_y, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_y, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_y, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_y, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_y);

}

static void Devices_devices_ingbtn_pressing (lv_event_t *e) {
    lv_obj_t *Devices_devices_label = Devices_get(&ui_manager)->devices_label;
    lv_obj_set_style_text_color(Devices_devices_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_devices_ingbtn_released (lv_event_t *e) {
    lv_obj_t *Devices_devices_label = Devices_get(&ui_manager)->devices_label;
    lv_obj_set_style_text_color(Devices_devices_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_setting_imgbtn_pressed (lv_event_t *e) {
    lv_obj_t *Devices_setting_label = Devices_get(&ui_manager)->setting_label;
    lv_obj_set_style_text_color(Devices_setting_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t *Devices_todo_label = Devices_get(&ui_manager)->todo_label;
    lv_obj_clear_flag(Devices_todo_label, LV_OBJ_FLAG_HIDDEN);
    lv_anim_t anim_Devices_todo_label_x;
    lv_anim_init(&anim_Devices_todo_label_x);
    lv_anim_set_var(&anim_Devices_todo_label_x, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_Devices_todo_label_x, 563, 563);
    lv_anim_set_time(&anim_Devices_todo_label_x, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_x, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_x, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_x, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_x);

    lv_anim_t anim_Devices_todo_label_y;
    lv_anim_init(&anim_Devices_todo_label_y);
    lv_anim_set_var(&anim_Devices_todo_label_y, Devices_todo_label);
    lv_anim_set_exec_cb(&anim_Devices_todo_label_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_Devices_todo_label_y, 3, -50);
    lv_anim_set_time(&anim_Devices_todo_label_y, 1500);
    lv_anim_set_repeat_count(&anim_Devices_todo_label_y, 1);
    lv_anim_set_delay(&anim_Devices_todo_label_y, 1000);
    lv_anim_set_path_cb(&anim_Devices_todo_label_y, lv_anim_path_linear);
    lv_anim_start(&anim_Devices_todo_label_y);

}

static void Devices_setting_imgbtn_pressing (lv_event_t *e) {
    lv_obj_t *Devices_setting_label = Devices_get(&ui_manager)->setting_label;
    lv_obj_set_style_text_color(Devices_setting_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static void Devices_setting_imgbtn_released (lv_event_t *e) {
    lv_obj_t *Devices_setting_label = Devices_get(&ui_manager)->setting_label;
    lv_obj_set_style_text_color(Devices_setting_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
}


void Devices_create(ui_manager_t *ui)
{
    Devices_t *scr = Devices_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_clear_flag(scr->obj, LV_OBJ_FLAG_SCROLLABLE);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->left_bg
    scr->left_bg = lv_img_create(scr->obj);
    lv_img_set_src(scr->left_bg, LVGL_IMAGE_PATH(left_bg_q95.jpg));
    lv_img_set_pivot(scr->left_bg, 50, 50);
    lv_img_set_angle(scr->left_bg, 0);
    lv_obj_set_style_img_opa(scr->left_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->left_bg, 0, 0);

    // Init scr->logo
    scr->logo = lv_img_create(scr->obj);
    lv_img_set_src(scr->logo, LVGL_IMAGE_PATH(artinchip_logo.png));
    lv_img_set_pivot(scr->logo, 50, 50);
    lv_img_set_angle(scr->logo, 0);
    lv_obj_set_style_img_opa(scr->logo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->logo, 4, 16);

    // Init scr->logo_name
    scr->logo_name = lv_label_create(scr->obj);
    lv_label_set_text(scr->logo_name, "Artinchip");
    lv_label_set_long_mode(scr->logo_name, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->logo_name, 85, 35);
    lv_obj_set_size(scr->logo_name, 100, 32);

    // Set style of scr->logo_name
    lv_obj_set_style_text_font(scr->logo_name, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->logo_name, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->copyright
    scr->copyright = lv_label_create(scr->obj);
    lv_label_set_text(scr->copyright, "Co.Apache-2.0");
    lv_label_set_long_mode(scr->copyright, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->copyright, 85, 66);
    lv_obj_set_size(scr->copyright, 100, 32);

    // Set style of scr->copyright
    lv_obj_set_style_text_font(scr->copyright, fs_alibabasans_bold_13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->copyright, lv_color_hex(0xc9c9c9), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->to_do_list_imgbtn
    scr->to_do_list_imgbtn = lv_imgbtn_create(scr->obj);
    lv_imgbtn_set_src(scr->to_do_list_imgbtn, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(todo_list_icon.png), NULL);
    lv_imgbtn_set_src(scr->to_do_list_imgbtn, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(todo_list_icon_green.png), NULL);
    lv_obj_t *Devices_to_do_list_imgbtn_label = lv_label_create(scr->to_do_list_imgbtn);
    lv_label_set_text(Devices_to_do_list_imgbtn_label, "");
    lv_obj_align(Devices_to_do_list_imgbtn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->to_do_list_imgbtn, 22, 121);
    lv_obj_set_size(scr->to_do_list_imgbtn, 32, 32);

    // Set style of scr->to_do_list_imgbtn
    lv_obj_set_style_text_font(scr->to_do_list_imgbtn, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->to_do_list_imgbtn
    lv_obj_add_event_cb(scr->to_do_list_imgbtn, Devices_to_do_list_imgbtn_pressed, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(scr->to_do_list_imgbtn, Devices_to_do_list_imgbtn_pressing, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(scr->to_do_list_imgbtn, Devices_to_do_list_imgbtn_released, LV_EVENT_RELEASED, NULL);

    // Init scr->to_do_list_label
    scr->to_do_list_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->to_do_list_label, "To-do-list");
    lv_label_set_long_mode(scr->to_do_list_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->to_do_list_label, 60, 122);
    lv_obj_set_size(scr->to_do_list_label, 123, 32);

    // Set style of scr->to_do_list_label
    lv_obj_set_style_text_font(scr->to_do_list_label, fs_alibabasans_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->to_do_list_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->statictics_imgbtn
    scr->statictics_imgbtn = lv_imgbtn_create(scr->obj);
    lv_imgbtn_set_src(scr->statictics_imgbtn, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(statistics_icon.png), NULL);
    lv_imgbtn_set_src(scr->statictics_imgbtn, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(statistics_icon_green.png), NULL);
    lv_obj_t *Devices_statictics_imgbtn_label = lv_label_create(scr->statictics_imgbtn);
    lv_label_set_text(Devices_statictics_imgbtn_label, "");
    lv_obj_align(Devices_statictics_imgbtn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->statictics_imgbtn, 22, 179);
    lv_obj_set_size(scr->statictics_imgbtn, 32, 32);

    // Set style of scr->statictics_imgbtn
    lv_obj_set_style_text_font(scr->statictics_imgbtn, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->statictics_imgbtn
    lv_obj_add_event_cb(scr->statictics_imgbtn, Devices_statictics_imgbtn_pressed, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(scr->statictics_imgbtn, Devices_statictics_imgbtn_pressing, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(scr->statictics_imgbtn, Devices_statictics_imgbtn_released, LV_EVENT_RELEASED, NULL);

    // Init scr->statictics_label
    scr->statictics_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->statictics_label, "Statictics");
    lv_label_set_long_mode(scr->statictics_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->statictics_label, 60, 181);
    lv_obj_set_size(scr->statictics_label, 100, 32);

    // Set style of scr->statictics_label
    lv_obj_set_style_text_font(scr->statictics_label, fs_alibabasans_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->statictics_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->left_bg_line0
    scr->left_bg_line0 = lv_line_create(scr->obj);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t left_bg_line0_point[] ={{0, 0}, {180, 0}};
#else
    static lv_point_precise_t left_bg_line0_point[] ={{0, 0}, {180, 0}};
#endif
    lv_line_set_points(scr->left_bg_line0, left_bg_line0_point, 2);
    lv_obj_set_pos(scr->left_bg_line0, 10, 101);
    lv_obj_set_size(scr->left_bg_line0, 185, 1);

    // Set style of scr->left_bg_line0
    lv_obj_set_style_line_color(scr->left_bg_line0, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(scr->left_bg_line0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qr_code_imgbtn
    scr->qr_code_imgbtn = lv_imgbtn_create(scr->obj);
    lv_imgbtn_set_src(scr->qr_code_imgbtn, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(qr_code_icon_green.png), NULL);
    lv_imgbtn_set_src(scr->qr_code_imgbtn, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(qr_code_icon_green.png), NULL);
    lv_obj_t *Devices_qr_code_imgbtn_label = lv_label_create(scr->qr_code_imgbtn);
    lv_label_set_text(Devices_qr_code_imgbtn_label, "");
    lv_obj_align(Devices_qr_code_imgbtn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->qr_code_imgbtn, 22, 237);
    lv_obj_set_size(scr->qr_code_imgbtn, 32, 32);

    // Set style of scr->qr_code_imgbtn
    lv_obj_set_style_text_font(scr->qr_code_imgbtn, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qr_code_label
    scr->qr_code_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->qr_code_label, "QR code");
    lv_label_set_long_mode(scr->qr_code_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->qr_code_label, 60, 238);
    lv_obj_set_size(scr->qr_code_label, 100, 32);

    // Set style of scr->qr_code_label
    lv_obj_set_style_text_font(scr->qr_code_label, fs_alibabasans_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->qr_code_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->cooking_imgbtn
    scr->cooking_imgbtn = lv_imgbtn_create(scr->obj);
    lv_imgbtn_set_src(scr->cooking_imgbtn, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(cook_icon.png), NULL);
    lv_imgbtn_set_src(scr->cooking_imgbtn, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(cook_icon_green.png), NULL);
    lv_obj_t *Devices_cooking_imgbtn_label = lv_label_create(scr->cooking_imgbtn);
    lv_label_set_text(Devices_cooking_imgbtn_label, "");
    lv_obj_align(Devices_cooking_imgbtn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->cooking_imgbtn, 22, 295);
    lv_obj_set_size(scr->cooking_imgbtn, 32, 32);

    // Set style of scr->cooking_imgbtn
    lv_obj_set_style_text_font(scr->cooking_imgbtn, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cooking_imgbtn
    lv_obj_add_event_cb(scr->cooking_imgbtn, Devices_cooking_imgbtn_pressed, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(scr->cooking_imgbtn, Devices_cooking_imgbtn_pressing, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(scr->cooking_imgbtn, Devices_cooking_imgbtn_released, LV_EVENT_RELEASED, NULL);

    // Init scr->cooking_label
    scr->cooking_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->cooking_label, "Cooking");
    lv_label_set_long_mode(scr->cooking_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->cooking_label, 60, 297);
    lv_obj_set_size(scr->cooking_label, 100, 32);
    lv_obj_add_flag(scr->cooking_label, LV_OBJ_FLAG_CLICKABLE);

    // Set style of scr->cooking_label
    lv_obj_set_style_text_font(scr->cooking_label, fs_alibabasans_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->cooking_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->cooking_label
    lv_obj_add_event_cb(scr->cooking_label, Devices_cooking_label_pressed, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(scr->cooking_label, Devices_cooking_label_pressing, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(scr->cooking_label, Devices_cooking_label_released, LV_EVENT_RELEASED, NULL);

    // Init scr->devices_ingbtn
    scr->devices_ingbtn = lv_imgbtn_create(scr->obj);
    lv_imgbtn_set_src(scr->devices_ingbtn, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(device_icon.png), NULL);
    lv_imgbtn_set_src(scr->devices_ingbtn, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(device_icon_green.png), NULL);
    lv_obj_t *Devices_devices_ingbtn_label = lv_label_create(scr->devices_ingbtn);
    lv_label_set_text(Devices_devices_ingbtn_label, "");
    lv_obj_align(Devices_devices_ingbtn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->devices_ingbtn, 22, 353);
    lv_obj_set_size(scr->devices_ingbtn, 32, 32);

    // Set style of scr->devices_ingbtn
    lv_obj_set_style_text_font(scr->devices_ingbtn, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->devices_ingbtn
    lv_obj_add_event_cb(scr->devices_ingbtn, Devices_devices_ingbtn_pressed, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(scr->devices_ingbtn, Devices_devices_ingbtn_pressing, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(scr->devices_ingbtn, Devices_devices_ingbtn_released, LV_EVENT_RELEASED, NULL);

    // Init scr->devices_label
    scr->devices_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->devices_label, "Devices");
    lv_label_set_long_mode(scr->devices_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->devices_label, 60, 354);
    lv_obj_set_size(scr->devices_label, 100, 32);

    // Set style of scr->devices_label
    lv_obj_set_style_text_font(scr->devices_label, fs_alibabasans_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->devices_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->left_bg_line1
    scr->left_bg_line1 = lv_line_create(scr->obj);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t left_bg_line1_point[] ={{0, 0}, {180, 0}};
#else
    static lv_point_precise_t left_bg_line1_point[] ={{0, 0}, {180, 0}};
#endif
    lv_line_set_points(scr->left_bg_line1, left_bg_line1_point, 2);
    lv_obj_set_pos(scr->left_bg_line1, 10, 410);
    lv_obj_set_size(scr->left_bg_line1, 184, 3);

    // Set style of scr->left_bg_line1
    lv_obj_set_style_line_color(scr->left_bg_line1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(scr->left_bg_line1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->setting_imgbtn
    scr->setting_imgbtn = lv_imgbtn_create(scr->obj);
    lv_imgbtn_set_src(scr->setting_imgbtn, LV_IMGBTN_STATE_RELEASED, NULL, LVGL_IMAGE_PATH(setting_icon.png), NULL);
    lv_imgbtn_set_src(scr->setting_imgbtn, LV_IMGBTN_STATE_PRESSED, NULL, LVGL_IMAGE_PATH(setting_icon_green.png), NULL);
    lv_obj_t *Devices_setting_imgbtn_label = lv_label_create(scr->setting_imgbtn);
    lv_label_set_text(Devices_setting_imgbtn_label, "");
    lv_obj_align(Devices_setting_imgbtn_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->setting_imgbtn, 22, 427);
    lv_obj_set_size(scr->setting_imgbtn, 32, 32);

    // Set style of scr->setting_imgbtn
    lv_obj_set_style_text_font(scr->setting_imgbtn, fs_alibabasans_bold_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->setting_imgbtn
    lv_obj_add_event_cb(scr->setting_imgbtn, Devices_setting_imgbtn_pressed, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(scr->setting_imgbtn, Devices_setting_imgbtn_pressing, LV_EVENT_PRESSING, NULL);
    lv_obj_add_event_cb(scr->setting_imgbtn, Devices_setting_imgbtn_released, LV_EVENT_RELEASED, NULL);

    // Init scr->setting_label
    scr->setting_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->setting_label, "setting");
    lv_label_set_long_mode(scr->setting_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->setting_label, 60, 427);
    lv_obj_set_size(scr->setting_label, 100, 32);

    // Set style of scr->setting_label
    lv_obj_set_style_text_font(scr->setting_label, fs_alibabasans_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->setting_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->main_bg_line0
    scr->main_bg_line0 = lv_line_create(scr->obj);
#if LVGL_VERSION_MAJOR == 8
    static lv_point_t main_bg_line0_point[] ={{0, 0}, {780, 0}};
#else
    static lv_point_precise_t main_bg_line0_point[] ={{0, 0}, {780, 0}};
#endif
    lv_line_set_points(scr->main_bg_line0, main_bg_line0_point, 2);
    lv_obj_set_pos(scr->main_bg_line0, 224, 107);
    lv_obj_set_size(scr->main_bg_line0, 780, 1);

    // Set style of scr->main_bg_line0
    lv_obj_set_style_bg_color(scr->main_bg_line0, lv_color_hex(0x4b4a4a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(scr->main_bg_line0, lv_color_hex(0x4b4a4a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->main_bg_line0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(scr->main_bg_line0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qr_code_img
    scr->qr_code_img = lv_img_create(scr->obj);
    lv_img_set_src(scr->qr_code_img, LVGL_IMAGE_PATH(qrcode_artinchip.png));
    lv_img_set_pivot(scr->qr_code_img, 50, 50);
    lv_img_set_angle(scr->qr_code_img, 0);
    lv_obj_set_style_img_opa(scr->qr_code_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->qr_code_img, 451, 141);

    // Set move animation of scr->qr_code_img
    lv_anim_t anim_qr_code_img_x;
    lv_anim_init(&anim_qr_code_img_x);
    lv_anim_set_var(&anim_qr_code_img_x, scr->qr_code_img);
    lv_anim_set_time(&anim_qr_code_img_x, 1000);
    lv_anim_set_exec_cb(&anim_qr_code_img_x, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_values(&anim_qr_code_img_x, 0, 451);
    lv_anim_set_path_cb(&anim_qr_code_img_x, lv_anim_path_ease_out);
    lv_anim_start(&anim_qr_code_img_x);

    lv_anim_t anim_qr_code_img_y;
    lv_anim_init(&anim_qr_code_img_y);
    lv_anim_set_var(&anim_qr_code_img_y, scr->qr_code_img);
    lv_anim_set_time(&anim_qr_code_img_y, 1000);
    lv_anim_set_exec_cb(&anim_qr_code_img_y, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&anim_qr_code_img_y, 141, 141);
    lv_anim_set_path_cb(&anim_qr_code_img_y, lv_anim_path_ease_out);
    lv_anim_start(&anim_qr_code_img_y);

    // Init scr->todo_label
    scr->todo_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->todo_label, "Todo...");
    lv_label_set_long_mode(scr->todo_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->todo_label, 563, 3);
    lv_obj_set_size(scr->todo_label, 100, 32);
    lv_obj_add_flag(scr->todo_label, LV_OBJ_FLAG_HIDDEN);

    // Set style of scr->todo_label
    lv_obj_set_style_text_font(scr->todo_label, fs_alibabasans_bold_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->todo_label, lv_color_hex(0x61d859), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->qrcode_font_image
    scr->qrcode_font_image = lv_img_create(scr->obj);
    lv_img_set_src(scr->qrcode_font_image, LVGL_IMAGE_PATH(qrcode.png));
    lv_img_set_pivot(scr->qrcode_font_image, 50, 50);
    lv_img_set_angle(scr->qrcode_font_image, 0);
    lv_obj_set_style_img_opa(scr->qrcode_font_image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->qrcode_font_image, 506, 51);

    // Init scr->qrcode_tip_font_image
    scr->qrcode_tip_font_image = lv_img_create(scr->obj);
    lv_img_set_src(scr->qrcode_tip_font_image, LVGL_IMAGE_PATH(font.png));
    lv_img_set_pivot(scr->qrcode_tip_font_image, 50, 50);
    lv_img_set_angle(scr->qrcode_tip_font_image, 0);
    lv_obj_set_style_img_opa(scr->qrcode_tip_font_image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->qrcode_tip_font_image, 381, 501);


}


