/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.3.0
 */

#include "custom.h"

void custom_init()
{
    /* Add your codes here */
}

