/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "aic_lang.h"
#include "custom/custom.h"

static lang_type_t current_lang = AIC_LANG_EN;

const aic_language_t languages[] = {
    {"en", ABEL_REGULAR_TTF, false},
    {"jp", DROIDSANSFALLBACK_TTF, false},
    {"zh", DROIDSANSFALLBACK_TTF, false}
};

const char *font_names[] = {
    "Abel-regular.ttf",
    "DroidSansFallback.ttf"
};

const char *translations[14][3] = {
    {"Chinese", "中国語", "中文"},
    {"Dark", "暗い", "暗色"},
    {"Display", "ディスプレイ", "显示"},
    {"English", "英語", "英语"},
    {"Japanese", "日本語", "日语"},
    {"Lamp", "ランプ", "电灯泡"},
    {"Language", "言語", "语言"},
    {"Light", "明るい", "亮色"},
    {"Setting", "設定", "设置"},
    {"Please switch languages on the setting page", "設定ページで言語を変更してください", "请在设置页面上切换语言"},
    {"Last night, the west wind withered the green trees, climbed the tall building alone, and looked out over the horizon", "昨夜の西風は碧の木をしおれて、ただ高いビルに上がって、天涯の道を眺め尽くします", "昨夜西风凋碧树，独上高楼，望尽天涯路"},
    {"My clothes grow daily more loose, yet care I not. For you am I thus wasting away in sorrow and pain", "身なりがだんだん広くなっても後悔せず、伊のためにやつれてしまった", "衣带渐宽终不悔，为伊消得人憔悴"},
    {"Searching for him in the crowd for thousands of times, suddenly looking back, the person was in a dimly lit place", "みんなは彼を千百度も探していたが、ふと振り返ってみると、あの人は明かりが消えかけているところにいた", "众里寻他千百度，蓦然回首，那人却在灯火阑珊处"},
    {"Multi Language Templates", "多言語テンプレート", "多语言模板"}
};

void aic_set_language(lang_type_t lang)
{
    current_lang  = lang;
}

const char *aic_get_translation(key_id_t key)
{
    return translations[key][current_lang];
}

const lv_font_t *aic_init_lang_font(int font_id, int font_size)
{
    const lv_font_t *font = aic_font_list_find(font_id, font_size);
    if (font)
        return font;

    char font_path[256] = {0};
    snprintf(font_path, sizeof(font_path) - 1, "%s/font/%s", LVGL_STORAGE_PATH, font_names[font_id]);

    font = ui_font_init(font_path, font_size);
    if (!font) {
        LV_LOG_ERROR("Failed to init font");
        return NULL;
    }

    aic_font_list_add(font_id, font_size, font);
    return font;
}

const lv_font_t *aic_get_lang_font(int font_id, int font_size, bool c_flag)
{
    if (c_flag)
        return aic_get_c_font(font_id, font_size);
    else
        return aic_init_lang_font(font_id, font_size);
}

const lv_font_t *aic_get_multi_lang_font(int font_size)
{
    const aic_language_t *lang = get_current_lang();
    return aic_get_lang_font(lang->font_id, font_size, lang->c_flag);
}

const lv_font_t *aic_get_c_font(int font_id, int font_size)
{
    switch (font_id) {

        default:
            return NULL;
    }
}

const aic_language_t *get_current_lang()
{
    return &languages[current_lang];
}
