/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "aic_lang.h"

void __attribute__((weak)) screen_1_TO_SCREEN_SWITCH_custom_clicked(void) {
}

static void screen_1_TO_SCREEN_SWITCH_clicked (lv_event_t *e) {
    screen_1_TO_SCREEN_SWITCH_custom_clicked();
}


void screen_1_create(ui_manager_t *ui)
{
    screen_1_t *scr = screen_1_get(ui);

    if (!ui->auto_del && scr->obj) {
        screen_1_update_current_language();
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->TO_SCREEN_SWITCH
    scr->TO_SCREEN_SWITCH = lv_img_create(scr->obj);
    lv_img_set_src(scr->TO_SCREEN_SWITCH, LVGL_IMAGE_PATH(setting_w_50x50.png));
    lv_img_set_pivot(scr->TO_SCREEN_SWITCH, 50, 50);
    lv_img_set_angle(scr->TO_SCREEN_SWITCH, 0);
    lv_obj_set_style_img_opa(scr->TO_SCREEN_SWITCH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->TO_SCREEN_SWITCH, 25, 522);
    lv_obj_add_flag(scr->TO_SCREEN_SWITCH, LV_OBJ_FLAG_CLICKABLE);

    // Set event handler of scr->TO_SCREEN_SWITCH
    lv_obj_add_event_cb(scr->TO_SCREEN_SWITCH, screen_1_TO_SCREEN_SWITCH_clicked, LV_EVENT_CLICKED, NULL);

    // Init scr->TEXT_BG1
    scr->TEXT_BG1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->TEXT_BG1, LVGL_IMAGE_PATH(bg1_400x220.png));
    lv_img_set_pivot(scr->TEXT_BG1, 50, 50);
    lv_img_set_angle(scr->TEXT_BG1, 0);
    lv_obj_set_style_img_opa(scr->TEXT_BG1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->TEXT_BG1, 120, 272);

    // Init scr->TEXT_BG3
    scr->TEXT_BG3 = lv_img_create(scr->obj);
    lv_img_set_src(scr->TEXT_BG3, LVGL_IMAGE_PATH(bg3_400x200.png));
    lv_img_set_pivot(scr->TEXT_BG3, 50, 50);
    lv_img_set_angle(scr->TEXT_BG3, 0);
    lv_obj_set_style_img_opa(scr->TEXT_BG3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->TEXT_BG3, 565, 46);

    // Init scr->TEXT_BG2
    scr->TEXT_BG2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->TEXT_BG2, LVGL_IMAGE_PATH(bg2_400x220.png));
    lv_img_set_pivot(scr->TEXT_BG2, 50, 50);
    lv_img_set_angle(scr->TEXT_BG2, 0);
    lv_obj_set_style_img_opa(scr->TEXT_BG2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->TEXT_BG2, 565, 272);

    // Init scr->TITLE
    scr->TITLE = lv_label_create(scr->obj);
    lv_label_set_text(scr->TITLE, aic_get_translation(TITLE));
    lv_label_set_long_mode(scr->TITLE, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->TITLE, 135, 119);
    lv_obj_set_size(scr->TITLE, 394, 93);

    // Set style of scr->TITLE
    lv_obj_set_style_text_font(scr->TITLE, aic_get_multi_lang_font(30), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->TEXT
    scr->TEXT = lv_label_create(scr->obj);
    lv_label_set_text(scr->TEXT, aic_get_translation(TEXT));
    lv_label_set_long_mode(scr->TEXT, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->TEXT, 135, 173);
    lv_obj_set_size(scr->TEXT, 442, 61);

    // Set style of scr->TEXT
    lv_obj_set_style_text_font(scr->TEXT, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->TEXT1
    scr->TEXT1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->TEXT1, aic_get_translation(TEXT1));
    lv_label_set_long_mode(scr->TEXT1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->TEXT1, 176, 324);
    lv_obj_set_size(scr->TEXT1, 296, 133);

    // Set style of scr->TEXT1
    lv_obj_set_style_text_font(scr->TEXT1, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->TEXT2
    scr->TEXT2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->TEXT2, aic_get_translation(TEXT2));
    lv_label_set_long_mode(scr->TEXT2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->TEXT2, 645, 327);
    lv_obj_set_size(scr->TEXT2, 252, 113);

    // Set style of scr->TEXT2
    lv_obj_set_style_text_font(scr->TEXT2, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->TEXT3
    scr->TEXT3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->TEXT3, aic_get_translation(TEXT3));
    lv_label_set_long_mode(scr->TEXT3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->TEXT3, 645, 92);
    lv_obj_set_size(scr->TEXT3, 259, 125);

    // Set style of scr->TEXT3
    lv_obj_set_style_text_font(scr->TEXT3, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);


}

void screen_1_update_language(lang_type_t lang)
{
    aic_set_language(lang);
    screen_1_update_current_language();
}

void screen_1_update_current_language()
{
    screen_1_t *scr = screen_1_get(&ui_manager);
    lv_obj_set_style_text_font(scr->TITLE, aic_get_multi_lang_font(30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->TITLE, aic_get_translation(TITLE));

    lv_obj_set_style_text_font(scr->TEXT, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->TEXT, aic_get_translation(TEXT));

    lv_obj_set_style_text_font(scr->TEXT1, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->TEXT1, aic_get_translation(TEXT1));

    lv_obj_set_style_text_font(scr->TEXT2, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->TEXT2, aic_get_translation(TEXT2));

    lv_obj_set_style_text_font(scr->TEXT3, aic_get_multi_lang_font(20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(scr->TEXT3, aic_get_translation(TEXT3));

}

