/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"
#include "aic_lang.h"

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *SETTING_LABEL;
    lv_obj_t *ENGLISH_BTN;
    lv_obj_t *CHINESE_BTN;
    lv_obj_t *JAPANESE_BTN;
    lv_obj_t *LAN_LABEL;
    lv_obj_t *ENGLISH_SELECT;
    lv_obj_t *CHINESE_SELECT;
    lv_obj_t *JAPANESE_SELECT;
    lv_obj_t *DISPLAY_LABEL;
    lv_obj_t *DISPLAY_IMG;
    lv_obj_t *LAN_OPT_IMG;
    lv_obj_t *DARK_BTN;
    lv_obj_t *LIGHT_BTN;
    lv_obj_t *DARK_SELECT;
    lv_obj_t *SCREEN_1_SWITCH;
    lv_obj_t *LIGHT_BG;
    lv_obj_t *LIGHT_OFF;
    lv_obj_t *LIGHT_SELECT;
    lv_obj_t *LIGHT_ON;
    lv_obj_t *VOLUME_SLIDER;
    lv_obj_t *VOLUME_IMG;
    lv_obj_t *WIFI_IMG;
    lv_obj_t *WIFI_SWITCH;
    lv_obj_t *LAMP_LABEL;
    lv_obj_t *WIFI_IMG_OFF;
} screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *TO_SCREEN_SWITCH;
    lv_obj_t *TEXT_BG1;
    lv_obj_t *TEXT_BG3;
    lv_obj_t *TEXT_BG2;
    lv_obj_t *TITLE;
    lv_obj_t *TEXT;
    lv_obj_t *TEXT1;
    lv_obj_t *TEXT2;
    lv_obj_t *TEXT3;
} screen_1_t;


typedef struct {
    bool auto_del;
    screen_t screen;
    screen_1_t screen_1;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}

static inline screen_1_t *screen_1_get(ui_manager_t *ui)
{
    return &ui->screen_1;
}


void screen_create(ui_manager_t *ui);
void screen_1_create(ui_manager_t *ui);

void screen_update_language(lang_type_t lang);
void screen_update_current_language();
void screen_1_update_language(lang_type_t lang);
void screen_1_update_current_language();



extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
