/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.5
 */

#ifndef CUSTOM_CODE
#define CUSTOM_CODE
#ifdef __cplusplus
extern "C" {
#endif

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

typedef enum {
    LAMP_OFF,
    LAMP_ON
}lamp_status;

typedef enum {
    DISPLAY_DARK,
    DISPLAY_LIGHT
}display_mode;

void custom_init();

void update_current_language(lang_type_t lang);

void update_current_status(lamp_status status);

void update_current_mode(display_mode mode);

void screen_language_setting_select(lang_type_t lan);

void screen_display_setting_select(display_mode mode);

void display_mode_swicth(display_mode mode);

void wifi_switch_img();

void switch_srceen_to_srceen_1();

void switch_srceen_1_to_srceen();

void switch_screen_language_handle();

void switch_screen_display_handle();

void switch_screen_light_handle();

void switch_screen_wifi_handle();

void screen_WIFI_SWITCH_custom_clicked();

void screen_ENGLISH_BTN_custom_clicked();

void screen_CHINESE_BTN_custom_clicked();

void screen_JAPANESE_BTN_custom_clicked();

void screen_DARK_BTN_custom_clicked();

void screen_LIGHT_BTN_custom_clicked();

void screen_SCREEN_1_SWITCH_custom_clicked();

void screen_LIGHT_OFF_custom_clicked();

void screen_LIGHT_ON_custom_clicked();

void screen_1_TO_SCREEN_SWITCH_custom_clicked();


#ifdef __cplusplus
}
#endif
#endif /* CUSTOM_CODE */
