/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.1
 */

#include "custom.h"
#include "lv_aic_player.h"

static void switch_hidden_status_cb(lv_event_t *e);
static void switch_play_status_cb(lv_event_t *e);
static void set_player_scale_cb(lv_event_t *e);
static void set_next_player_cb(lv_event_t *e);
static void set_last_player_cb(lv_event_t *e);

void custom_init() {

}

void scr_video_play_control_custom_clicked(void) {
    scr_video_t *scr = scr_video_get(&ui_manager);

    lv_obj_t *player = scr->video_player;
    lv_obj_t *play_img = scr->play_control;

    if (strstr(lv_img_get_src(play_img), "pause_50x50.png")) {
        lv_img_set_src(play_img, LVGL_IMAGE_PATH(video/play_50x50.png));
        lv_aic_player_set_cmd(player, LV_AIC_PLAYER_CMD_PAUSE, NULL);
    } else {
        lv_img_set_src(play_img, LVGL_IMAGE_PATH(video/pause_50x50.png));
        lv_aic_player_set_cmd(player, LV_AIC_PLAYER_CMD_RESUME, NULL);
    }
}


void scr_video_video_player_custom_clicked(void){
	scr_video_t *scr = scr_video_get(&ui_manager);
    lv_obj_t *control_bar = scr->control_bar;
    lv_obj_t *file_name = scr->file_name;
    lv_obj_t *author = scr->author;
	lv_obj_t *back =scr->back;

	if (lv_obj_has_flag(control_bar, LV_OBJ_FLAG_HIDDEN)){
	    lv_obj_clear_flag(control_bar, LV_OBJ_FLAG_HIDDEN);
	    lv_obj_clear_flag(file_name, LV_OBJ_FLAG_HIDDEN);
	    lv_obj_clear_flag(author, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(back, LV_OBJ_FLAG_HIDDEN);
	}
	else{
	    lv_obj_add_flag(control_bar, LV_OBJ_FLAG_HIDDEN);
	    lv_obj_add_flag(file_name, LV_OBJ_FLAG_HIDDEN);
	    lv_obj_add_flag(author, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(back, LV_OBJ_FLAG_HIDDEN);
	}
}

void scr_video_zoom_custom_clicked(void) {
    scr_video_t *scr = scr_video_get(&ui_manager);
    lv_obj_t *zoom_img = scr->zoom;
    lv_obj_t *player = scr->video_player;
    printf("%s", lv_img_get_src(zoom_img));

    if (strstr(lv_img_get_src(zoom_img), "zoom_out_50x50.png")) {
        lv_img_set_src(zoom_img, LVGL_IMAGE_PATH(video/zoom_in_50x50.png));
        lv_obj_center(player);
        lv_aic_player_set_scale(player, 128);
    } else {
        lv_img_set_src(zoom_img, LVGL_IMAGE_PATH(video/zoom_out_50x50.png));
        lv_obj_center(player);
        lv_aic_player_set_scale(player, 256);
    }
}


//static void set_player(void)
//{
//    lv_obj_t *player = main_screen_get(&ui_manager)->player;
//    lv_obj_t *file_name_label = main_screen_get(&ui_manager)->file_name_label;
//    lv_obj_t *play_img = main_screen_get(&ui_manager)->play_img;
//
//    const char *path = player_list_get_path(player_list.current);
//    const char *name = player_list_get_name(player_list.current);
//    
//    if (path && name) {
//        lv_aic_player_set_src(player, path);
//        lv_aic_player_set_cmd(player, LV_AIC_PLAYER_CMD_START, NULL);
//        lv_label_set_text(file_name_label, name);
//        lv_img_set_src(play_img, LVGL_IMAGE_PATH(play.png));
//    } else {
//        printf("Error: Invalid path or name at index %d\n", player_list.current);
//    }
//}
//
//static void set_next_player_cb(lv_event_t *e)
//{
//    lv_event_code_t code = lv_event_get_code(e);
//
//    if (code == LV_EVENT_CLICKED)
//    {
//        player_list.current++;
//        if (player_list.current >= player_list.count)
//            player_list.current = 0;
//        set_player();
//    }
//}
//
//static void set_last_player_cb(lv_event_t *e)
//{
//    lv_event_code_t code = lv_event_get_code(e);
//
//    if (code == LV_EVENT_CLICKED)
//    {
//        player_list.current--;
//        if (player_list.current < 0)
//            player_list.current = player_list.count - 1;
//        set_player();
//    }
//}


