/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


void __attribute__((weak)) screen_custom_load_start(void) {
}
void __attribute__((weak)) screen_custom_unload_start(void) {
}

static void screen_unload_start (lv_event_t *e) {
    screen_custom_unload_start();
}

static void screen_load_start (lv_event_t *e) {
    screen_custom_load_start();
}


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(scr->obj, LVGL_IMAGE_PATH(main/bg.png), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->obj
    lv_obj_add_event_cb(scr->obj, screen_unload_start, LV_EVENT_SCREEN_UNLOAD_START, NULL);
    lv_obj_add_event_cb(scr->obj, screen_load_start, LV_EVENT_SCREEN_LOAD_START, NULL);

    // Init scr->speed_arc
    scr->speed_arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->speed_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->speed_arc, 0, 240);
    lv_arc_set_value(scr->speed_arc, 2);
    lv_arc_set_bg_angles(scr->speed_arc, 180, 45);
    lv_arc_set_angles(scr->speed_arc, 180, 181);
    lv_arc_set_rotation(scr->speed_arc, 0);
    lv_arc_set_change_rate(scr->speed_arc, 720);
    lv_obj_set_pos(scr->speed_arc, 31, 90);
    lv_obj_set_size(scr->speed_arc, 350, 350);

    // Set style of scr->speed_arc
    lv_obj_set_style_bg_color(scr->speed_arc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->speed_arc, 136, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->unit_label
    scr->unit_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->unit_label, "Km/h");
    lv_label_set_long_mode(scr->unit_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->unit_label, 171, 325);
    lv_obj_set_size(scr->unit_label, 70, 25);

    // Set style of scr->unit_label
    lv_obj_set_style_text_align(scr->unit_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->unit_label, lv_color_hex(0x47ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->unit_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->speed_label
    scr->speed_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->speed_label, "00");
    lv_label_set_long_mode(scr->speed_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->speed_label, 82, 155);
    lv_obj_set_size(scr->speed_label, 248, 151);

    // Set style of scr->speed_label
    lv_obj_set_style_outline_color(scr->speed_label, lv_color_hex(0x55ff7d), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->speed_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->speed_label, lv_color_hex(0x47ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->speed_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->speed_label, fs_droidsansfallback_140, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_arc
    scr->temp_arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->temp_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->temp_arc, 0, 100);
    lv_arc_set_value(scr->temp_arc, 40);
    lv_arc_set_bg_angles(scr->temp_arc, 135, 45);
    lv_arc_set_angles(scr->temp_arc, 135, 243);
    lv_arc_set_rotation(scr->temp_arc, 0);
    lv_arc_set_change_rate(scr->temp_arc, 720);
    lv_obj_set_pos(scr->temp_arc, 151, 425);
    lv_obj_set_size(scr->temp_arc, 110, 110);

    // Init scr->power_arc
    scr->power_arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->power_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->power_arc, 0, 100);
    lv_arc_set_value(scr->power_arc, 70);
    lv_arc_set_bg_angles(scr->power_arc, 135, 45);
    lv_arc_set_angles(scr->power_arc, 135, 324);
    lv_arc_set_rotation(scr->power_arc, 0);
    lv_arc_set_change_rate(scr->power_arc, 720);
    lv_obj_set_pos(scr->power_arc, 16, 425);
    lv_obj_set_size(scr->power_arc, 110, 110);

    // Init scr->battemp_arc
    scr->battemp_arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->battemp_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->battemp_arc, 0, 100);
    lv_arc_set_value(scr->battemp_arc, 30);
    lv_arc_set_bg_angles(scr->battemp_arc, 135, 45);
    lv_arc_set_angles(scr->battemp_arc, 135, 216);
    lv_arc_set_rotation(scr->battemp_arc, 0);
    lv_arc_set_change_rate(scr->battemp_arc, 720);
    lv_obj_set_pos(scr->battemp_arc, 286, 425);
    lv_obj_set_size(scr->battemp_arc, 110, 110);

    // Init scr->chart_1
    scr->chart_1 = lv_chart_create(scr->obj);
    lv_chart_set_type(scr->chart_1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(scr->chart_1, LV_CHART_AXIS_PRIMARY_Y, 0, 100);
    lv_chart_set_point_count(scr->chart_1, 5);

    lv_obj_set_pos(scr->chart_1, 6, 700);
    lv_obj_set_size(scr->chart_1, 400, 100);

    // Set style of scr->chart_1
    lv_obj_set_style_border_width(scr->chart_1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->chart_1, lv_color_hex(0x47ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(scr->chart_1, 53, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(scr->chart_1, lv_color_hex(0x47ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(scr->chart_1, 52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(scr->chart_1, lv_color_hex(0x47ffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(scr->chart_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_dash_width(scr->chart_1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->chart_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->power_label
    scr->power_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->power_label, "Power Output");
    lv_label_set_long_mode(scr->power_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->power_label, 11, 535);
    lv_obj_set_size(scr->power_label, 121, 25);

    // Set style of scr->power_label
    lv_obj_set_style_text_align(scr->power_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->power_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->power_label, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_label
    scr->temp_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp_label, "Motor Temp");
    lv_label_set_long_mode(scr->temp_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp_label, 145, 535);
    lv_obj_set_size(scr->temp_label, 121, 25);

    // Set style of scr->temp_label
    lv_obj_set_style_text_align(scr->temp_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->temp_label, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->battemp_label
    scr->battemp_label = lv_label_create(scr->obj);
    lv_label_set_text(scr->battemp_label, "Battery Temp");
    lv_label_set_long_mode(scr->battemp_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->battemp_label, 280, 535);
    lv_obj_set_size(scr->battemp_label, 121, 25);

    // Set style of scr->battemp_label
    lv_obj_set_style_text_align(scr->battemp_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->battemp_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->battemp_label, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->bettery_arc
    scr->bettery_arc = lv_arc_create(scr->obj);
    lv_arc_set_mode(scr->bettery_arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(scr->bettery_arc, 0, 100);
    lv_arc_set_value(scr->bettery_arc, 80);
    lv_arc_set_bg_angles(scr->bettery_arc, 180, 0);
    lv_arc_set_angles(scr->bettery_arc, 180, 324);
    lv_arc_set_rotation(scr->bettery_arc, 0);
    lv_arc_set_change_rate(scr->bettery_arc, 720);
    lv_obj_set_pos(scr->bettery_arc, 131, 833);
    lv_obj_set_size(scr->bettery_arc, 150, 150);

    // Init scr->power_num
    scr->power_num = lv_label_create(scr->obj);
    lv_label_set_text(scr->power_num, "40%");
    lv_label_set_long_mode(scr->power_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->power_num, 48, 470);
    lv_obj_set_size(scr->power_num, 45, 20);

    // Set style of scr->power_num
    lv_obj_set_style_bg_color(scr->power_num, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(scr->power_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->power_num, lv_color_hex(0xff66ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->power_num, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->temp_num
    scr->temp_num = lv_label_create(scr->obj);
    lv_label_set_text(scr->temp_num, "85%");
    lv_label_set_long_mode(scr->temp_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->temp_num, 183, 470);
    lv_obj_set_size(scr->temp_num, 45, 20);

    // Set style of scr->temp_num
    lv_obj_set_style_text_align(scr->temp_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->temp_num, lv_color_hex(0x9375ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->temp_num, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->battemp_num
    scr->battemp_num = lv_label_create(scr->obj);
    lv_label_set_text(scr->battemp_num, "70%");
    lv_label_set_long_mode(scr->battemp_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->battemp_num, 319, 470);
    lv_obj_set_size(scr->battemp_num, 45, 20);

    // Set style of scr->battemp_num
    lv_obj_set_style_text_align(scr->battemp_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->battemp_num, lv_color_hex(0xfd5353), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->battemp_num, fs_montserratmedium_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->battery_num
    scr->battery_num = lv_label_create(scr->obj);
    lv_label_set_text(scr->battery_num, "60%");
    lv_label_set_long_mode(scr->battery_num, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->battery_num, 176, 894);
    lv_obj_set_size(scr->battery_num, 60, 28);

    // Set style of scr->battery_num
    lv_obj_set_style_text_align(scr->battery_num, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->battery_num, lv_color_hex(0x00ff77), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->battery_num, fs_montserratmedium_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(main/bat_32x32.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_offset_x(scr->image_1, 0);
    lv_img_set_offset_y(scr->image_1, 0);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_pos(scr->image_1, 190, 855);


}


