/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_droidsansfallback_140;
lv_font_t *fs_droidsansfallback_18;
lv_font_t *fs_montserratmedium_20;
lv_font_t *fs_montserratmedium_22;

void ui_init(void)
{
    fs_droidsansfallback_140 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 140);
    fs_droidsansfallback_18 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 18);
    fs_montserratmedium_20 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 20);
    fs_montserratmedium_22 = ui_font_init(LVGL_FONT_PATH(montserratMedium.ttf), 22);
    if (!fs_droidsansfallback_140) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_140");
    	return;
    }
    if (!fs_droidsansfallback_18) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_18");
    	return;
    }
    if (!fs_montserratmedium_20) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_20");
    	return;
    }
    if (!fs_montserratmedium_22) {
    	LV_LOG_ERROR("Failed to init fs_montserratmedium_22");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    screen_create(&ui_manager);
    lv_scr_load(screen_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
