/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.1
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *speed_arc;
    lv_obj_t *unit_label;
    lv_obj_t *speed_label;
    lv_obj_t *temp_arc;
    lv_obj_t *power_arc;
    lv_obj_t *battemp_arc;
    lv_obj_t *chart_1;
    lv_obj_t *power_label;
    lv_obj_t *temp_label;
    lv_obj_t *battemp_label;
    lv_obj_t *bettery_arc;
    lv_obj_t *power_num;
    lv_obj_t *temp_num;
    lv_obj_t *battemp_num;
    lv_obj_t *battery_num;
    lv_obj_t *image_1;
} screen_t;


typedef struct {
    bool auto_del;
    screen_t screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}


void screen_create(ui_manager_t *ui);


extern lv_font_t *fs_droidsansfallback_140;
extern lv_font_t *fs_droidsansfallback_18;
extern lv_font_t *fs_montserratmedium_20;
extern lv_font_t *fs_montserratmedium_22;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
