/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.2.0
 */

#ifndef CUSTOM_CODE
#define CUSTOM_CODE
#ifdef __cplusplus
extern "C" {
#endif

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"

void custom_init();

int scene_get_selected_apng_image(void);

#ifdef __cplusplus
}
#endif
#endif /* CUSTOM_CODE */
