/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.2.0
 */

#include "custom.h"

void custom_init()
{
    /* Add your codes here */
}

